[package]
name = "taru-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
taru-addon-protocol = { path = "../taru-addon-protocol" }
taru-client-protocol = { path = "../taru-client-protocol" }
taru-core = { path = "../taru-core" }
taru-streaming = { path = "../taru-streaming" }
