[package]
name = "nako-metadata"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
nako-catalog = { path = "../nako-catalog" }
nako-core = { path = "../nako-core" }
nako-search = { path = "../nako-search" }
time.workspace = true
tokio.workspace = true

[dev-dependencies]
axum.workspace = true
nako-db = { path = "../nako-db" }
