[package]
name = "nako-addon-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0 OR MIT"
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
reqwest.workspace = true
serde_json.workspace = true
nako-addon-protocol = { path = "../nako-addon-protocol" }

[dev-dependencies]
tokio.workspace = true
