[package]
name = "nako-addon-client"
version = "0.1.0-alpha.2"
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0 OR MIT"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Rust HTTP caller helper for Nako Addon Sidecar integrations."
readme = "README.md"
keywords = ["nako", "addons", "client", "media-server"]
categories = ["api-bindings", "web-programming"]

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
nako-addon-protocol = { path = "../nako-addon-protocol", version = "0.1.0-alpha.2" }

[dev-dependencies]
tokio.workspace = true
