use crate::admin::ADMIN_API_VERSION;

const ADMIN_ROUTE_SUFFIXES: [(&str, &str); 24] = [
    ("overview", "overview"),
    ("addons", "addons"),
    ("addonDetail", "addons/:addon_id"),
    ("addonStatus", "addons/:addon_id/status"),
    ("addonUnregister", "addons/:addon_id/unregister"),
    ("addonHealthCheck", "addons/:addon_id/health-check"),
    ("addonSurfaces", "addons/:addon_id/surfaces"),
    ("addonInstallGuide", "addons/:addon_id/install-guide"),
    (
        "addonResourceCallDiagnostic",
        "addons/:addon_id/diagnostics/resource-call",
    ),
    (
        "acquisitionIntakeCandidates",
        "acquisition/intake/candidates",
    ),
    (
        "acquisitionIntakeWatchFolderDiscovery",
        "acquisition/intake/watch-folder-discovery",
    ),
    (
        "generatedArtifactProposals",
        "automation/generated-artifacts/proposals",
    ),
    (
        "generatedArtifactReviewPlan",
        "automation/generated-artifacts/{artifact_id}/review-plan",
    ),
    (
        "generatedArtifactReview",
        "automation/generated-artifacts/{artifact_id}/review",
    ),
    ("catalogGovernanceItems", "catalog/governance/items"),
    ("events", "events"),
    ("jobs", "jobs"),
    ("playbackSessions", "playback/sessions"),
    ("playbackRuntime", "playback/runtime"),
    ("playbackSupport", "playback/support"),
    (
        "addonRuntimeReadiness",
        "addons/{addon_id}/runtime-readiness",
    ),
    ("addonRoutingPlans", "addons/{addon_id}/routing-plans"),
    ("storageStaging", "storage/staging"),
    ("systemConfig", "system/config"),
];

#[must_use]
pub fn admin_typescript_contract() -> String {
    let mut output = String::new();
    output.push_str(
        "// Generated by `cargo run -p nako-api --example emit-admin-typescript-contract`.\n",
    );
    output.push_str("// Do not edit generated output by hand.\n\n");
    output.push_str(&format!(
        "export const NAKO_ADMIN_API_VERSION = \"{}\" as const;\n\n",
        ADMIN_API_VERSION
    ));
    output.push_str("export const NAKO_ADMIN_ROUTES = {\n");
    for (key, suffix) in ADMIN_ROUTE_SUFFIXES {
        output.push_str(&format!("  {key}: \"{}\",\n", admin_route_path(suffix)));
    }
    output.push_str("} as const;\n\n");
    output.push_str(CONTRACT_BODY);
    output
}

fn admin_route_path(suffix: &str) -> String {
    format!("/admin/{ADMIN_API_VERSION}/{suffix}")
}

const CONTRACT_BODY: &str = r#"export type AdminApiRouteKey = keyof typeof NAKO_ADMIN_ROUTES;

export interface AdminPageQuery {
  limit?: number;
  offset?: number;
}

export interface AdminCatalogGovernanceItemsQuery extends AdminPageQuery {
  library_id?: string;
  max_confidence_milli?: number;
}

export interface AdminOutboxEventsQuery extends AdminPageQuery {
  kind?: string;
  status?: string;
  library_id?: string;
  source_id?: string;
}

export interface AdminJobsQuery extends AdminPageQuery {
  status?: string;
  kind?: string;
  resource_class?: string;
  library_id?: string;
  source_id?: string;
}

export interface AdminPlaybackSessionsQuery extends AdminPageQuery {
  source_id?: string;
  kind?: string;
  state?: string;
}

export interface AdminPlaybackSupportQuery {
  session_id?: string;
  source_id?: string;
}

export interface AdminAcquisitionIntakeCandidatesQuery extends AdminPageQuery {
  library_id?: string;
  state?: string;
  source_kind?: string;
  managed_import_artifact_id?: string;
}

export interface AdminWatchFolderDiscoveryRequest {
  target_library_id: string;
  root_uri?: string;
  max_depth?: number;
}

export interface AdminStorageStagingQuery extends AdminPageQuery {
  purpose?: string;
  state?: string;
}

export interface AdminGeneratedArtifactProposalsQuery extends AdminPageQuery {}

export interface AdminGeneratedArtifactReviewRequest {
  decision: "accept" | "reject";
}
export type AddonStatus = "enabled" | "disabled" | "unregistered";

export type AddonScope =
  | "catalog_read"
  | "item_metadata_read"
  | "item_metadata_suggest"
  | "image_read"
  | "subtitle_read"
  | "stream_url_read"
  | "recommendation_write"
  | "automation_run"
  | "webhook_event_read";

export type AddonResource =
  | "catalog"
  | "metadata"
  | "image"
  | "stream"
  | "subtitle"
  | "recommendation"
  | "automation"
  | "webhook";

export type AddonEntryPointKind =
  | "item_action"
  | "library_action"
  | "admin_action"
  | "settings"
  | "diagnostics"
  | "task_launcher";

export type AddonPermission =
  | "metadata_write"
  | "artwork_write"
  | "subtitle_write"
  | "library_file_write";

export type AddonTokenStatus = "active" | "revoked" | "rotated";

export type AddonAuth = "none" | "bearer" | "shared_secret";

export type AdminAddonHealthCheckStatus =
  | "reachable"
  | "degraded"
  | "unhealthy"
  | "unreachable"
  | "protocol_mismatch"
  | "invalid_manifest";

export type AdminAddonResourceCallDiagnosticStatus =
  | "succeeded"
  | "missing_resource"
  | "missing_grant"
  | "authorization_gap"
  | "unreachable"
  | "protocol_mismatch"
  | "retryable_http_failure"
  | "http_failure"
  | "unsafe_response";

export interface AdminAddonsQuery {
  status?: AddonStatus;
}

export interface RegisterAddonRequest {
  id?: string;
  manifest: AdminAddonManifest;
  granted_scopes?: AddonScope[];
  status?: AddonStatus;
}

export interface AdminAddonResourceDeclaration {
  kind: AddonResource;
  path: string;
  input_schema: string | null;
  output_schema: string | null;
  required_scopes: AddonScope[];
  timeout_ms: number | null;
  max_attempts: number | null;
}

export interface AdminAddonManifest {
  id: string;
  name: string;
  version: string;
  protocol_version: string;
  base_url: string;
  description: string | null;
  resources: AdminAddonResourceDeclaration[];
  entry_points?: AdminAddonEntryPointDeclaration[];
  hosted_pages?: AdminAddonHostedPageDeclaration[];
  configuration_schema?: AdminAddonConfigurationSchemaDeclaration;
  secret_reference_fields?: AdminAddonSecretReferenceFieldDeclaration[];
  event_subscriptions?: AdminAddonEventSubscriptionDeclaration[];
  tasks?: AdminAddonTaskDeclaration[];
  auth: AddonAuth;
  default_timeout_ms: number | null;
  default_max_attempts: number | null;
  scopes: AddonScope[];
}

export interface AdminAddonEntryPointDeclaration {
  id: string;
  kind: AddonEntryPointKind;
  label: string;
  path: string;
  hosted_page_id?: string;
  required_scopes?: AddonScope[];
}

export interface AdminAddonHostedPageDeclaration {
  id: string;
  title: string;
  path: string;
  required_scopes?: AddonScope[];
}

export interface AdminAddonConfigurationSchemaDeclaration {
  schema_id: string;
  schema: Record<string, unknown>;
}

export interface AdminAddonSecretReferenceFieldDeclaration {
  id: string;
  label: string;
  description?: string;
  required?: boolean;
}

export interface AdminAddonEventSubscriptionDeclaration {
  id: string;
  event_kind: string;
  path: string;
  required_scopes?: AddonScope[];
  filters?: Record<string, unknown>;
}

export interface AdminAddonTaskDeclaration {
  id: string;
  name: string;
  path: string;
  description?: string;
  required_scopes?: AddonScope[];
  timeout_ms?: number;
  max_attempts?: number;
}

export interface AdminAddonRegistrationSummary {
  id: string;
  manifest_id: string;
  name: string;
  version: string;
  protocol_version: string;
  base_url: string;
  granted_scopes: string[];
  status: AddonStatus;
  created_at: string;
  updated_at: string;
}

export interface AdminAddonRegistrationDetail {
  summary: AdminAddonRegistrationSummary;
  manifest: AdminAddonManifest;
}

export interface AdminAddonRegistrationResponse {
  addon: AdminAddonRegistrationDetail;
}

export interface AdminAddonRegistrationsResponse {
  addons: AdminAddonRegistrationSummary[];
}

export interface UpdateAddonStatusRequest {
  status: AddonStatus;
}

export interface AdminAddonHealthCheckResponse {
  addon_id: string;
  manifest_id: string;
  status: AdminAddonHealthCheckStatus;
  latency_ms: number;
  protocol_version?: string;
  addon_version?: string;
  resource_count?: number;
  protocol_checked_at?: string;
  safe_error_code?: string;
}

export interface AdminAddonEntryPointSurface {
  id: string;
  kind: AddonEntryPointKind;
  label: string;
  path: string;
  hosted_page_id?: string;
  required_scopes: AddonScope[];
}

export interface AdminAddonHostedPageSurface {
  id: string;
  title: string;
  path: string;
  url: string;
  required_scopes: AddonScope[];
}

export interface AdminAddonConfigurationSchemaSurface {
  schema_id: string;
  schema: Record<string, unknown>;
}

export interface AdminAddonSecretReferenceFieldSurface {
  id: string;
  label: string;
  description?: string;
  required: boolean;
}

export interface AdminAddonTaskSurface {
  id: string;
  name: string;
  path: string;
  description?: string;
  required_scopes: AddonScope[];
  timeout_ms?: number;
  max_attempts?: number;
}

export interface AdminAddonEventSubscriptionSurface {
  id: string;
  event_kind: string;
  path: string;
  required_scopes: AddonScope[];
  filters: Record<string, unknown>;
}

export interface AdminAddonSurfacesResponse {
  addon_id: string;
  manifest_id: string;
  entry_points: AdminAddonEntryPointSurface[];
  hosted_pages: AdminAddonHostedPageSurface[];
  configuration_schema?: AdminAddonConfigurationSchemaSurface;
  secret_reference_fields: AdminAddonSecretReferenceFieldSurface[];
  tasks: AdminAddonTaskSurface[];
  event_subscriptions: AdminAddonEventSubscriptionSurface[];
}

export interface AdminAddonResourceCallDiagnosticRequest {
  resource: AddonResource;
  payload?: Record<string, unknown>;
}

export interface AdminAddonResourceCallDiagnosticResponse {
  addon_id: string;
  manifest_id: string;
  resource: AddonResource;
  status: AdminAddonResourceCallDiagnosticStatus;
  latency_ms: number;
  attempts: number;
  http_status?: number;
  safe_error_code?: string;
}

export interface AdminAddonInstallGuideResponse {
  addon_id: string;
  manifest_id: string;
  addon_name: string;
  addon_version: string;
  protocol_version: string;
  base_url: string;
  status: AddonStatus;
  docker_compose: AdminAddonInstallGuideSnippet;
  systemd: AdminAddonInstallGuideSnippet;
  secret_references: AdminAddonInstallGuideSecretReference[];
  health_check_steps: AdminAddonInstallGuideStep[];
  registration_verification_steps: AdminAddonInstallGuideStep[];
  lifecycle_boundary: AdminAddonInstallGuideLifecycleBoundary;
}

export interface AdminAddonInstallGuideSnippet {
  title: string;
  filename: string;
  content: string;
  notes: string[];
}

export interface AdminAddonInstallGuideSecretReference {
  id: string;
  label: string;
  description?: string;
  required: boolean;
  env_var: string;
  placeholder: string;
}

export interface AdminAddonInstallGuideStep {
  title: string;
  command: string;
  expected_result: string;
}

export interface AdminAddonInstallGuideLifecycleBoundary {
  nako_manages_containers: boolean;
  nako_manages_processes: boolean;
  nako_manages_packages: boolean;
  message: string;
}

export interface IssueAddonTokenRequest {
  label?: string;
}

export interface AddonTokenSummary {
  id: string;
  addon_id: string;
  label: string;
  token_prefix: string;
  status: AddonTokenStatus;
  created_at: string;
  rotated_at: string | null;
  revoked_at: string | null;
  last_used_at: string | null;
}

export interface AddonTokensResponse {
  tokens: AddonTokenSummary[];
}

export interface AddonTokenResponse {
  token: AddonTokenSummary;
}

export interface AddonTokenIssuedResponse {
  token: AddonTokenSummary;
  raw_token: string;
}

export interface AddonTokenRotationResponse {
  rotated: AddonTokenSummary;
  token: AddonTokenSummary;
  raw_token: string;
}

export interface ReplaceAddonGrantsRequest {
  grants?: AddonGrantAssignment[];
}

export interface AddonGrantAssignment {
  permission: AddonPermission;
  library_id?: string | null;
}

export interface AddonGrantRecord {
  id: string;
  addon_id: string;
  permission: AddonPermission;
  library_id: string | null;
  created_at: string;
}

export interface AddonGrantsResponse {
  grants: AddonGrantRecord[];
}

export interface PageInfo {
  limit: number;
  offset: number;
  returned: number;
}

export type AdminOverviewStatus = "healthy" | "degraded";

export interface AdminOverviewResponse {
  admin_api_version: string;
  public_api_version: string;
  status: AdminOverviewStatus;
  storage: {
    total_backends: number;
    ready_backends: number;
    degraded_backends: number;
    unavailable_backends: number;
    backends: Array<{
      library_id: string;
      library_name: string;
      backend_kind: string;
      status: string;
    }>;
  };
  metadata: {
    total_providers: number;
    available_providers: number;
    disabled_providers: number;
    unavailable_providers: number;
    providers: Array<{
      provider: string;
      status: string;
    }>;
  };
  runtime: {
    active_tasks: number;
    completed_tasks: number;
    failed_tasks: number;
    succeeded_jobs: number;
    cancelled_jobs: number;
    failed_jobs: number;
    shutdown_requested: boolean;
  };
  startup: {
    configured_libraries: number;
    recovered_transcode_sessions: number;
    recovered_jobs: number;
    staging_deleted_records: number;
    staging_deleted_files: number;
    metadata_raw_cache_deleted: number;
    metadata_lifecycle_tasks_started: number;
    artwork_ingest_worker_started: boolean;
  };
}

export interface AdminCatalogGovernanceItemListResponse {
  items: AdminCatalogGovernanceItem[];
  page: PageInfo;
}

export interface AdminCatalogGovernanceItem {
  item_id: string;
  library_id: string;
  kind: string;
  parent_id: string | null;
  title: string;
  release_date: string | null;
  source_count: number;
  representative_source_id: string | null;
  representative_file_name: string | null;
  local_inference: AdminLocalInferenceSummary | null;
  provider_mapping_count: number;
  accepted_provider_mapping_count: number;
  duplicate_relationship_count: number;
  issues: string[];
}

export interface AdminLocalInferenceSummary {
  source_id: string;
  inferred_kind: string;
  inferred_title: string | null;
  inferred_year: number | null;
  inferred_season: number | null;
  inferred_episode: number | null;
  confidence_milli: number | null;
  evidence_source: string;
  has_evidence: boolean;
  inference_version: string;
}

export interface AdminOutboxEventListResponse {
  events: AdminOutboxEventListItem[];
  page: PageInfo;
}

export interface AdminOutboxEventListItem {
  id: string;
  kind: string;
  subject: string | Record<string, unknown>;
  library_id: string | null;
  source_id: string | null;
  status: string;
  attempts: number;
  has_payload: boolean;
  has_error: boolean;
  occurred_at: string;
  updated_at: string;
  next_attempt_at: string | null;
}

export interface AdminJobListItem {
  id: string;
  kind: string;
  status: string;
  resource_class: string;
  library_id: string | null;
  source_id: string | null;
  has_input: boolean;
  has_summary: boolean;
  has_error: boolean;
  queued_at: string;
  started_at: string | null;
  completed_at: string | null;
}

export interface AdminJobListResponse {
  jobs: AdminJobListItem[];
  page: PageInfo;
}

export interface AdminPlaybackSessionListItem {
  id: string;
  source_id: string;
  kind: string;
  request_key: string;
  state: string;
  failure_category: string | null;
  has_failure_message: boolean;
  active: boolean;
  terminal: boolean;
  created_at: string;
  updated_at: string;
  started_at: string | null;
  completed_at: string | null;
}

export interface AdminPlaybackSessionListResponse {
  sessions: AdminPlaybackSessionListItem[];
  page: PageInfo;
}

export interface AdminAcquisitionIntakeCandidateListResponse {
  admin_api_version: string;
  public_api_version: string;
  candidates: AdminAcquisitionIntakeCandidateDiagnostic[];
  page: PageInfo;
}

export interface AdminAcquisitionIntakeCandidateDiagnostic {
  id: string;
  target_library_id: string;
  source_kind: string;
  custom_source_kind: boolean;
  source_scheme: string | null;
  source_ref_redacted: string;
  source_key_fingerprint: string;
  has_display_name: boolean;
  has_intended_locator: boolean;
  size_bytes: number | null;
  has_fingerprint: boolean;
  managed_import_artifact_id: string | null;
  state: string;
  has_diagnostics: boolean;
  first_seen_at_ms: number;
  last_seen_at_ms: number;
  created_at_ms: number;
  updated_at_ms: number;
}

export interface AdminWatchFolderDiscoveryResponse {
  admin_api_version: string;
  public_api_version: string;
  target_library_id: string;
  root_scheme: string | null;
  root_ref_redacted: string;
  ready_candidates: number;
  blocked_candidates: number;
  incomplete_candidates: number;
  unsupported_candidates: number;
  recorded_candidates: number;
  failures: Array<{
    ref_redacted: string;
    safe_message: string;
  }>;
  writes_library: boolean;
  managed_import_artifacts_created: boolean;
  promotion_apply: boolean;
}

export interface AdminGeneratedArtifactProposalListResponse {
  admin_api_version: string;
  public_api_version: string;
  proposals: AdminGeneratedArtifactProposal[];
  page: PageInfo;
}

export interface AdminGeneratedArtifactProposal {
  id: string;
  kind: string;
  capability: string;
  status: string;
  target: AdminGeneratedArtifactTarget;
  provenance: AdminGeneratedArtifactProvenance;
  payload: AdminGeneratedArtifactPayloadSummary;
  readiness: AdminGeneratedArtifactReadiness;
  created_at: string;
  updated_at: string;
  accepted_at: string | null;
}

export interface AdminGeneratedArtifactTarget {
  kind: string;
  library_id: string | null;
  item_id: string | null;
  source_id: string | null;
}

export interface AdminGeneratedArtifactProvenance {
  provider_id: string;
  provider_name: string | null;
  job_id: string;
  capability: string;
  idempotency_key_fingerprint: string | null;
  prompt_fingerprint: string | null;
  attempt_count: number | null;
  artifact_created_at: string;
}

export interface AdminGeneratedArtifactPayloadSummary {
  valid_json: boolean;
  shape: string;
  payload_fingerprint: string;
  payload_bytes: number;
  object_field_count: number | null;
  array_item_count: number | null;
  has_textual_values: boolean;
  has_explanation: boolean;
  confidence_milli: number | null;
}

export interface AdminGeneratedArtifactReadiness {
  status: string;
  actionable: boolean;
  reasons: string[];
}

export interface AdminGeneratedArtifactReviewPlanResponse {
  admin_api_version: string;
  public_api_version: string;
  plan: AdminGeneratedArtifactAcceptancePlan;
}

export interface AdminGeneratedArtifactReviewResponse {
  admin_api_version: string;
  public_api_version: string;
  artifact_id: string;
  decision: "accept" | "reject";
  artifact_status: string;
  accepted_at: string | null;
  idempotent_replay: boolean;
  plan: AdminGeneratedArtifactAcceptancePlan;
}

export interface AdminGeneratedArtifactAcceptancePlan {
  artifact_id: string;
  decision: "accept" | "reject";
  status: string;
  action: string;
  reasons: string[];
  capability: string;
  kind: string;
  target: AdminGeneratedArtifactTarget;
  payload: AdminGeneratedArtifactPayloadSummary;
  readiness: AdminGeneratedArtifactReadiness;
  boundary: {
    accepted_into_canonical_metadata: boolean;
    writes_sidecar: boolean;
    writes_library_files: boolean;
    applies_immediately: boolean;
    requires_metadata_authority_apply: boolean;
  };
}

export interface AdminPlaybackRuntimeDiagnosticsResponse {
  admin_api_version: string;
  public_api_version: string;
  readiness: {
    status: string;
    reason: string;
    checks: Array<{
      name: string;
      status: string;
      reason: string;
    }>;
  };
  ffmpeg: {
    probe_status: string;
    has_probe_error: boolean;
    hardware_capability_count: number;
    available_gpu_capabilities: number;
  };
  hardware: {
    policy: Record<string, unknown>;
    selection: {
      acceleration: string;
      fallback_used: boolean;
      reason: string;
    };
    capabilities: Array<{
      accelerator: string;
      available: boolean;
      reason_code: string;
      encoder_discovery: {
        status: string;
        encoder: string | null;
        has_detail: boolean;
      };
      device_initialization: {
        status: string;
        operator_check: string;
        has_detail: boolean;
      };
      smoke_probe: {
        status: string;
        operator_check: string;
        has_detail: boolean;
      };
    }>;
  };
  transcode: {
    configured_cpu_slots: number;
    configured_gpu_slots: number;
    effective_cpu_slots: number;
    effective_gpu_slots: number;
    selected_hls_slots: number;
  };
  remux: {
    max_concurrent_sessions: number;
    timeout_ms: number;
  };
  remote_playback: {
    backend_count: number;
    stream_permits_available: number;
    stream_permits_max: number;
    stage_permits_available: number;
    stage_permits_max: number;
    state_scope: string;
  };
  staging: {
    max_bytes: number;
    retention_ms: number;
    cleanup_on_startup: boolean;
    startup_deleted_records: number;
    startup_deleted_files: number;
  };
}

export interface AdminPlaybackSupportEvidenceResponse {
  admin_api_version: string;
  public_api_version: string;
  subject: {
    session_id: string | null;
    source_id: string | null;
  };
  session: {
    id: string;
    source_id: string;
    kind: string;
    state: string;
    failure_category: string | null;
    has_failure_message: boolean;
    active: boolean;
    terminal: boolean;
    request_key_fingerprint: string;
    output_artifact_kind: string;
    created_at: string;
    updated_at: string;
    started_at: string | null;
    completed_at: string | null;
  } | null;
  source: {
    source_id: string;
    library_id: string;
    item_id: string;
    source_scheme: string;
    file_name: string;
    size_bytes: number | null;
    has_fingerprint: boolean;
  } | null;
  runtime: {
    readiness: AdminPlaybackRuntimeDiagnosticsResponse["readiness"];
    ffmpeg: AdminPlaybackRuntimeDiagnosticsResponse["ffmpeg"];
    hardware: {
      policy: Record<string, unknown>;
      selected_acceleration: string;
      fallback_used: boolean;
      capability_count: number;
      unavailable_capabilities: Array<{
        accelerator: string;
        reason_code: string;
        encoder_discovery_status: string;
        device_initialization_status: string;
        smoke_probe_status: string;
      }>;
    };
    transcode: AdminPlaybackRuntimeDiagnosticsResponse["transcode"];
    remux: AdminPlaybackRuntimeDiagnosticsResponse["remux"];
    remote_playback: AdminPlaybackRuntimeDiagnosticsResponse["remote_playback"];
    staging: AdminPlaybackRuntimeDiagnosticsResponse["staging"];
  };
  redaction: {
    paths_redacted: boolean;
    source_references_redacted: boolean;
    ffmpeg_commands_redacted: boolean;
    stderr_redacted: boolean;
    credentials_redacted: boolean;
  };
}

export type AdminAddonRuntimeReadinessStatus = "ready" | "degraded" | "unavailable";

export type AdminAddonRuntimeReadinessReason =
  | "ready"
  | "unavailable"
  | "manifest_mismatch"
  | "protocol_mismatch"
  | "missing_grant"
  | "missing_secret_reference"
  | "network_policy_blocked"
  | "sidecar_degraded"
  | "sidecar_unhealthy"
  | "unsafe_response";

export type AdminAddonRuntimeReadinessCheckName =
  | "reachability"
  | "protocol"
  | "manifest"
  | "grants"
  | "secret_references"
  | "network"
  | "safety";

export interface AdminAddonRuntimeReadinessResponse {
  addon_id: string;
  manifest_id: string;
  readiness: {
    status: AdminAddonRuntimeReadinessStatus;
    reason: AdminAddonRuntimeReadinessReason;
    checks: Array<{
      name: AdminAddonRuntimeReadinessCheckName;
      status: AdminAddonRuntimeReadinessStatus;
      reason: AdminAddonRuntimeReadinessReason;
      safe_error_code?: string;
    }>;
  };
}

export type AdminAddonRoutingDeclarationKind = "task" | "event_subscription";

export type AdminAddonRoutingPlanStatus = "executable" | "deferred";

export type AdminAddonRoutingPlanTarget = "addon_task_job" | "event_outbox" | "none";

export interface AdminAddonRoutingPlansResponse {
  addon_id: string;
  manifest_id: string;
  manifest_version: string;
  manifest_fingerprint: string;
  executable: number;
  deferred: number;
  plans: Array<{
    declaration_kind: AdminAddonRoutingDeclarationKind;
    declaration_id: string;
    status: AdminAddonRoutingPlanStatus;
    target: AdminAddonRoutingPlanTarget;
    safe_reason_code?: string;
    job_kind?: string;
    event_kind?: string;
    required_scope_count: number;
    filter_configured: boolean;
    timeout_ms?: number;
    max_attempts?: number;
  }>;
}

export interface AdminStorageStagingDiagnosticsResponse {
  admin_api_version: string;
  public_api_version: string;
  summary: {
    configured_max_bytes: number;
    used_manifest_bytes: number;
    cleanup_on_startup: boolean;
    retention_ms: number;
    startup_deleted_records: number;
    startup_deleted_files: number;
    process_cached_backends: number;
    vfs_cache: {
      object_count: number;
      listing_count: number;
      failure_count: number;
      stale_object_count: number;
      stale_listing_count: number;
      last_failure_at_ms: number | null;
    };
  };
  records: Array<{
    id: string;
    source_scheme: string;
    purpose: string;
    state: string;
    size_bytes: number | null;
    has_etag: boolean;
    has_fingerprint: boolean;
    active_leases: number;
    has_validation_error: boolean;
    created_at_ms: number;
    updated_at_ms: number;
    last_accessed_at_ms: number;
    expires_at_ms: number | null;
  }>;
  page: PageInfo;
}

export type AdminNetworkExposureMode =
  | "local_only"
  | "private_network"
  | "reverse_proxy"
  | "tunnel_provider";

export type AdminNetworkReadinessStatus = "ready" | "degraded" | "unavailable";

export type AdminNetworkReadinessReason =
  | "ready"
  | "local_only"
  | "auth_disabled"
  | "missing_external_base_url"
  | "missing_trusted_proxy_sources"
  | "missing_tunnel_provider"
  | "missing_tunnel_token"
  | "browser_origins_not_configured";

export type AdminNetworkReadinessCheckName =
  | "exposure_mode"
  | "auth"
  | "external_endpoint"
  | "trusted_proxy"
  | "origin_policy"
  | "tunnel_provider";

export type AdminTunnelProviderKind =
  | "external"
  | "cloudflare_tunnel"
  | "tailscale_funnel"
  | "ngrok";

export interface AdminNetworkAccessDiagnostics {
  exposure_mode: AdminNetworkExposureMode;
  readiness: {
    status: AdminNetworkReadinessStatus;
    reason: AdminNetworkReadinessReason;
    checks: Array<{
      name: AdminNetworkReadinessCheckName;
      status: AdminNetworkReadinessStatus;
      reason: AdminNetworkReadinessReason;
    }>;
  };
  external_endpoint: {
    configured: boolean;
    scheme: string | null;
    host_fingerprint: string | null;
  };
  trusted_proxy: {
    headers_enabled: boolean;
    source_count: number;
  };
  origins: {
    allowed_origin_count: number;
    configured: boolean;
  };
  tunnel_providers: Array<{
    id: string;
    kind: AdminTunnelProviderKind;
    endpoint_configured: boolean;
    endpoint_scheme: string | null;
    endpoint_host_fingerprint: string | null;
    token_env: string | null;
    token_present: boolean;
  }>;
}

export interface AdminServerConfigDiagnosticsResponse {
  admin_api_version: string;
  public_api_version: string;
  auth: {
    enabled: boolean;
    token_env: string | null;
  };
  network: AdminNetworkAccessDiagnostics;
  database: {
    configured_backend_kind: string;
    active_backend_kind: string;
    url_scheme: string;
    runtime_supported: boolean;
    migrated_on_startup: boolean;
    capabilities: {
      lifecycle: boolean;
      libraries: boolean;
      jobs: boolean;
      job_leases: boolean;
      media: boolean;
      scan_commits: boolean;
      metadata: boolean;
      catalog: boolean;
      playback_state: boolean;
      transcode_sessions: boolean;
      event_outbox: boolean;
      addons: boolean;
      automation: boolean;
      managed_artwork: boolean;
      vfs_cache: boolean;
      webhooks: boolean;
      search_index: boolean;
    };
  };
  runtime: {
    listen_addr: string;
    scan_concurrency: number;
    probe_concurrency: number;
    metadata_concurrency: number;
    remux_concurrency: number;
    webhook_concurrency: number;
    remux_timeout_ms: number;
  };
  libraries: Array<{
    id: string;
    name: string;
    preset: string;
    backend_kind: string;
    root_scheme: string;
    has_webdav_password_env: boolean;
    webdav_timeout_ms: number | null;
    webdav_max_attempts: number | null;
  }>;
  metadata: {
    raw_cache_retention_ms: number;
    raw_cache_cleanup_on_startup: boolean;
    raw_cache_cleanup_interval_ms: number;
    maintenance_policies: number;
    providers: Array<{
      provider: string;
      enabled: boolean;
      token_env: string | null;
      api_key_env: string | null;
      has_api_base_url: boolean;
      has_image_base_url: boolean;
      language: string | null;
      include_adult: boolean;
      header_count: number;
      secret_header_count: number;
      has_provider_runtime_override: boolean;
    }>;
    runtime: {
      timeout_ms: number;
      max_attempts: number;
      min_interval_ms: number;
      concurrency: number;
      user_agent: string;
      has_proxy: boolean;
      circuit_breaker_failures: number;
      circuit_breaker_backoff_ms: number;
    };
  };
  transcode: {
    hardware_policy: Record<string, unknown>;
    cpu_concurrency: number;
    gpu_concurrency: number;
  };
  staging: {
    max_bytes: number;
    retention_ms: number;
    cleanup_on_startup: boolean;
  };
  playback: {
    remote_stream_concurrency: number;
    remote_stage_concurrency: number;
  };
  artwork: {
    artifact_root_configured: boolean;
    fetch_timeout_ms: number;
    fetch_max_attempts: number;
    fetch_max_bytes: number;
    fetch_concurrency: number;
    ingest_worker_enabled: boolean;
    ingest_worker_idle_ms: number;
    fetch_user_agent: string;
    has_fetch_proxy: boolean;
    max_width: number;
    max_height: number;
  };
}
"#;

#[cfg(test)]
mod tests {
    use nako_client_protocol::public_client_paths;

    use super::*;

    #[test]
    fn admin_contract_includes_route_constants() {
        let contract = admin_typescript_contract();

        for (key, suffix) in ADMIN_ROUTE_SUFFIXES {
            let path = admin_route_path(suffix);
            assert!(
                contract.contains(&format!("{key}: \"{path}\"")),
                "Admin contract missing route constant {key} -> {path}"
            );
        }

        for expected in [
            "AdminCatalogGovernanceItemsQuery",
            "AdminOutboxEventsQuery",
            "AdminJobsQuery",
            "AdminPlaybackSessionsQuery",
            "AdminPlaybackSupportQuery",
            "AdminAddonsQuery",
            "RegisterAddonRequest",
            "AdminAddonManifest",
            "AdminAddonEntryPointDeclaration",
            "AdminAddonRegistrationSummary",
            "AdminAddonRegistrationsResponse",
            "AdminAddonRegistrationResponse",
            "UpdateAddonStatusRequest",
            "AdminAddonHealthCheckResponse",
            "AdminAddonSurfacesResponse",
            "AdminAddonInstallGuideResponse",
            "AdminAddonResourceCallDiagnosticRequest",
            "AdminAddonResourceCallDiagnosticResponse",
            "IssueAddonTokenRequest",
            "AddonTokensResponse",
            "AddonTokenIssuedResponse",
            "AddonTokenRotationResponse",
            "AddonTokenResponse",
            "ReplaceAddonGrantsRequest",
            "AddonGrantsResponse",
            "AdminAcquisitionIntakeCandidatesQuery",
            "AdminWatchFolderDiscoveryRequest",
            "AdminGeneratedArtifactProposalsQuery",
            "AdminGeneratedArtifactReviewRequest",
            "AdminAcquisitionIntakeCandidateListResponse",
            "AdminWatchFolderDiscoveryResponse",
            "AdminGeneratedArtifactProposalListResponse",
            "AdminGeneratedArtifactReviewPlanResponse",
            "AdminGeneratedArtifactReviewResponse",
            "AdminStorageStagingQuery",
            "AdminOverviewResponse",
            "AdminPlaybackSupportEvidenceResponse",
            "AdminAddonRuntimeReadinessResponse",
            "AdminAddonRoutingPlansResponse",
            "AdminNetworkAccessDiagnostics",
            "AdminServerConfigDiagnosticsResponse",
        ] {
            assert!(
                contract.contains(expected),
                "Admin contract missing {expected}"
            );
        }
    }

    #[test]
    fn admin_contract_excludes_generated_fetch_runtime_and_raw_sensitive_fields() {
        let contract = admin_typescript_contract().to_ascii_lowercase();

        for forbidden in [
            "class adminapiclient",
            "fetchlike",
            "requestjson",
            "source_uri",
            "source_locator",
            "cache_uri",
            "storage_uri",
            "prompt_json",
            "artifact_json",
            "database_url",
            "output_path",
            "local_path",
            "raw_source_url",
            "raw_generated",
            "token_value",
            "access_token",
            "bearer_token",
            "resolved_secret",
            "providerrawresponse",
        ] {
            assert!(
                !contract.contains(forbidden),
                "Admin contract leaked forbidden term: {forbidden}"
            );
        }

        assert!(
            contract.contains("raw_token: string"),
            "Admin contract should expose raw_token only for one-time addon token issue/rotation responses"
        );
        assert_eq!(
            contract.matches("raw_token").count(),
            2,
            "raw_token must stay limited to explicit one-time token response DTOs"
        );
    }

    #[test]
    fn public_typescript_sdk_still_excludes_admin_routes() {
        let public_sdk = crate::sdk::typescript_sdk().to_ascii_lowercase();

        for forbidden in ["/admin", "/admin/v1", "nako_admin_routes"] {
            assert!(
                !public_sdk.contains(forbidden),
                "Public TypeScript SDK leaked admin term: {forbidden}"
            );
        }
    }

    #[test]
    fn admin_contract_routes_stay_out_of_public_client_inventory() {
        let public_paths = public_client_paths().collect::<Vec<_>>();

        for (_key, suffix) in ADMIN_ROUTE_SUFFIXES {
            let admin_path = admin_route_path(suffix);
            assert!(
                !public_paths.contains(&admin_path.as_str()),
                "Public Client route inventory leaked Admin API path: {admin_path}"
            );
        }
    }

    #[test]
    fn admin_web_generated_contract_matches_generator_output() {
        let generated = admin_typescript_contract().replace("\r\n", "\n");
        let app_local = include_str!("../../../apps/admin-web/src/adminApi/generated/contract.ts")
            .replace("\r\n", "\n");

        assert_eq!(
            app_local, generated,
            "run `cargo run -p nako-api --example emit-admin-typescript-contract -- --output apps/admin-web/src/adminApi/generated/contract.ts` to refresh the Admin API TypeScript contract"
        );
    }
}
