use std::collections::{BTreeMap, BTreeSet};

use nako_client_protocol::public_client_paths;
use serde_json::Value;

use crate::{
    openapi::public_openapi_v1,
    public_client::{API_VERSION, API_VERSION_HEADER, PLAYBACK_SESSION_ID_HEADER},
};

#[must_use]
pub fn typescript_sdk() -> String {
    let document = public_openapi_v1();
    let schemas = document["components"]["schemas"]
        .as_object()
        .expect("OpenAPI schemas are an object");
    let mut schema_names = schemas.keys().cloned().collect::<Vec<_>>();
    schema_names.sort();

    let mut output = String::new();
    output.push_str("// Generated by `cargo run -p nako-api --example emit-typescript-sdk`.\n");
    output.push_str("// Do not edit generated output by hand.\n\n");
    output.push_str(&format!(
        "export const NAKO_API_VERSION = \"{}\" as const;\n",
        API_VERSION
    ));
    output.push_str(&format!(
        "export const NAKO_API_VERSION_HEADER = \"{}\" as const;\n\n",
        API_VERSION_HEADER
    ));
    output.push_str(&format!(
        "export const NAKO_PLAYBACK_SESSION_ID_HEADER = \"{}\" as const;\n\n",
        PLAYBACK_SESSION_ID_HEADER
    ));
    output.push_str("export const NAKO_PUBLIC_PATHS = [\n");
    for path in public_client_paths() {
        output.push_str(&format!("  \"{}\",\n", path));
    }
    output.push_str("] as const;\n\n");

    for name in schema_names {
        let schema = &schemas[&name];
        output.push_str(&schema_definition(&name, schema));
        output.push('\n');
    }

    output.push_str(CLIENT_RUNTIME);
    output
}

#[must_use]
pub fn kotlin_sdk() -> String {
    let document = public_openapi_v1();
    let schemas = document["components"]["schemas"]
        .as_object()
        .expect("OpenAPI schemas are an object");
    let mut schema_names = schemas.keys().cloned().collect::<Vec<_>>();
    schema_names.sort();

    let mut generated_property_enums = BTreeMap::new();
    let mut schema_definitions = Vec::new();
    for name in schema_names {
        let schema = &schemas[&name];
        schema_definitions.push(kotlin_schema_definition(
            &name,
            schema,
            &mut generated_property_enums,
        ));
    }

    let mut output = String::new();
    output.push_str("// Generated by `cargo run -p nako-api --example emit-kotlin-sdk`.\n");
    output.push_str("// Do not edit generated output by hand.\n\n");
    output.push_str("@file:Suppress(\"unused\")\n\n");
    output.push_str("package dev.nako.sdk\n\n");
    output.push_str("import java.net.URLEncoder\n");
    output.push_str("import java.nio.charset.StandardCharsets\n");
    output.push_str("import kotlinx.serialization.SerialName\n");
    output.push_str("import kotlinx.serialization.Serializable\n");
    output.push_str("import kotlinx.serialization.json.JsonElement\n\n");
    output.push_str(&format!(
        "public const val NAKO_API_VERSION: String = {:?}\n",
        API_VERSION
    ));
    output.push_str(&format!(
        "public const val NAKO_API_VERSION_HEADER: String = {:?}\n",
        API_VERSION_HEADER
    ));
    output.push_str(&format!(
        "public const val NAKO_PLAYBACK_SESSION_ID_HEADER: String = {:?}\n\n",
        PLAYBACK_SESSION_ID_HEADER
    ));
    output.push_str("public val NAKO_PUBLIC_PATHS: List<String> = listOf(\n");
    for path in public_client_paths() {
        output.push_str(&format!("    {path:?},\n"));
    }
    output.push_str(")\n\n");
    output.push_str(KOTLIN_CLIENT_RUNTIME);
    output.push('\n');

    for (name, values) in generated_property_enums {
        output.push_str(&kotlin_enum_definition(&name, &values));
        output.push('\n');
    }

    for definition in schema_definitions {
        output.push_str(&definition);
        output.push('\n');
    }

    while output.ends_with("\n\n") {
        output.pop();
    }

    output
}

fn kotlin_schema_definition(
    name: &str,
    schema: &Value,
    generated_property_enums: &mut BTreeMap<String, Vec<String>>,
) -> String {
    if schema.get("type").and_then(Value::as_str) == Some("object") {
        return kotlin_data_class_definition(name, schema, generated_property_enums);
    }

    if let Some(values) = openapi_enum_values(schema) {
        return kotlin_enum_definition(name, &values);
    }

    let schema_type = kotlin_schema_type(schema, None, generated_property_enums);
    format!("public typealias {name} = {}\n", schema_type.name)
}

fn kotlin_data_class_definition(
    name: &str,
    schema: &Value,
    generated_property_enums: &mut BTreeMap<String, Vec<String>>,
) -> String {
    let required = schema["required"]
        .as_array()
        .map(|values| {
            values
                .iter()
                .filter_map(Value::as_str)
                .collect::<BTreeSet<_>>()
        })
        .unwrap_or_default();

    let properties = schema["properties"]
        .as_object()
        .expect("object schema has properties");
    let mut property_names = properties.keys().cloned().collect::<Vec<_>>();
    property_names.sort();

    let mut output = String::new();
    output.push_str("@Serializable\n");
    output.push_str(&format!("public data class {name}(\n"));

    for property in property_names {
        let property_schema = &properties[&property];
        let is_required = required.contains(property.as_str());
        let property_name = kotlin_property_name(&property);
        let mut property_type = kotlin_schema_type(
            property_schema,
            Some(KotlinPropertyContext {
                parent: name,
                property: &property,
            }),
            generated_property_enums,
        );
        let default_value = if is_required {
            String::new()
        } else {
            kotlin_optional_default(&mut property_type)
        };
        if property_name != property {
            output.push_str(&format!("    @SerialName({property:?})\n"));
        }
        output.push_str(&format!(
            "    public val {property_name}: {}{default_value},\n",
            property_type.name
        ));
    }

    output.push_str(")\n");
    output
}

#[derive(Clone, Copy)]
struct KotlinPropertyContext<'a> {
    parent: &'a str,
    property: &'a str,
}

#[derive(Clone, Copy, Eq, PartialEq)]
enum KotlinDefaultKind {
    Null,
    EmptyList,
    EmptyMap,
}

struct KotlinType {
    name: String,
    default_kind: KotlinDefaultKind,
}

fn kotlin_schema_type(
    schema: &Value,
    context: Option<KotlinPropertyContext<'_>>,
    generated_property_enums: &mut BTreeMap<String, Vec<String>>,
) -> KotlinType {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return KotlinType {
            name: nullable_type(kotlin_ref_name(reference), schema),
            default_kind: KotlinDefaultKind::Null,
        };
    }

    if let Some(all_of) = schema.get("allOf").and_then(Value::as_array)
        && let Some(first) = all_of.first()
    {
        let mut schema_type = kotlin_schema_type(first, context, generated_property_enums);
        if schema.get("nullable").and_then(Value::as_bool) == Some(true) {
            schema_type.name = make_nullable(schema_type.name);
            schema_type.default_kind = KotlinDefaultKind::Null;
        }
        return schema_type;
    }

    if let Some(values) = openapi_enum_values(schema) {
        let name = context
            .map(|context| kotlin_property_enum_name(context.parent, context.property))
            .unwrap_or_else(|| "String".to_owned());
        if name != "String" {
            generated_property_enums
                .entry(name.clone())
                .or_insert_with(|| values.clone());
        }
        return KotlinType {
            name: nullable_type(name, schema),
            default_kind: KotlinDefaultKind::Null,
        };
    }

    let nullable = schema.get("nullable").and_then(Value::as_bool) == Some(true);
    let schema_type = match schema.get("type").and_then(Value::as_str) {
        Some("array") => {
            let item_type =
                kotlin_schema_type(&schema["items"], None, generated_property_enums).name;
            KotlinType {
                name: if nullable {
                    format!("List<{item_type}>?")
                } else {
                    format!("List<{item_type}>")
                },
                default_kind: if nullable {
                    KotlinDefaultKind::Null
                } else {
                    KotlinDefaultKind::EmptyList
                },
            }
        }
        Some("boolean") => KotlinType {
            name: nullable_type("Boolean".to_owned(), schema),
            default_kind: KotlinDefaultKind::Null,
        },
        Some("integer") => {
            let name = if schema.get("format").and_then(Value::as_str) == Some("int64") {
                "Long"
            } else {
                "Int"
            };
            KotlinType {
                name: nullable_type(name.to_owned(), schema),
                default_kind: KotlinDefaultKind::Null,
            }
        }
        Some("number") => {
            let name = if schema.get("format").and_then(Value::as_str) == Some("float") {
                "Float"
            } else {
                "Double"
            };
            KotlinType {
                name: nullable_type(name.to_owned(), schema),
                default_kind: KotlinDefaultKind::Null,
            }
        }
        Some("object") => kotlin_object_type(schema, nullable, generated_property_enums),
        Some("string") => KotlinType {
            name: nullable_type("String".to_owned(), schema),
            default_kind: KotlinDefaultKind::Null,
        },
        _ => KotlinType {
            name: if nullable {
                "JsonElement?".to_owned()
            } else {
                "JsonElement".to_owned()
            },
            default_kind: KotlinDefaultKind::Null,
        },
    };

    schema_type
}

fn kotlin_object_type(
    schema: &Value,
    nullable: bool,
    generated_property_enums: &mut BTreeMap<String, Vec<String>>,
) -> KotlinType {
    if let Some(additional_properties) = schema.get("additionalProperties") {
        let value_type = if additional_properties == &Value::Bool(true) {
            "JsonElement".to_owned()
        } else {
            kotlin_schema_type(additional_properties, None, generated_property_enums).name
        };
        return KotlinType {
            name: if nullable {
                format!("Map<String, {value_type}>?")
            } else {
                format!("Map<String, {value_type}>")
            },
            default_kind: if nullable {
                KotlinDefaultKind::Null
            } else {
                KotlinDefaultKind::EmptyMap
            },
        };
    }

    KotlinType {
        name: if nullable {
            "JsonElement?".to_owned()
        } else {
            "JsonElement".to_owned()
        },
        default_kind: KotlinDefaultKind::Null,
    }
}

fn kotlin_optional_default(schema_type: &mut KotlinType) -> String {
    if schema_type.name.ends_with('?') {
        return " = null".to_owned();
    }

    match schema_type.default_kind {
        KotlinDefaultKind::EmptyList => " = emptyList()".to_owned(),
        KotlinDefaultKind::EmptyMap => " = emptyMap()".to_owned(),
        KotlinDefaultKind::Null => {
            schema_type.name = make_nullable(std::mem::take(&mut schema_type.name));
            " = null".to_owned()
        }
    }
}

fn nullable_type(name: String, schema: &Value) -> String {
    if schema.get("nullable").and_then(Value::as_bool) == Some(true) {
        make_nullable(name)
    } else {
        name
    }
}

fn make_nullable(name: String) -> String {
    if name.ends_with('?') {
        name
    } else {
        format!("{name}?")
    }
}

fn kotlin_ref_name(reference: &str) -> String {
    reference
        .rsplit('/')
        .next()
        .expect("schema ref has a name")
        .to_owned()
}

fn openapi_enum_values(schema: &Value) -> Option<Vec<String>> {
    schema
        .get("enum")
        .and_then(Value::as_array)
        .map(|values| {
            values
                .iter()
                .filter_map(Value::as_str)
                .map(ToOwned::to_owned)
                .collect::<Vec<_>>()
        })
        .filter(|values| !values.is_empty())
}

fn kotlin_enum_definition(name: &str, values: &[String]) -> String {
    let mut output = String::new();
    output.push_str("@JvmInline\n");
    output.push_str("@Serializable\n");
    output.push_str(&format!(
        "public value class {name}(\n    public val wireValue: String,\n) {{\n"
    ));
    let mut used_names = BTreeSet::new();
    let mut constants = Vec::new();

    for (index, value) in values.iter().enumerate() {
        let mut constant_name = kotlin_enum_variant_name(value);
        if !used_names.insert(constant_name.clone()) {
            constant_name = format!("{constant_name}{index}");
        }
        constants.push((constant_name, value));
    }

    output.push_str("    public val isKnown: Boolean\n");
    output.push_str("        get() = wireValue in KnownWireValues\n\n");
    output.push_str("    public companion object {\n");
    for (constant_name, value) in &constants {
        output.push_str(&format!(
            "        public val {constant_name}: {name} = {name}({value:?})\n"
        ));
    }
    output.push('\n');
    output.push_str("        public val KnownWireValues: Set<String> = setOf(\n");
    for (_, value) in &constants {
        output.push_str(&format!("            {value:?},\n"));
    }
    output.push_str("        )\n");
    output.push_str("    }\n");
    output.push_str("}\n");
    output
}

fn kotlin_property_name(name: &str) -> String {
    let mut identifier = lower_camel_identifier(name);
    if !is_kotlin_identifier(&identifier) || is_kotlin_reserved(&identifier) {
        identifier = format!("`{identifier}`");
    }
    identifier
}

fn kotlin_property_enum_name(parent: &str, property: &str) -> String {
    format!("{parent}{}", pascal_identifier(property))
}

fn kotlin_enum_variant_name(value: &str) -> String {
    let name = pascal_identifier(value);
    if is_kotlin_reserved(&name) {
        format!("{name}_")
    } else {
        name
    }
}

fn lower_camel_identifier(value: &str) -> String {
    let parts = identifier_parts(value);
    let Some((first, rest)) = parts.split_first() else {
        return "_".to_owned();
    };

    let mut output = first.to_ascii_lowercase();
    for part in rest {
        output.push_str(&pascal_word(part));
    }
    output
}

fn pascal_identifier(value: &str) -> String {
    let mut output = String::new();
    for part in identifier_parts(value) {
        output.push_str(&pascal_word(&part));
    }
    if output.is_empty() {
        output.push_str("Value");
    }
    if output.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        output.insert_str(0, "Value");
    }
    output
}

fn pascal_word(value: &str) -> String {
    let mut chars = value.chars();
    let Some(first) = chars.next() else {
        return String::new();
    };
    let mut output = first.to_ascii_uppercase().to_string();
    output.push_str(&chars.as_str().to_ascii_lowercase());
    output
}

fn identifier_parts(value: &str) -> Vec<String> {
    value
        .split(|ch: char| !ch.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(ToOwned::to_owned)
        .collect()
}

fn is_kotlin_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    chars
        .next()
        .is_some_and(|ch| ch == '_' || ch.is_ascii_alphabetic())
        && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

fn is_kotlin_reserved(value: &str) -> bool {
    matches!(
        value,
        "as" | "break"
            | "class"
            | "continue"
            | "do"
            | "else"
            | "false"
            | "for"
            | "fun"
            | "if"
            | "in"
            | "interface"
            | "is"
            | "null"
            | "object"
            | "package"
            | "return"
            | "super"
            | "this"
            | "throw"
            | "true"
            | "try"
            | "typealias"
            | "typeof"
            | "val"
            | "var"
            | "when"
            | "while"
    )
}

const KOTLIN_CLIENT_RUNTIME: &str = r#"public data class NakoRequestDescriptor(
    public val method: String,
    public val pathAndQuery: String,
    public val authRequired: Boolean = true,
)

public data class PageQuery(
    public val limit: Int? = null,
    public val offset: Long? = null,
)

public data class ImageVariantQuery(
    public val width: Int? = null,
    public val height: Int? = null,
)

public data class ManagementContextQuery(
    public val libraryId: String? = null,
    public val itemId: String? = null,
    public val sourceId: String? = null,
    public val playbackSessionId: String? = null,
)

public data class PlaybackCapabilitiesQuery(
    public val directPlay: Boolean? = null,
    public val containers: List<String> = emptyList(),
    public val videoCodecs: List<String> = emptyList(),
    public val audioCodecs: List<String> = emptyList(),
)

@JvmInline
@Serializable
public value class RemuxOutputContainer(
    public val wireValue: String,
) {
    public val isKnown: Boolean
        get() = wireValue in KnownWireValues

    public companion object {
        public val Mp4: RemuxOutputContainer = RemuxOutputContainer("mp4")
        public val Mkv: RemuxOutputContainer = RemuxOutputContainer("mkv")

        public val KnownWireValues: Set<String> = setOf(
            "mp4",
            "mkv",
        )
    }
}

public data class RemuxPlaybackQuery(
    public val directPlay: Boolean? = null,
    public val containers: List<String> = emptyList(),
    public val videoCodecs: List<String> = emptyList(),
    public val audioCodecs: List<String> = emptyList(),
    public val outputContainer: RemuxOutputContainer? = null,
)

public object NakoPublicClientRequests {
    public fun health(): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = "/health",
            authRequired = false,
        )

    public fun listLibraries(page: PageQuery = PageQuery()): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery("/libraries", pageQuery(page)),
        )

    public fun getLibrary(libraryId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = "/libraries/${encodePathSegment(libraryId)}",
        )

    public fun listLibrarySources(
        libraryId: String,
        page: PageQuery = PageQuery(),
    ): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/libraries/${encodePathSegment(libraryId)}/sources",
                pageQuery(page),
            ),
        )

    public fun listItems(page: PageQuery = PageQuery()): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery("/items", pageQuery(page)),
        )

    public fun getItem(itemId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = "/items/${encodePathSegment(itemId)}",
        )

    public fun listItemImages(itemId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = "/items/${encodePathSegment(itemId)}/images",
        )

    public fun image(
        imageId: String,
        variant: ImageVariantQuery = ImageVariantQuery(),
    ): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/images/${encodePathSegment(imageId)}",
                imageVariantQuery(variant),
            ),
        )

    public fun headImage(
        imageId: String,
        variant: ImageVariantQuery = ImageVariantQuery(),
    ): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "HEAD",
            pathAndQuery = pathWithQuery(
                "/images/${encodePathSegment(imageId)}",
                imageVariantQuery(variant),
            ),
        )

    public fun getPerson(personId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = "/people/${encodePathSegment(personId)}",
        )

    public fun listPersonItems(
        personId: String,
        page: PageQuery = PageQuery(),
    ): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/people/${encodePathSegment(personId)}/items",
                pageQuery(page),
            ),
        )

    public fun listGenres(page: PageQuery = PageQuery()): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery("/genres", pageQuery(page)),
        )

    public fun listGenreItems(
        genreId: String,
        page: PageQuery = PageQuery(),
    ): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/genres/${encodePathSegment(genreId)}/items",
                pageQuery(page),
            ),
        )

    public fun listTags(page: PageQuery = PageQuery()): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery("/tags", pageQuery(page)),
        )

    public fun listTagItems(
        tagId: String,
        page: PageQuery = PageQuery(),
    ): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/tags/${encodePathSegment(tagId)}/items",
                pageQuery(page),
            ),
        )

    public fun searchItems(
        query: String? = null,
        facets: List<String> = emptyList(),
        page: PageQuery = PageQuery(),
    ): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/search",
                buildList {
                    if (!query.isNullOrBlank()) {
                        add("q" to query)
                    }
                    if (facets.isNotEmpty()) {
                        add("facet" to facets.joinToString(","))
                    }
                    addAll(pageQuery(page))
                },
            ),
        )

    public fun managementContextLinks(
        query: ManagementContextQuery = ManagementContextQuery(),
    ): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/management/context-links",
                managementContextQuery(query),
            ),
        )

    public fun getSourceProbe(sourceId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = "/sources/${encodePathSegment(sourceId)}/probe",
        )

    public fun getSourcePlaybackDecision(
        sourceId: String,
        capabilities: PlaybackCapabilitiesQuery = PlaybackCapabilitiesQuery(),
    ): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/sources/${encodePathSegment(sourceId)}/playback/decision",
                playbackCapabilitiesQuery(capabilities),
            ),
        )

    public fun createBrowserPlaybackTicket(sourceId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "POST",
            pathAndQuery = "/sources/${encodePathSegment(sourceId)}/playback/browser-ticket",
        )

    public fun streamSource(sourceId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = "/sources/${encodePathSegment(sourceId)}/stream",
        )

    public fun headStreamSource(sourceId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "HEAD",
            pathAndQuery = "/sources/${encodePathSegment(sourceId)}/stream",
        )

    public fun remuxStreamSource(
        sourceId: String,
        query: RemuxPlaybackQuery = RemuxPlaybackQuery(),
    ): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/sources/${encodePathSegment(sourceId)}/stream/remux",
                remuxPlaybackQuery(query),
            ),
        )

    public fun headRemuxStreamSource(
        sourceId: String,
        query: RemuxPlaybackQuery = RemuxPlaybackQuery(),
    ): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "HEAD",
            pathAndQuery = pathWithQuery(
                "/sources/${encodePathSegment(sourceId)}/stream/remux",
                remuxPlaybackQuery(query),
            ),
        )

    public fun hlsPlaylistSource(
        sourceId: String,
        capabilities: PlaybackCapabilitiesQuery = PlaybackCapabilitiesQuery(),
    ): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/sources/${encodePathSegment(sourceId)}/stream/hls/playlist.m3u8",
                playbackCapabilitiesQuery(capabilities),
            ),
        )

    public fun getSourceSubtitle(sourceId: String, streamIndex: Int): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = "/sources/${encodePathSegment(sourceId)}/subtitles/${encodePathSegment(streamIndex.toString())}",
        )

    public fun getPlaybackSession(sessionId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = "/playback/sessions/${encodePathSegment(sessionId)}",
        )

    public fun cancelPlaybackSession(sessionId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "POST",
            pathAndQuery = "/playback/sessions/${encodePathSegment(sessionId)}/cancel",
        )

    public fun heartbeatPlaybackSession(sessionId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "POST",
            pathAndQuery = "/playback/sessions/${encodePathSegment(sessionId)}/heartbeat",
        )

    public fun hlsSegment(
        sessionId: String,
        segmentName: String,
    ): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = "/playback/sessions/${encodePathSegment(sessionId)}/hls/segments/${
                encodePathSegment(segmentName)
            }",
        )

    public fun listRenderers(page: PageQuery = PageQuery()): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery("/renderers", pageQuery(page)),
        )

    public fun registerRenderer(): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "POST",
            pathAndQuery = "/renderers",
        )

    public fun heartbeatRenderer(rendererSessionId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "POST",
            pathAndQuery = "/renderers/${encodePathSegment(rendererSessionId)}/heartbeat",
        )

    public fun pollNextRendererCommand(rendererSessionId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "POST",
            pathAndQuery = "/renderers/${encodePathSegment(rendererSessionId)}/commands/next",
        )

    public fun playOnRenderer(rendererSessionId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "POST",
            pathAndQuery = "/renderers/${encodePathSegment(rendererSessionId)}/commands/play",
        )

    public fun completeRendererCommand(
        rendererSessionId: String,
        commandId: String,
    ): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "POST",
            pathAndQuery = "/renderers/${encodePathSegment(rendererSessionId)}/commands/${
                encodePathSegment(commandId)
            }/complete",
        )

    public fun getUserPlaybackState(itemId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = "/users/me/playback-state/items/${encodePathSegment(itemId)}",
        )

    public fun listContinueWatching(page: PageQuery = PageQuery()): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery("/users/me/playback-state/continue-watching", pageQuery(page)),
        )

    public fun updateUserPlaybackProgress(itemId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "PUT",
            pathAndQuery = "/users/me/playback-state/items/${encodePathSegment(itemId)}/progress",
        )

    public fun setUserWatchedState(itemId: String): NakoRequestDescriptor =
        NakoRequestDescriptor(
            method = "PUT",
            pathAndQuery = "/users/me/playback-state/items/${encodePathSegment(itemId)}/watched",
        )

    public fun pathWithQuery(
        path: String,
        query: Iterable<Pair<String, String>>,
    ): String {
        val rendered = queryString(query)
        return if (rendered.isEmpty()) path else "$path?$rendered"
    }

    public fun queryString(query: Iterable<Pair<String, String>>): String =
        query.joinToString("&") { (name, value) ->
            "${encodeQueryValue(name)}=${encodeQueryValue(value)}"
        }

    public fun encodePathSegment(value: String): String =
        URLEncoder
            .encode(value, StandardCharsets.UTF_8)
            .replace("+", "%20")

    private fun pageQuery(page: PageQuery): List<Pair<String, String>> =
        buildList {
            page.limit?.let { add("limit" to it.toString()) }
            page.offset?.let { add("offset" to it.toString()) }
        }

    private fun imageVariantQuery(variant: ImageVariantQuery): List<Pair<String, String>> =
        buildList {
            variant.width?.let { add("width" to it.toString()) }
            variant.height?.let { add("height" to it.toString()) }
        }

    private fun managementContextQuery(query: ManagementContextQuery): List<Pair<String, String>> =
        buildList {
            query.libraryId?.let { add("library_id" to it) }
            query.itemId?.let { add("item_id" to it) }
            query.sourceId?.let { add("source_id" to it) }
            query.playbackSessionId?.let { add("playback_session_id" to it) }
        }

    private fun playbackCapabilitiesQuery(
        capabilities: PlaybackCapabilitiesQuery,
    ): List<Pair<String, String>> =
        buildList {
            capabilities.directPlay?.let {
                add("direct_play" to it.toString())
            }
            addCsv("container", capabilities.containers)
            addCsv("video_codec", capabilities.videoCodecs)
            addCsv("audio_codec", capabilities.audioCodecs)
        }

    private fun remuxPlaybackQuery(
        query: RemuxPlaybackQuery,
    ): List<Pair<String, String>> =
        buildList {
            query.directPlay?.let {
                add("direct_play" to it.toString())
            }
            addCsv("container", query.containers)
            addCsv("video_codec", query.videoCodecs)
            addCsv("audio_codec", query.audioCodecs)
            query.outputContainer?.let {
                add("output_container" to it.wireValue)
            }
        }

    private fun MutableList<Pair<String, String>>.addCsv(
        name: String,
        values: List<String>,
    ) {
        val cleaned = values.map(String::trim).filter(String::isNotEmpty)
        if (cleaned.isNotEmpty()) {
            add(name to cleaned.joinToString(","))
        }
    }

    private fun encodeQueryValue(value: String): String =
        URLEncoder.encode(value, StandardCharsets.UTF_8)
}

"#;

fn schema_definition(name: &str, schema: &Value) -> String {
    if schema.get("type").and_then(Value::as_str) == Some("object") {
        return interface_definition(name, schema);
    }

    format!("export type {name} = {};\n", schema_to_ts(schema))
}

fn interface_definition(name: &str, schema: &Value) -> String {
    let mut output = String::new();
    output.push_str(&format!("export interface {name} {{\n"));

    let required = schema["required"]
        .as_array()
        .map(|values| values.iter().filter_map(Value::as_str).collect::<Vec<_>>())
        .unwrap_or_default();

    let properties = schema["properties"]
        .as_object()
        .expect("object schema has properties");
    let mut property_names = properties.keys().cloned().collect::<Vec<_>>();
    property_names.sort();

    for property in property_names {
        let optional = if required.contains(&property.as_str()) {
            ""
        } else {
            "?"
        };
        output.push_str(&format!(
            "  {}{}: {};\n",
            ts_property_name(&property),
            optional,
            schema_to_ts(&properties[&property])
        ));
    }

    output.push_str("}\n");
    output
}

fn schema_to_ts(schema: &Value) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return reference
            .rsplit('/')
            .next()
            .expect("schema ref has a name")
            .to_owned();
    }

    if let Some(all_of) = schema.get("allOf").and_then(Value::as_array) {
        let mut values = all_of.iter().map(schema_to_ts).collect::<Vec<_>>();
        if schema.get("nullable").and_then(Value::as_bool) == Some(true) {
            values.push("null".to_owned());
        }
        return values.join(" | ");
    }

    let nullable = schema.get("nullable").and_then(Value::as_bool) == Some(true);
    let mut value = if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        values
            .iter()
            .filter_map(Value::as_str)
            .map(|value| format!("\"{value}\""))
            .collect::<Vec<_>>()
            .join(" | ")
    } else {
        match schema.get("type").and_then(Value::as_str) {
            Some("array") => format!("Array<{}>", schema_to_ts(&schema["items"])),
            Some("boolean") => "boolean".to_owned(),
            Some("integer" | "number") => "number".to_owned(),
            Some("object") => "Record<string, unknown>".to_owned(),
            Some("string") => "string".to_owned(),
            _ => "unknown".to_owned(),
        }
    };

    if value.is_empty() {
        value = "string".to_owned();
    }
    if nullable {
        value.push_str(" | null");
    }

    value
}

fn ts_property_name(name: &str) -> String {
    if name
        .chars()
        .all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
        && name
            .chars()
            .next()
            .is_some_and(|ch| ch == '_' || ch.is_ascii_alphabetic())
    {
        name.to_owned()
    } else {
        format!("{name:?}")
    }
}

const CLIENT_RUNTIME: &str = r#"export interface PageQuery {
  limit?: number;
  offset?: number;
}

export interface PlaybackCapabilitiesQuery {
  direct_play?: boolean;
  container?: string | string[];
  video_codec?: string | string[];
  audio_codec?: string | string[];
  max_video_bitrate?: number;
  max_width?: number;
  max_height?: number;
  max_audio_channels?: number;
  supports_hdr?: boolean;
  supports_subtitles?: boolean;
  hls_variant_policy?: "single_variant" | "adaptive";
  hls_segment_container?: "mpeg_ts" | "fmp4";
}

export interface RemuxPlaybackQuery extends PlaybackCapabilitiesQuery {
  output_container?: "mp4" | "mkv";
}

export interface ImageVariantQuery {
  width?: number;
  height?: number;
}

export interface ManagementContextQuery {
  library_id?: string;
  item_id?: string;
  source_id?: string;
  playback_session_id?: string;
}

export interface NakoClientOptions {
  baseUrl: string;
  bearerToken?: string;
  fetch?: FetchLike;
}

export type FetchLike = (input: string, init?: RequestInit) => Promise<Response>;

export class NakoApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly body: ErrorResponse;

  constructor(status: number, body: ErrorResponse) {
    super(body.message);
    this.name = "NakoApiError";
    this.status = status;
    this.code = body.code;
    this.body = body;
  }
}

export class NakoClient {
  private readonly baseUrl: string;
  private readonly bearerToken: string | undefined;
  private readonly fetchImpl: FetchLike;

  constructor(options: NakoClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/+$/, "");
    this.bearerToken = options.bearerToken;
    this.fetchImpl = options.fetch ?? globalThis.fetch.bind(globalThis);
  }

  health(): Promise<HealthResponse> {
    return this.requestJson("GET", "/health", { auth: false });
  }

  login(body: LoginRequest): Promise<LoginResponse> {
    return this.requestJson("POST", "/auth/login", { auth: false, body });
  }

  redeemInvitation(body: RedeemInvitationRequest): Promise<LoginResponse> {
    return this.requestJson("POST", "/auth/invitations/redeem", { auth: false, body });
  }

  logout(): Promise<LogoutResponse> {
    return this.requestJson("POST", "/auth/logout");
  }

  currentUser(): Promise<CurrentUserResponse> {
    return this.requestJson("GET", "/users/me");
  }

  listLibraries(page?: PageQuery): Promise<LibraryListResponse> {
    return this.requestJson("GET", "/libraries", { query: page });
  }

  getLibrary(libraryId: string): Promise<LibraryResponse> {
    return this.requestJson("GET", `/libraries/${encodeURIComponent(libraryId)}`);
  }

  listLibrarySources(libraryId: string, page?: PageQuery): Promise<LibrarySourcesResponse> {
    return this.requestJson("GET", `/libraries/${encodeURIComponent(libraryId)}/sources`, { query: page });
  }

  listItems(page?: PageQuery): Promise<ItemsResponse> {
    return this.requestJson("GET", "/items", { query: page });
  }

  getItem(itemId: string): Promise<ItemDetailResponse> {
    return this.requestJson("GET", `/items/${encodeURIComponent(itemId)}`);
  }

  listItemCredits(itemId: string): Promise<ItemCreditsResponse> {
    return this.requestJson("GET", `/items/${encodeURIComponent(itemId)}/credits`);
  }

  listItemImages(itemId: string): Promise<ImagesResponse> {
    return this.requestJson("GET", `/items/${encodeURIComponent(itemId)}/images`);
  }

  image(imageId: string, variant?: ImageVariantQuery): Promise<Response> {
    return this.requestRaw("GET", `/images/${encodeURIComponent(imageId)}`, { query: variant });
  }

  headImage(imageId: string, variant?: ImageVariantQuery): Promise<Response> {
    return this.requestRaw("HEAD", `/images/${encodeURIComponent(imageId)}`, { query: variant });
  }

  listPeople(page?: PageQuery): Promise<PeopleResponse> {
    return this.requestJson("GET", "/people", { query: page });
  }

  getPerson(personId: string): Promise<PersonResponse> {
    return this.requestJson("GET", `/people/${encodeURIComponent(personId)}`);
  }

  listPersonItems(personId: string, page?: PageQuery): Promise<PersonItemsResponse> {
    return this.requestJson("GET", `/people/${encodeURIComponent(personId)}/items`, { query: page });
  }

  listTags(page?: PageQuery): Promise<TagsResponse> {
    return this.requestJson("GET", "/tags", { query: page });
  }

  listTagItems(tagId: string, page?: PageQuery): Promise<TagItemsResponse> {
    return this.requestJson("GET", `/tags/${encodeURIComponent(tagId)}/items`, { query: page });
  }

  listGenres(page?: PageQuery): Promise<GenreListResponse> {
    return this.requestJson("GET", "/genres", { query: page });
  }

  listGenreItems(genreId: string, page?: PageQuery): Promise<GenreItemsResponse> {
    return this.requestJson("GET", `/genres/${encodeURIComponent(genreId)}/items`, { query: page });
  }

  searchItems(params: { q?: string; facet?: string | string[] } & PageQuery): Promise<SearchResponse> {
    return this.requestJson("GET", "/search", { query: params });
  }

  managementContextLinks(query?: ManagementContextQuery): Promise<ManagementContextLinksResponse> {
    return this.requestJson("GET", "/management/context-links", { query });
  }

  getSourceProbe(sourceId: string): Promise<SourceProbeResponse> {
    return this.requestJson("GET", `/sources/${encodeURIComponent(sourceId)}/probe`);
  }

  getPlaybackDecision(sourceId: string, capabilities?: PlaybackCapabilitiesQuery): Promise<PlaybackDecisionResponse> {
    return this.requestJson("GET", `/sources/${encodeURIComponent(sourceId)}/playback/decision`, { query: capabilities });
  }

  createBrowserPlaybackTicket(sourceId: string, body: BrowserPlaybackTicketRequest): Promise<BrowserPlaybackTicketResponse> {
    return this.requestJson("POST", `/sources/${encodeURIComponent(sourceId)}/playback/browser-ticket`, { body });
  }

  streamSource(sourceId: string, range?: string): Promise<Response> {
    return this.requestRaw("GET", `/sources/${encodeURIComponent(sourceId)}/stream`, { range });
  }

  headStreamSource(sourceId: string, range?: string): Promise<Response> {
    return this.requestRaw("HEAD", `/sources/${encodeURIComponent(sourceId)}/stream`, { range });
  }

  remuxStreamSource(sourceId: string, query?: RemuxPlaybackQuery, range?: string): Promise<Response> {
    return this.requestRaw("GET", `/sources/${encodeURIComponent(sourceId)}/stream/remux`, { query, range });
  }

  headRemuxStreamSource(sourceId: string, query?: RemuxPlaybackQuery): Promise<Response> {
    return this.requestRaw("HEAD", `/sources/${encodeURIComponent(sourceId)}/stream/remux`, { query });
  }

  hlsPlaylist(sourceId: string, capabilities?: PlaybackCapabilitiesQuery): Promise<string> {
    return this.requestText("GET", `/sources/${encodeURIComponent(sourceId)}/stream/hls/playlist.m3u8`, { query: capabilities });
  }

  getSourceSubtitle(sourceId: string, streamIndex: number): Promise<string> {
    return this.requestText("GET", `/sources/${encodeURIComponent(sourceId)}/subtitles/${encodeURIComponent(String(streamIndex))}`);
  }

  getPlaybackSession(sessionId: string): Promise<PlaybackSessionResponse> {
    return this.requestJson("GET", `/playback/sessions/${encodeURIComponent(sessionId)}`);
  }

  cancelPlaybackSession(sessionId: string): Promise<PlaybackSessionResponse> {
    return this.requestJson("POST", `/playback/sessions/${encodeURIComponent(sessionId)}/cancel`);
  }

  heartbeatPlaybackSession(sessionId: string, body: PlaybackSessionHeartbeatRequest): Promise<PlaybackSessionResponse> {
    return this.requestJson("POST", `/playback/sessions/${encodeURIComponent(sessionId)}/heartbeat`, { body });
  }

  hlsSegment(sessionId: string, segmentName: string): Promise<Response> {
    return this.requestRaw("GET", `/playback/sessions/${encodeURIComponent(sessionId)}/hls/segments/${encodeURIComponent(segmentName)}`);
  }

  listRenderers(page?: PageQuery): Promise<RendererSessionsResponse> {
    return this.requestJson("GET", "/renderers", { query: page });
  }

  registerRenderer(body: RendererRegistrationRequest): Promise<RendererSessionResponse> {
    return this.requestJson("POST", "/renderers", { body });
  }

  heartbeatRenderer(rendererSessionId: string, body: RendererHeartbeatRequest): Promise<RendererSessionResponse> {
    return this.requestJson("POST", `/renderers/${encodeURIComponent(rendererSessionId)}/heartbeat`, { body });
  }

  pollNextRendererCommand(rendererSessionId: string): Promise<RendererCommandPollResponse> {
    return this.requestJson("POST", `/renderers/${encodeURIComponent(rendererSessionId)}/commands/next`);
  }

  playOnRenderer(rendererSessionId: string, body: RendererPlayCommandRequest): Promise<RendererPlayCommandResponse> {
    return this.requestJson("POST", `/renderers/${encodeURIComponent(rendererSessionId)}/commands/play`, { body });
  }

  completeRendererCommand(rendererSessionId: string, commandId: string, body: RendererCommandCompletionRequest): Promise<RendererCommandResponse> {
    return this.requestJson("POST", `/renderers/${encodeURIComponent(rendererSessionId)}/commands/${encodeURIComponent(commandId)}/complete`, { body });
  }

  getUserPlaybackState(itemId: string): Promise<UserPlaybackStateResponse> {
    return this.requestJson("GET", `/users/me/playback-state/items/${encodeURIComponent(itemId)}`);
  }

  listContinueWatching(page?: PageQuery): Promise<ContinueWatchingResponse> {
    return this.requestJson("GET", "/users/me/playback-state/continue-watching", { query: page });
  }

  updateUserPlaybackProgress(itemId: string, body: UpdatePlaybackProgressRequest): Promise<UserPlaybackStateResponse> {
    return this.requestJson("PUT", `/users/me/playback-state/items/${encodeURIComponent(itemId)}/progress`, { body });
  }

  setUserWatchedState(itemId: string, body: SetWatchedStateRequest): Promise<UserPlaybackStateResponse> {
    return this.requestJson("PUT", `/users/me/playback-state/items/${encodeURIComponent(itemId)}/watched`, { body });
  }

  private async requestJson<T>(method: string, path: string, options: RequestOptions = {}): Promise<T> {
    const response = await this.request(method, path, options);
    await this.ensureOk(response);
    this.checkApiVersion(response);
    return await response.json() as T;
  }

  private async requestText(method: string, path: string, options: RequestOptions = {}): Promise<string> {
    const response = await this.request(method, path, options);
    await this.ensureOk(response);
    this.checkApiVersion(response);
    return await response.text();
  }

  private async requestRaw(method: string, path: string, options: RequestOptions = {}): Promise<Response> {
    const response = await this.request(method, path, options);
    await this.ensureOk(response);
    this.checkApiVersion(response);
    return response;
  }

  private request(method: string, path: string, options: RequestOptions): Promise<Response> {
    const headers = new Headers(options.headers);
    if (options.auth !== false && this.bearerToken) {
      headers.set("Authorization", `Bearer ${this.bearerToken}`);
    }
    if (options.range) {
      headers.set("Range", options.range);
    }
    const init: RequestInit = {
      method,
      headers,
    };
    if (options.body !== undefined) {
      headers.set("Content-Type", "application/json");
      init.body = JSON.stringify(options.body);
    }
    return this.fetchImpl(this.url(path, options.query), init);
  }

  private url(path: string, query?: QueryInput): string {
    const url = new URL(`${this.baseUrl}${path}`);
    for (const [key, value] of Object.entries(query ?? {})) {
      if (value === undefined || value === null) {
        continue;
      }
      const rendered = Array.isArray(value) ? value.join(",") : String(value);
      url.searchParams.set(key, rendered);
    }
    return url.toString();
  }

  private async ensureOk(response: Response): Promise<void> {
    if (response.ok) {
      return;
    }

    let body: ErrorResponse | undefined;
    const text = await response.text();
    if (text.length > 0) {
      try {
        body = JSON.parse(text) as ErrorResponse;
      } catch {
        body = undefined;
      }
    }

    throw new NakoApiError(response.status, body ?? {
      code: "invalid_input",
      message: response.statusText || `HTTP ${response.status}`,
    });
  }

  private checkApiVersion(response: Response): void {
    const version = response.headers.get(NAKO_API_VERSION_HEADER);
    if (version !== null && version !== NAKO_API_VERSION) {
      throw new NakoApiError(response.status, {
        code: "unsupported",
        message: `unsupported Nako API version: ${version}`,
      });
    }
  }
}

interface RequestOptions {
  auth?: boolean | undefined;
  body?: unknown | undefined;
  headers?: HeadersInit | undefined;
  query?: QueryInput | undefined;
  range?: string | undefined;
}

type QueryInput = object;
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn typescript_sdk_includes_public_route_methods_and_paths() {
        let sdk = typescript_sdk();

        for path in public_client_paths() {
            assert!(sdk.contains(path), "SDK missing public path {path}");
        }

        for method in [
            "health(",
            "listLibraries(",
            "getLibrary(",
            "searchItems(",
            "managementContextLinks(",
            "getPlaybackDecision(",
            "createBrowserPlaybackTicket(",
            "streamSource(",
            "headStreamSource(",
            "remuxStreamSource(",
            "headRemuxStreamSource(",
            "hlsPlaylist(",
            "getSourceSubtitle(",
            "getPlaybackSession(",
            "cancelPlaybackSession(",
            "heartbeatPlaybackSession(",
            "listRenderers(",
            "registerRenderer(",
            "heartbeatRenderer(",
            "pollNextRendererCommand(",
            "playOnRenderer(",
            "completeRendererCommand(",
            "getUserPlaybackState(",
            "listContinueWatching(",
            "updateUserPlaybackProgress(",
            "setUserWatchedState(",
        ] {
            assert!(sdk.contains(method), "SDK missing method {method}");
        }
    }

    #[test]
    fn typescript_sdk_includes_auth_version_error_and_pagination_runtime() {
        managed_artwork_variant_typescript_sdk_accepts_bounded_dimensions();
    }

    #[test]
    fn managed_artwork_variant_typescript_sdk_accepts_bounded_dimensions() {
        let sdk = typescript_sdk();

        for expected in [
            "Authorization",
            "Bearer ${this.bearerToken}",
            "NAKO_API_VERSION_HEADER",
            "NAKO_PLAYBACK_SESSION_ID_HEADER",
            "NakoApiError",
            "ErrorResponse",
            "BrowserPlaybackTicketRequest",
            "BrowserPlaybackTicketResponse",
            "BrowserPlaybackCapabilitiesDto",
            "BrowserPlaybackUrlDto",
            "ClientPlaybackCapabilitiesDto",
            "ClientPlaybackDecisionReason",
            "\"client_disabled_direct_play\"",
            "RendererSessionResponse",
            "RendererCommandPollResponse",
            "RendererPlayCommandResponse",
            "RendererCommandTransportDto",
            "RendererCommandTransportUrlDto",
            "RendererTransportMode",
            "RendererTransportUrlKind",
            "PlaybackSessionResponse",
            "PlaybackSessionHeartbeatRequest",
            "limit?: number",
            "offset?: number",
            "ImageVariantQuery",
            "image(imageId: string, variant?: ImageVariantQuery)",
            "headImage(imageId: string, variant?: ImageVariantQuery)",
            "response.headers.get",
            "Content-Type",
            "JSON.stringify",
        ] {
            assert!(
                sdk.contains(expected),
                "SDK missing runtime detail {expected}"
            );
        }
    }

    #[test]
    fn typescript_sdk_excludes_admin_internal_and_secret_surfaces() {
        let sdk = typescript_sdk().to_ascii_lowercase();

        for forbidden in [
            "/admin",
            "/admin/v1",
            "/addons",
            "/addon",
            "/addon/v1",
            "/webhooks",
            "/automation",
            "/storage/backends",
            "/jobs",
            "secret_env",
            "output_path",
            "providerrawresponse",
            "nako_core",
            "nako-server",
        ] {
            assert!(
                !sdk.contains(forbidden),
                "SDK leaked forbidden term: {forbidden}"
            );
        }
    }

    #[test]
    fn typescript_package_entry_matches_generator_output() {
        let generated = typescript_sdk().replace("\r\n", "\n");
        let package_entry =
            include_str!("../../../sdk/typescript/src/index.ts").replace("\r\n", "\n");

        assert_eq!(
            package_entry, generated,
            "run `npm run generate --prefix sdk/typescript` to refresh the TypeScript SDK package entry"
        );
    }

    #[test]
    fn kotlin_sdk_includes_public_constants_paths_and_wire_types() {
        let sdk = kotlin_sdk();

        for path in public_client_paths() {
            assert!(sdk.contains(path), "Kotlin SDK missing public path {path}");
        }

        for expected in [
            "public const val NAKO_API_VERSION: String = \"v1\"",
            "public const val NAKO_API_VERSION_HEADER: String = \"x-nako-api-version\"",
            "public const val NAKO_PLAYBACK_SESSION_ID_HEADER: String = \"x-nako-playback-session-id\"",
            "public data class HealthResponse",
            "public data class LibraryListResponse",
            "public data class ManagementContextLinksResponse",
            "public data class PlaybackDecisionResponse",
            "public data class UserPlaybackStateResponse",
            "public data class ErrorResponse",
            "public data class ClientPlaybackCapabilitiesDto",
            "public value class ClientPlaybackDecisionReason",
            "public val ClientDisabledDirectPlay: ClientPlaybackDecisionReason = ClientPlaybackDecisionReason(\"client_disabled_direct_play\")",
            "public data class NakoRequestDescriptor",
            "public object NakoPublicClientRequests",
            "public fun health(): NakoRequestDescriptor",
            "public fun listLibraries(page: PageQuery = PageQuery()): NakoRequestDescriptor",
            "public fun managementContextLinks(",
            "public fun createBrowserPlaybackTicket(sourceId: String): NakoRequestDescriptor",
            "public fun getSourceSubtitle(sourceId: String, streamIndex: Int): NakoRequestDescriptor",
            "public fun heartbeatPlaybackSession(sessionId: String): NakoRequestDescriptor",
            "public fun listRenderers(page: PageQuery = PageQuery()): NakoRequestDescriptor",
            "public fun pollNextRendererCommand(rendererSessionId: String): NakoRequestDescriptor",
            "public fun playOnRenderer(rendererSessionId: String): NakoRequestDescriptor",
            "public value class ClientMediaKind",
            "public val wireValue: String",
            "public val isKnown: Boolean",
            "public value class ClientPlaybackDecisionMode",
            "public val DirectPlay: ClientPlaybackDecisionMode = ClientPlaybackDecisionMode(\"direct_play\")",
            "public val owner: Map<String, String>",
        ] {
            assert!(
                sdk.contains(expected),
                "Kotlin SDK missing generated detail {expected}"
            );
        }
    }

    #[test]
    fn kotlin_sdk_excludes_admin_internal_secret_and_raw_locator_surfaces() {
        let sdk = kotlin_sdk().to_ascii_lowercase();

        for forbidden in [
            "/admin",
            "/admin/v1",
            "/addons",
            "/addon",
            "/addon/v1",
            "/webhooks",
            "/automation",
            "/storage/backends",
            "/jobs",
            "secret_env",
            "output_path",
            "providerrawresponse",
            "nako_core",
            "nako-server",
            "locator",
            "source_uri",
            "cache_uri",
            "storage_uri",
            "managed-artwork://",
        ] {
            assert!(
                !sdk.contains(forbidden),
                "Kotlin SDK leaked forbidden term: {forbidden}"
            );
        }
    }

    #[test]
    fn kotlin_sdk_package_entry_matches_generator_output() {
        let generated = kotlin_sdk().replace("\r\n", "\n");
        let package_entry =
            include_str!("../../../sdk/kotlin/src/main/kotlin/dev/nako/sdk/NakoClientSdk.kt")
                .replace("\r\n", "\n");

        assert_eq!(
            package_entry, generated,
            "run `cargo run -q -p nako-api --example emit-kotlin-sdk -- --output sdk/kotlin/src/main/kotlin/dev/nako/sdk/NakoClientSdk.kt` to refresh the Kotlin SDK package entry"
        );
    }
}
