[package]
name = "nako-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
nako-addon-protocol = { path = "../nako-addon-protocol" }
nako-client-protocol = { path = "../nako-client-protocol" }
nako-core = { path = "../nako-core" }
nako-streaming = { path = "../nako-streaming" }
nako-transcode = { path = "../nako-transcode" }
time.workspace = true
