[package]
name = "nako-client-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0 OR MIT"
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
nako-client = { path = "../nako-client" }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
async-trait.workspace = true
reqwest.workspace = true

