[package]
name = "taru-library"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
futures-util.workspace = true
serde.workspace = true
taru-core = { path = "../taru-core" }
taru-media-probe = { path = "../taru-media-probe" }
taru-naming = { path = "../taru-naming" }
taru-search = { path = "../taru-search" }
taru-vfs = { path = "../taru-vfs" }

[dev-dependencies]
axum.workspace = true
pollster.workspace = true
taru-db = { path = "../taru-db" }
tempfile.workspace = true
tokio.workspace = true
