use crate::admin::ADMIN_API_VERSION;

const ADMIN_READ_MODEL_ROUTE_SUFFIXES: [(&str, &str); 8] = [
    ("overview", "overview"),
    ("catalogGovernanceItems", "catalog/governance/items"),
    ("events", "events"),
    ("jobs", "jobs"),
    ("playbackSessions", "playback/sessions"),
    ("playbackRuntime", "playback/runtime"),
    ("storageStaging", "storage/staging"),
    ("systemConfig", "system/config"),
];

#[must_use]
pub fn admin_typescript_contract() -> String {
    let mut output = String::new();
    output.push_str(
        "// Generated by `cargo run -p taru-api --example emit-admin-typescript-contract`.\n",
    );
    output.push_str("// Do not edit generated output by hand.\n\n");
    output.push_str(&format!(
        "export const TARU_ADMIN_API_VERSION = \"{}\" as const;\n\n",
        ADMIN_API_VERSION
    ));
    output.push_str("export const TARU_ADMIN_ROUTES = {\n");
    for (key, suffix) in ADMIN_READ_MODEL_ROUTE_SUFFIXES {
        output.push_str(&format!("  {key}: \"{}\",\n", admin_route_path(suffix)));
    }
    output.push_str("} as const;\n\n");
    output.push_str(CONTRACT_BODY);
    output
}

fn admin_route_path(suffix: &str) -> String {
    format!("/admin/{ADMIN_API_VERSION}/{suffix}")
}

const CONTRACT_BODY: &str = r#"export type AdminApiRouteKey = keyof typeof TARU_ADMIN_ROUTES;

export interface AdminPageQuery {
  limit?: number;
  offset?: number;
}

export interface AdminCatalogGovernanceItemsQuery extends AdminPageQuery {
  library_id?: string;
  max_confidence_milli?: number;
}

export interface AdminOutboxEventsQuery extends AdminPageQuery {
  kind?: string;
  status?: string;
  library_id?: string;
  source_id?: string;
}

export interface AdminJobsQuery extends AdminPageQuery {
  status?: string;
  kind?: string;
  resource_class?: string;
  library_id?: string;
  source_id?: string;
}

export interface AdminPlaybackSessionsQuery extends AdminPageQuery {
  source_id?: string;
  kind?: string;
  state?: string;
}

export interface AdminStorageStagingQuery extends AdminPageQuery {
  purpose?: string;
  state?: string;
}

export interface PageInfo {
  limit: number;
  offset: number;
  returned: number;
}

export type AdminOverviewStatus = "healthy" | "degraded";

export interface AdminOverviewResponse {
  admin_api_version: string;
  public_api_version: string;
  status: AdminOverviewStatus;
  storage: {
    total_backends: number;
    ready_backends: number;
    degraded_backends: number;
    unavailable_backends: number;
    backends: Array<{
      library_id: string;
      library_name: string;
      backend_kind: string;
      status: string;
    }>;
  };
  metadata: {
    total_providers: number;
    available_providers: number;
    disabled_providers: number;
    unavailable_providers: number;
    providers: Array<{
      provider: string;
      status: string;
    }>;
  };
  runtime: {
    active_tasks: number;
    completed_tasks: number;
    failed_tasks: number;
    succeeded_jobs: number;
    cancelled_jobs: number;
    failed_jobs: number;
    shutdown_requested: boolean;
  };
  startup: {
    configured_libraries: number;
    recovered_transcode_sessions: number;
    recovered_jobs: number;
    staging_deleted_records: number;
    staging_deleted_files: number;
    metadata_raw_cache_deleted: number;
    metadata_lifecycle_tasks_started: number;
    artwork_ingest_worker_started: boolean;
  };
}

export interface AdminCatalogGovernanceItemListResponse {
  items: AdminCatalogGovernanceItem[];
  page: PageInfo;
}

export interface AdminCatalogGovernanceItem {
  item_id: string;
  library_id: string;
  kind: string;
  parent_id: string | null;
  title: string;
  release_date: string | null;
  source_count: number;
  representative_source_id: string | null;
  representative_file_name: string | null;
  local_inference: AdminLocalInferenceSummary | null;
  provider_mapping_count: number;
  accepted_provider_mapping_count: number;
  duplicate_relationship_count: number;
  issues: string[];
}

export interface AdminLocalInferenceSummary {
  source_id: string;
  inferred_kind: string;
  inferred_title: string | null;
  inferred_year: number | null;
  inferred_season: number | null;
  inferred_episode: number | null;
  confidence_milli: number | null;
  evidence_source: string;
  has_evidence: boolean;
  inference_version: string;
}

export interface AdminOutboxEventListResponse {
  events: AdminOutboxEventListItem[];
  page: PageInfo;
}

export interface AdminOutboxEventListItem {
  id: string;
  kind: string;
  subject: string | Record<string, unknown>;
  library_id: string | null;
  source_id: string | null;
  status: string;
  attempts: number;
  has_payload: boolean;
  has_error: boolean;
  occurred_at: string;
  updated_at: string;
  next_attempt_at: string | null;
}

export interface AdminJobListItem {
  id: string;
  kind: string;
  status: string;
  resource_class: string;
  library_id: string | null;
  source_id: string | null;
  has_input: boolean;
  has_summary: boolean;
  has_error: boolean;
  queued_at: string;
  started_at: string | null;
  completed_at: string | null;
}

export interface AdminJobListResponse {
  jobs: AdminJobListItem[];
  page: PageInfo;
}

export interface AdminPlaybackSessionListItem {
  id: string;
  source_id: string;
  kind: string;
  request_key: string;
  state: string;
  failure_category: string | null;
  has_failure_message: boolean;
  active: boolean;
  terminal: boolean;
  created_at: string;
  updated_at: string;
  started_at: string | null;
  completed_at: string | null;
}

export interface AdminPlaybackSessionListResponse {
  sessions: AdminPlaybackSessionListItem[];
  page: PageInfo;
}

export interface AdminPlaybackRuntimeDiagnosticsResponse {
  admin_api_version: string;
  public_api_version: string;
  ffmpeg: {
    probe_status: string;
    has_probe_error: boolean;
    hardware_capability_count: number;
    available_gpu_capabilities: number;
  };
  hardware: {
    policy: Record<string, unknown>;
    selection: {
      acceleration: string;
      fallback_used: boolean;
      reason: string;
    };
    capabilities: Array<{
      accelerator: string;
      available: boolean;
      reason_code: string;
      evidence: string;
      smoke_probe: {
        status: string;
        operator_check: string;
        has_detail: boolean;
      };
    }>;
  };
  transcode: {
    configured_cpu_slots: number;
    configured_gpu_slots: number;
    effective_cpu_slots: number;
    effective_gpu_slots: number;
    selected_hls_slots: number;
  };
  remux: {
    max_concurrent_sessions: number;
    timeout_ms: number;
  };
  remote_playback: {
    backend_count: number;
    stream_permits_available: number;
    stream_permits_max: number;
    stage_permits_available: number;
    stage_permits_max: number;
    state_scope: string;
  };
  staging: {
    max_bytes: number;
    retention_ms: number;
    cleanup_on_startup: boolean;
    startup_deleted_records: number;
    startup_deleted_files: number;
  };
}

export interface AdminStorageStagingDiagnosticsResponse {
  admin_api_version: string;
  public_api_version: string;
  summary: {
    configured_max_bytes: number;
    used_manifest_bytes: number;
    cleanup_on_startup: boolean;
    retention_ms: number;
    startup_deleted_records: number;
    startup_deleted_files: number;
    process_cached_backends: number;
    vfs_cache: {
      object_count: number;
      listing_count: number;
      failure_count: number;
      stale_object_count: number;
      stale_listing_count: number;
      last_failure_at_ms: number | null;
    };
  };
  records: Array<{
    id: string;
    source_scheme: string;
    purpose: string;
    state: string;
    size_bytes: number | null;
    has_etag: boolean;
    has_fingerprint: boolean;
    active_leases: number;
    has_validation_error: boolean;
    created_at_ms: number;
    updated_at_ms: number;
    last_accessed_at_ms: number;
    expires_at_ms: number | null;
  }>;
  page: PageInfo;
}

export interface AdminServerConfigDiagnosticsResponse {
  admin_api_version: string;
  public_api_version: string;
  auth: {
    enabled: boolean;
    token_env: string | null;
  };
  runtime: {
    listen_addr: string;
    scan_concurrency: number;
    probe_concurrency: number;
    metadata_concurrency: number;
    remux_concurrency: number;
    webhook_concurrency: number;
    remux_timeout_ms: number;
  };
  libraries: Array<{
    id: string;
    name: string;
    preset: string;
    backend_kind: string;
    root_scheme: string;
    has_webdav_password_env: boolean;
    webdav_timeout_ms: number | null;
    webdav_max_attempts: number | null;
  }>;
  metadata: {
    raw_cache_retention_ms: number;
    raw_cache_cleanup_on_startup: boolean;
    raw_cache_cleanup_interval_ms: number;
    maintenance_policies: number;
    providers: Array<{
      provider: string;
      enabled: boolean;
      token_env: string | null;
      api_key_env: string | null;
      has_api_base_url: boolean;
      has_image_base_url: boolean;
      language: string | null;
      include_adult: boolean;
      header_count: number;
      secret_header_count: number;
      has_provider_runtime_override: boolean;
    }>;
    runtime: {
      timeout_ms: number;
      max_attempts: number;
      min_interval_ms: number;
      concurrency: number;
      user_agent: string;
      has_proxy: boolean;
      circuit_breaker_failures: number;
      circuit_breaker_backoff_ms: number;
    };
  };
  transcode: {
    hardware_policy: Record<string, unknown>;
    cpu_concurrency: number;
    gpu_concurrency: number;
  };
  staging: {
    max_bytes: number;
    retention_ms: number;
    cleanup_on_startup: boolean;
  };
  playback: {
    remote_stream_concurrency: number;
    remote_stage_concurrency: number;
  };
  artwork: {
    artifact_root_configured: boolean;
    fetch_timeout_ms: number;
    fetch_max_attempts: number;
    fetch_max_bytes: number;
    fetch_concurrency: number;
    ingest_worker_enabled: boolean;
    ingest_worker_idle_ms: number;
    fetch_user_agent: string;
    has_fetch_proxy: boolean;
    max_width: number;
    max_height: number;
  };
}
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn admin_contract_includes_read_model_route_constants() {
        let contract = admin_typescript_contract();

        for (key, suffix) in ADMIN_READ_MODEL_ROUTE_SUFFIXES {
            let path = admin_route_path(suffix);
            assert!(
                contract.contains(&format!("{key}: \"{path}\"")),
                "Admin contract missing route constant {key} -> {path}"
            );
        }

        for expected in [
            "AdminCatalogGovernanceItemsQuery",
            "AdminOutboxEventsQuery",
            "AdminJobsQuery",
            "AdminPlaybackSessionsQuery",
            "AdminStorageStagingQuery",
            "AdminOverviewResponse",
            "AdminServerConfigDiagnosticsResponse",
        ] {
            assert!(
                contract.contains(expected),
                "Admin contract missing {expected}"
            );
        }
    }

    #[test]
    fn admin_contract_excludes_generated_fetch_runtime_and_raw_sensitive_fields() {
        let contract = admin_typescript_contract().to_ascii_lowercase();

        for forbidden in [
            "class adminapiclient",
            "fetchlike",
            "requestjson",
            "source_uri",
            "cache_uri",
            "storage_uri",
            "output_path",
            "local_path",
            "raw_source_url",
            "token_value",
            "access_token",
            "bearer_token",
            "resolved_secret",
            "providerrawresponse",
        ] {
            assert!(
                !contract.contains(forbidden),
                "Admin contract leaked forbidden term: {forbidden}"
            );
        }
    }

    #[test]
    fn public_typescript_sdk_still_excludes_admin_routes() {
        let public_sdk = crate::sdk::typescript_sdk().to_ascii_lowercase();

        for forbidden in ["/admin", "/admin/v1", "taru_admin_routes"] {
            assert!(
                !public_sdk.contains(forbidden),
                "Public TypeScript SDK leaked admin term: {forbidden}"
            );
        }
    }

    #[test]
    fn admin_web_generated_contract_matches_generator_output() {
        let generated = admin_typescript_contract().replace("\r\n", "\n");
        let app_local = include_str!("../../../apps/admin-web/src/adminApi/generated/contract.ts")
            .replace("\r\n", "\n");

        assert_eq!(
            app_local, generated,
            "run `cargo run -p taru-api --example emit-admin-typescript-contract -- --output apps/admin-web/src/adminApi/generated/contract.ts` to refresh the Admin API TypeScript contract"
        );
    }
}
