use serde_json::Value;
use taru_client_protocol::public_client_paths;

use crate::{
    API_VERSION, API_VERSION_HEADER, PLAYBACK_SESSION_ID_HEADER, openapi::public_openapi_v1,
};

#[must_use]
pub fn typescript_sdk() -> String {
    let document = public_openapi_v1();
    let schemas = document["components"]["schemas"]
        .as_object()
        .expect("OpenAPI schemas are an object");
    let mut schema_names = schemas.keys().cloned().collect::<Vec<_>>();
    schema_names.sort();

    let mut output = String::new();
    output.push_str("// Generated by `cargo run -p taru-api --example emit-typescript-sdk`.\n");
    output.push_str("// Do not edit generated output by hand.\n\n");
    output.push_str(&format!(
        "export const TARU_API_VERSION = \"{}\" as const;\n",
        API_VERSION
    ));
    output.push_str(&format!(
        "export const TARU_API_VERSION_HEADER = \"{}\" as const;\n\n",
        API_VERSION_HEADER
    ));
    output.push_str(&format!(
        "export const TARU_PLAYBACK_SESSION_ID_HEADER = \"{}\" as const;\n\n",
        PLAYBACK_SESSION_ID_HEADER
    ));
    output.push_str("export const TARU_PUBLIC_PATHS = [\n");
    for path in public_client_paths() {
        output.push_str(&format!("  \"{}\",\n", path));
    }
    output.push_str("] as const;\n\n");

    for name in schema_names {
        let schema = &schemas[&name];
        output.push_str(&schema_definition(&name, schema));
        output.push('\n');
    }

    output.push_str(CLIENT_RUNTIME);
    output
}

fn schema_definition(name: &str, schema: &Value) -> String {
    if schema.get("type").and_then(Value::as_str) == Some("object") {
        return interface_definition(name, schema);
    }

    format!("export type {name} = {};\n", schema_to_ts(schema))
}

fn interface_definition(name: &str, schema: &Value) -> String {
    let mut output = String::new();
    output.push_str(&format!("export interface {name} {{\n"));

    let required = schema["required"]
        .as_array()
        .map(|values| values.iter().filter_map(Value::as_str).collect::<Vec<_>>())
        .unwrap_or_default();

    let properties = schema["properties"]
        .as_object()
        .expect("object schema has properties");
    let mut property_names = properties.keys().cloned().collect::<Vec<_>>();
    property_names.sort();

    for property in property_names {
        let optional = if required.contains(&property.as_str()) {
            ""
        } else {
            "?"
        };
        output.push_str(&format!(
            "  {}{}: {};\n",
            ts_property_name(&property),
            optional,
            schema_to_ts(&properties[&property])
        ));
    }

    output.push_str("}\n");
    output
}

fn schema_to_ts(schema: &Value) -> String {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        return reference
            .rsplit('/')
            .next()
            .expect("schema ref has a name")
            .to_owned();
    }

    if let Some(all_of) = schema.get("allOf").and_then(Value::as_array) {
        let mut values = all_of.iter().map(schema_to_ts).collect::<Vec<_>>();
        if schema.get("nullable").and_then(Value::as_bool) == Some(true) {
            values.push("null".to_owned());
        }
        return values.join(" | ");
    }

    let nullable = schema.get("nullable").and_then(Value::as_bool) == Some(true);
    let mut value = if let Some(values) = schema.get("enum").and_then(Value::as_array) {
        values
            .iter()
            .filter_map(Value::as_str)
            .map(|value| format!("\"{value}\""))
            .collect::<Vec<_>>()
            .join(" | ")
    } else {
        match schema.get("type").and_then(Value::as_str) {
            Some("array") => format!("Array<{}>", schema_to_ts(&schema["items"])),
            Some("boolean") => "boolean".to_owned(),
            Some("integer" | "number") => "number".to_owned(),
            Some("object") => "Record<string, unknown>".to_owned(),
            Some("string") => "string".to_owned(),
            _ => "unknown".to_owned(),
        }
    };

    if value.is_empty() {
        value = "string".to_owned();
    }
    if nullable {
        value.push_str(" | null");
    }

    value
}

fn ts_property_name(name: &str) -> String {
    if name
        .chars()
        .all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
        && name
            .chars()
            .next()
            .is_some_and(|ch| ch == '_' || ch.is_ascii_alphabetic())
    {
        name.to_owned()
    } else {
        format!("{name:?}")
    }
}

const CLIENT_RUNTIME: &str = r#"export interface PageQuery {
  limit?: number;
  offset?: number;
}

export interface PlaybackCapabilitiesQuery {
  direct_play?: boolean;
  container?: string | string[];
  video_codec?: string | string[];
  audio_codec?: string | string[];
}

export interface RemuxPlaybackQuery extends PlaybackCapabilitiesQuery {
  output_container?: "mp4" | "mkv";
}

export interface TaruClientOptions {
  baseUrl: string;
  bearerToken?: string;
  fetch?: FetchLike;
}

export type FetchLike = (input: string, init?: RequestInit) => Promise<Response>;

export class TaruApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly body: ErrorResponse;

  constructor(status: number, body: ErrorResponse) {
    super(body.message);
    this.name = "TaruApiError";
    this.status = status;
    this.code = body.code;
    this.body = body;
  }
}

export class TaruClient {
  private readonly baseUrl: string;
  private readonly bearerToken: string | undefined;
  private readonly fetchImpl: FetchLike;

  constructor(options: TaruClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/+$/, "");
    this.bearerToken = options.bearerToken;
    this.fetchImpl = options.fetch ?? globalThis.fetch.bind(globalThis);
  }

  health(): Promise<HealthResponse> {
    return this.requestJson("GET", "/health", { auth: false });
  }

  listLibraries(page?: PageQuery): Promise<LibraryListResponse> {
    return this.requestJson("GET", "/libraries", { query: page });
  }

  getLibrary(libraryId: string): Promise<LibraryResponse> {
    return this.requestJson("GET", `/libraries/${encodeURIComponent(libraryId)}`);
  }

  listLibrarySources(libraryId: string, page?: PageQuery): Promise<LibrarySourcesResponse> {
    return this.requestJson("GET", `/libraries/${encodeURIComponent(libraryId)}/sources`, { query: page });
  }

  listItems(page?: PageQuery): Promise<ItemsResponse> {
    return this.requestJson("GET", "/items", { query: page });
  }

  getItem(itemId: string): Promise<ItemDetailResponse> {
    return this.requestJson("GET", `/items/${encodeURIComponent(itemId)}`);
  }

  listItemCredits(itemId: string): Promise<ItemCreditsResponse> {
    return this.requestJson("GET", `/items/${encodeURIComponent(itemId)}/credits`);
  }

  listItemImages(itemId: string): Promise<ImagesResponse> {
    return this.requestJson("GET", `/items/${encodeURIComponent(itemId)}/images`);
  }

  image(imageId: string): Promise<Response> {
    return this.requestRaw("GET", `/images/${encodeURIComponent(imageId)}`);
  }

  headImage(imageId: string): Promise<Response> {
    return this.requestRaw("HEAD", `/images/${encodeURIComponent(imageId)}`);
  }

  listPeople(page?: PageQuery): Promise<PeopleResponse> {
    return this.requestJson("GET", "/people", { query: page });
  }

  getPerson(personId: string): Promise<PersonResponse> {
    return this.requestJson("GET", `/people/${encodeURIComponent(personId)}`);
  }

  listPersonItems(personId: string, page?: PageQuery): Promise<PersonItemsResponse> {
    return this.requestJson("GET", `/people/${encodeURIComponent(personId)}/items`, { query: page });
  }

  listTags(page?: PageQuery): Promise<TagsResponse> {
    return this.requestJson("GET", "/tags", { query: page });
  }

  listTagItems(tagId: string, page?: PageQuery): Promise<TagItemsResponse> {
    return this.requestJson("GET", `/tags/${encodeURIComponent(tagId)}/items`, { query: page });
  }

  listGenres(page?: PageQuery): Promise<GenreListResponse> {
    return this.requestJson("GET", "/genres", { query: page });
  }

  listGenreItems(genreId: string, page?: PageQuery): Promise<GenreItemsResponse> {
    return this.requestJson("GET", `/genres/${encodeURIComponent(genreId)}/items`, { query: page });
  }

  searchItems(params: { q?: string; facet?: string | string[] } & PageQuery): Promise<SearchResponse> {
    return this.requestJson("GET", "/search", { query: params });
  }

  getSourceProbe(sourceId: string): Promise<SourceProbeResponse> {
    return this.requestJson("GET", `/sources/${encodeURIComponent(sourceId)}/probe`);
  }

  getPlaybackDecision(sourceId: string, capabilities?: PlaybackCapabilitiesQuery): Promise<PlaybackDecisionResponse> {
    return this.requestJson("GET", `/sources/${encodeURIComponent(sourceId)}/playback/decision`, { query: capabilities });
  }

  streamSource(sourceId: string, range?: string): Promise<Response> {
    return this.requestRaw("GET", `/sources/${encodeURIComponent(sourceId)}/stream`, { range });
  }

  headStreamSource(sourceId: string, range?: string): Promise<Response> {
    return this.requestRaw("HEAD", `/sources/${encodeURIComponent(sourceId)}/stream`, { range });
  }

  remuxStreamSource(sourceId: string, query?: RemuxPlaybackQuery, range?: string): Promise<Response> {
    return this.requestRaw("GET", `/sources/${encodeURIComponent(sourceId)}/stream/remux`, { query, range });
  }

  headRemuxStreamSource(sourceId: string, query?: RemuxPlaybackQuery): Promise<Response> {
    return this.requestRaw("HEAD", `/sources/${encodeURIComponent(sourceId)}/stream/remux`, { query });
  }

  hlsPlaylist(sourceId: string, capabilities?: PlaybackCapabilitiesQuery): Promise<string> {
    return this.requestText("GET", `/sources/${encodeURIComponent(sourceId)}/stream/hls/playlist.m3u8`, { query: capabilities });
  }

  getPlaybackSession(sessionId: string): Promise<TranscodeSessionResponse> {
    return this.requestJson("GET", `/playback/sessions/${encodeURIComponent(sessionId)}`);
  }

  cancelPlaybackSession(sessionId: string): Promise<TranscodeSessionResponse> {
    return this.requestJson("POST", `/playback/sessions/${encodeURIComponent(sessionId)}/cancel`);
  }

  hlsSegment(sessionId: string, segmentName: string): Promise<Response> {
    return this.requestRaw("GET", `/playback/sessions/${encodeURIComponent(sessionId)}/hls/segments/${encodeURIComponent(segmentName)}`);
  }

  getUserPlaybackState(itemId: string): Promise<UserPlaybackStateResponse> {
    return this.requestJson("GET", `/users/me/playback-state/items/${encodeURIComponent(itemId)}`);
  }

  listContinueWatching(page?: PageQuery): Promise<ContinueWatchingResponse> {
    return this.requestJson("GET", "/users/me/playback-state/continue-watching", { query: page });
  }

  updateUserPlaybackProgress(itemId: string, body: UpdatePlaybackProgressRequest): Promise<UserPlaybackStateResponse> {
    return this.requestJson("PUT", `/users/me/playback-state/items/${encodeURIComponent(itemId)}/progress`, { body });
  }

  setUserWatchedState(itemId: string, body: SetWatchedStateRequest): Promise<UserPlaybackStateResponse> {
    return this.requestJson("PUT", `/users/me/playback-state/items/${encodeURIComponent(itemId)}/watched`, { body });
  }

  private async requestJson<T>(method: string, path: string, options: RequestOptions = {}): Promise<T> {
    const response = await this.request(method, path, options);
    await this.ensureOk(response);
    this.checkApiVersion(response);
    return await response.json() as T;
  }

  private async requestText(method: string, path: string, options: RequestOptions = {}): Promise<string> {
    const response = await this.request(method, path, options);
    await this.ensureOk(response);
    this.checkApiVersion(response);
    return await response.text();
  }

  private async requestRaw(method: string, path: string, options: RequestOptions = {}): Promise<Response> {
    const response = await this.request(method, path, options);
    await this.ensureOk(response);
    this.checkApiVersion(response);
    return response;
  }

  private request(method: string, path: string, options: RequestOptions): Promise<Response> {
    const headers = new Headers(options.headers);
    if (options.auth !== false && this.bearerToken) {
      headers.set("Authorization", `Bearer ${this.bearerToken}`);
    }
    if (options.range) {
      headers.set("Range", options.range);
    }
    const init: RequestInit = {
      method,
      headers,
    };
    if (options.body !== undefined) {
      headers.set("Content-Type", "application/json");
      init.body = JSON.stringify(options.body);
    }
    return this.fetchImpl(this.url(path, options.query), init);
  }

  private url(path: string, query?: QueryInput): string {
    const url = new URL(`${this.baseUrl}${path}`);
    for (const [key, value] of Object.entries(query ?? {})) {
      if (value === undefined || value === null) {
        continue;
      }
      const rendered = Array.isArray(value) ? value.join(",") : String(value);
      url.searchParams.set(key, rendered);
    }
    return url.toString();
  }

  private async ensureOk(response: Response): Promise<void> {
    if (response.ok) {
      return;
    }

    let body: ErrorResponse | undefined;
    const text = await response.text();
    if (text.length > 0) {
      try {
        body = JSON.parse(text) as ErrorResponse;
      } catch {
        body = undefined;
      }
    }

    throw new TaruApiError(response.status, body ?? {
      code: "invalid_input",
      message: response.statusText || `HTTP ${response.status}`,
    });
  }

  private checkApiVersion(response: Response): void {
    const version = response.headers.get(TARU_API_VERSION_HEADER);
    if (version !== null && version !== TARU_API_VERSION) {
      throw new TaruApiError(response.status, {
        code: "unsupported",
        message: `unsupported Taru API version: ${version}`,
      });
    }
  }
}

interface RequestOptions {
  auth?: boolean | undefined;
  body?: unknown | undefined;
  headers?: HeadersInit | undefined;
  query?: QueryInput | undefined;
  range?: string | undefined;
}

type QueryInput = object;
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn typescript_sdk_includes_public_route_methods_and_paths() {
        let sdk = typescript_sdk();

        for path in public_client_paths() {
            assert!(sdk.contains(path), "SDK missing public path {path}");
        }

        for method in [
            "health(",
            "listLibraries(",
            "getLibrary(",
            "searchItems(",
            "getPlaybackDecision(",
            "streamSource(",
            "headStreamSource(",
            "remuxStreamSource(",
            "headRemuxStreamSource(",
            "hlsPlaylist(",
            "getPlaybackSession(",
            "cancelPlaybackSession(",
            "getUserPlaybackState(",
            "listContinueWatching(",
            "updateUserPlaybackProgress(",
            "setUserWatchedState(",
        ] {
            assert!(sdk.contains(method), "SDK missing method {method}");
        }
    }

    #[test]
    fn typescript_sdk_includes_auth_version_error_and_pagination_runtime() {
        let sdk = typescript_sdk();

        for expected in [
            "Authorization",
            "Bearer ${this.bearerToken}",
            "TARU_API_VERSION_HEADER",
            "TARU_PLAYBACK_SESSION_ID_HEADER",
            "TaruApiError",
            "ErrorResponse",
            "limit?: number",
            "offset?: number",
            "response.headers.get",
            "Content-Type",
            "JSON.stringify",
        ] {
            assert!(
                sdk.contains(expected),
                "SDK missing runtime detail {expected}"
            );
        }
    }

    #[test]
    fn typescript_sdk_excludes_admin_internal_and_secret_surfaces() {
        let sdk = typescript_sdk().to_ascii_lowercase();

        for forbidden in [
            "/admin",
            "/admin/v1",
            "/addons",
            "/addon",
            "/addon/v1",
            "/webhooks",
            "/automation",
            "/storage/backends",
            "/jobs",
            "secret_env",
            "output_path",
            "providerrawresponse",
            "taru_core",
            "taru-server",
        ] {
            assert!(
                !sdk.contains(forbidden),
                "SDK leaked forbidden term: {forbidden}"
            );
        }
    }

    #[test]
    fn typescript_package_entry_matches_generator_output() {
        let generated = typescript_sdk().replace("\r\n", "\n");
        let package_entry =
            include_str!("../../../sdk/typescript/src/index.ts").replace("\r\n", "\n");

        assert_eq!(
            package_entry, generated,
            "run `npm run generate --prefix sdk/typescript` to refresh the TypeScript SDK package entry"
        );
    }
}
