import type {
  AdminCatalogGovernanceItemListResponse,
  AdminJobListResponse,
  AdminOutboxEventListResponse,
  AdminOverviewResponse,
  AdminPlaybackRuntimeDiagnosticsResponse,
  AdminPlaybackSessionListResponse,
  AdminServerConfigDiagnosticsResponse,
  AdminStorageStagingDiagnosticsResponse,
} from "./generated/contract";
import type {
  AdminConsoleData,
  AdminSourceMap,
} from "./types";

export const mockOverview: AdminOverviewResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  status: "healthy",
  storage: {
    total_backends: 3,
    ready_backends: 2,
    degraded_backends: 1,
    unavailable_backends: 0,
    backends: [
      {
        library_id: "library-anime",
        library_name: "Anime Vault",
        backend_kind: "local",
        status: "ready",
      },
      {
        library_id: "library-films",
        library_name: "Films",
        backend_kind: "webdav",
        status: "ready",
      },
      {
        library_id: "library-archive",
        library_name: "Archive",
        backend_kind: "local",
        status: "degraded",
      },
    ],
  },
  metadata: {
    total_providers: 4,
    available_providers: 3,
    disabled_providers: 1,
    unavailable_providers: 0,
    providers: [
      { provider: "tmdb", status: "available" },
      { provider: "douban", status: "available" },
      { provider: "bangumi", status: "available" },
      { provider: "nfo", status: "disabled" },
    ],
  },
  runtime: {
    active_tasks: 4,
    completed_tasks: 186,
    failed_tasks: 2,
    succeeded_jobs: 72,
    cancelled_jobs: 1,
    failed_jobs: 3,
    shutdown_requested: false,
  },
  startup: {
    configured_libraries: 3,
    recovered_transcode_sessions: 0,
    recovered_jobs: 1,
    staging_deleted_records: 4,
    staging_deleted_files: 4,
    metadata_raw_cache_deleted: 18,
    metadata_lifecycle_tasks_started: 2,
    artwork_ingest_worker_started: true,
  },
};

export const mockCatalogGovernance: AdminCatalogGovernanceItemListResponse = {
  items: [
    {
      item_id: "item-unknown-1",
      library_id: "library-anime",
      kind: "unknown",
      parent_id: null,
      title: "Unmatched OVA Special",
      release_date: null,
      source_count: 2,
      representative_source_id: "source-unknown-1",
      representative_file_name: "Unmatched OVA Special.mkv",
      local_inference: {
        source_id: "source-unknown-1",
        inferred_kind: "movie",
        inferred_title: "Unmatched OVA Special",
        inferred_year: null,
        inferred_season: null,
        inferred_episode: null,
        confidence_milli: 420,
        evidence_source: "path",
        has_evidence: true,
        inference_version: "taru-naming:1",
      },
      provider_mapping_count: 0,
      accepted_provider_mapping_count: 0,
      duplicate_relationship_count: 1,
      issues: ["unknown_kind", "low_local_inference_confidence"],
    },
    {
      item_id: "item-low-confidence",
      library_id: "library-films",
      kind: "movie",
      parent_id: null,
      title: "Film Needs Mapping",
      release_date: "1999-01-01",
      source_count: 1,
      representative_source_id: "source-low-confidence",
      representative_file_name: "Film Needs Mapping.mkv",
      local_inference: null,
      provider_mapping_count: 1,
      accepted_provider_mapping_count: 0,
      duplicate_relationship_count: 0,
      issues: ["missing_accepted_provider_mapping"],
    },
  ],
  page: { limit: 20, offset: 0, returned: 2 },
};

export const mockEvents: AdminOutboxEventListResponse = {
  events: [
    {
      id: "event-metadata",
      kind: "item_metadata_refreshed",
      subject: "item:item-unknown-1",
      library_id: "library-anime",
      source_id: null,
      status: "pending",
      attempts: 0,
      has_payload: true,
      has_error: false,
      occurred_at: "2026-05-19T10:00:00Z",
      updated_at: "2026-05-19T10:00:00Z",
      next_attempt_at: null,
    },
    {
      id: "event-webhook",
      kind: "library_scanned",
      subject: "library:library-films",
      library_id: "library-films",
      source_id: null,
      status: "failed",
      attempts: 3,
      has_payload: true,
      has_error: true,
      occurred_at: "2026-05-19T09:30:00Z",
      updated_at: "2026-05-19T09:45:00Z",
      next_attempt_at: "2026-05-19T10:15:00Z",
    },
  ],
  page: { limit: 20, offset: 0, returned: 2 },
};

export const mockJobs: AdminJobListResponse = {
  jobs: [
    {
      id: "job-scan",
      kind: "library_scan",
      status: "running",
      resource_class: "library",
      library_id: "library-anime",
      source_id: null,
      has_input: true,
      has_summary: false,
      has_error: false,
      queued_at: "2026-05-19T09:58:00Z",
      started_at: "2026-05-19T10:00:00Z",
      completed_at: null,
    },
    {
      id: "job-artwork",
      kind: "managed_artwork_ingest",
      status: "queued",
      resource_class: "artwork",
      library_id: null,
      source_id: "source-unknown-1",
      has_input: true,
      has_summary: false,
      has_error: false,
      queued_at: "2026-05-19T10:02:00Z",
      started_at: null,
      completed_at: null,
    },
    {
      id: "job-metadata",
      kind: "metadata_refresh",
      status: "failed",
      resource_class: "metadata",
      library_id: "library-films",
      source_id: null,
      has_input: true,
      has_summary: true,
      has_error: true,
      queued_at: "2026-05-19T08:00:00Z",
      started_at: "2026-05-19T08:01:00Z",
      completed_at: "2026-05-19T08:04:00Z",
    },
  ],
  page: { limit: 20, offset: 0, returned: 3 },
};

export const mockPlaybackSessions: AdminPlaybackSessionListResponse = {
  sessions: [
    {
      id: "session-hls",
      source_id: "source-hls",
      kind: "hls_transcode",
      request_key: "profile:v1;kind=hls",
      state: "running",
      failure_category: null,
      has_failure_message: false,
      active: true,
      terminal: false,
      created_at: "2026-05-19T10:00:00Z",
      updated_at: "2026-05-19T10:03:00Z",
      started_at: "2026-05-19T10:00:01Z",
      completed_at: null,
    },
    {
      id: "session-remux",
      source_id: "source-remux",
      kind: "remux",
      request_key: "profile:v1;kind=remux",
      state: "starting",
      failure_category: null,
      has_failure_message: false,
      active: true,
      terminal: false,
      created_at: "2026-05-19T10:04:00Z",
      updated_at: "2026-05-19T10:04:00Z",
      started_at: null,
      completed_at: null,
    },
  ],
  page: { limit: 20, offset: 0, returned: 2 },
};

export const mockPlaybackRuntime: AdminPlaybackRuntimeDiagnosticsResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  readiness: {
    status: "ready",
    reason: "ffmpeg_probe_ready",
    checks: [
      { name: "ffmpeg_probe", status: "ready", reason: "ffmpeg_probe_ready" },
      {
        name: "hardware_acceleration",
        status: "ready",
        reason: "requested_accelerator_ready",
      },
      {
        name: "selected_fallback",
        status: "ready",
        reason: "selected_acceleration_ready",
      },
      {
        name: "transcode_budget",
        status: "ready",
        reason: "transcode_budget_ready",
      },
      {
        name: "remote_playback_budget",
        status: "ready",
        reason: "remote_playback_budget_ready",
      },
      { name: "staging", status: "ready", reason: "staging_ready" },
    ],
  },
  ffmpeg: {
    probe_status: "ready",
    has_probe_error: false,
    hardware_capability_count: 4,
    available_gpu_capabilities: 1,
  },
  hardware: {
    policy: { requested: "nvenc", fallback: "cpu" },
    selection: {
      acceleration: "nvenc",
      fallback_used: false,
      reason: "nvenc is available",
    },
    capabilities: [
      {
        accelerator: "vaapi",
        available: false,
        reason_code: "encoder_not_listed",
        encoder_discovery: {
          status: "missing",
          encoder: "h264_vaapi",
          has_detail: false,
        },
        device_initialization: {
          status: "not_run",
          operator_check: "Verify the host exposes a VAAPI render device to Taru",
          has_detail: false,
        },
        smoke_probe: {
          status: "not_run",
          operator_check: "Run a VAAPI encode smoke test on the host",
          has_detail: false,
        },
      },
      {
        accelerator: "nvenc",
        available: true,
        reason_code: "available",
        encoder_discovery: {
          status: "listed",
          encoder: "h264_nvenc",
          has_detail: false,
        },
        device_initialization: {
          status: "passed",
          operator_check: "NVIDIA driver and FFmpeg can initialize NVENC",
          has_detail: false,
        },
        smoke_probe: {
          status: "passed",
          operator_check: "NVENC encode smoke test passed",
          has_detail: true,
        },
      },
      {
        accelerator: "quick_sync",
        available: false,
        reason_code: "encoder_not_listed",
        encoder_discovery: {
          status: "missing",
          encoder: "h264_qsv",
          has_detail: false,
        },
        device_initialization: {
          status: "not_run",
          operator_check: "Verify Intel Quick Sync devices are exposed to Taru",
          has_detail: false,
        },
        smoke_probe: {
          status: "not_run",
          operator_check: "Run a QuickSync encode smoke test on the host",
          has_detail: false,
        },
      },
    ],
  },
  transcode: {
    configured_cpu_slots: 2,
    configured_gpu_slots: 1,
    effective_cpu_slots: 2,
    effective_gpu_slots: 1,
    selected_hls_slots: 1,
  },
  remux: {
    max_concurrent_sessions: 2,
    timeout_ms: 30000,
  },
  remote_playback: {
    backend_count: 2,
    stream_permits_available: 4,
    stream_permits_max: 4,
    stage_permits_available: 1,
    stage_permits_max: 2,
    state_scope: "process_local",
  },
  staging: {
    max_bytes: 10737418240,
    retention_ms: 86400000,
    cleanup_on_startup: true,
    startup_deleted_records: 4,
    startup_deleted_files: 4,
  },
};

export const mockStorageStaging: AdminStorageStagingDiagnosticsResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  summary: {
    configured_max_bytes: 10737418240,
    used_manifest_bytes: 2147483648,
    cleanup_on_startup: true,
    retention_ms: 86400000,
    startup_deleted_records: 4,
    startup_deleted_files: 4,
    process_cached_backends: 2,
    vfs_cache: {
      object_count: 48,
      listing_count: 7,
      failure_count: 1,
      stale_object_count: 3,
      stale_listing_count: 1,
      last_failure_at_ms: 1779180000000,
    },
  },
  records: [
    {
      id: "staging-hls",
      source_scheme: "webdav",
      purpose: "ffmpeg_input",
      state: "ready",
      size_bytes: 1468006400,
      has_etag: true,
      has_fingerprint: true,
      active_leases: 1,
      has_validation_error: false,
      created_at_ms: 1779180000000,
      updated_at_ms: 1779180200000,
      last_accessed_at_ms: 1779180300000,
      expires_at_ms: 1779266400000,
    },
    {
      id: "staging-old",
      source_scheme: "local",
      purpose: "ffmpeg_input",
      state: "failed",
      size_bytes: null,
      has_etag: false,
      has_fingerprint: false,
      active_leases: 0,
      has_validation_error: true,
      created_at_ms: 1779170000000,
      updated_at_ms: 1779170010000,
      last_accessed_at_ms: 1779170010000,
      expires_at_ms: null,
    },
  ],
  page: { limit: 20, offset: 0, returned: 2 },
};

export const mockSystemConfig: AdminServerConfigDiagnosticsResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  auth: {
    enabled: true,
    token_env: "TARU_ADMIN_TOKEN",
  },
  database: {
    configured_backend_kind: "sqlite",
    active_backend_kind: "sqlite",
    url_scheme: "sqlite",
    runtime_supported: true,
    migrated_on_startup: true,
    capabilities: {
      lifecycle: true,
      libraries: true,
      jobs: true,
      job_leases: true,
      media: true,
      scan_commits: true,
      metadata: true,
      catalog: true,
      playback_state: true,
      transcode_sessions: true,
      event_outbox: true,
      addons: true,
      automation: true,
      managed_artwork: true,
      vfs_cache: true,
      webhooks: true,
      search_index: true,
    },
  },
  runtime: {
    listen_addr: "127.0.0.1:3000",
    scan_concurrency: 2,
    probe_concurrency: 2,
    metadata_concurrency: 2,
    remux_concurrency: 1,
    webhook_concurrency: 2,
    remux_timeout_ms: 30000,
  },
  libraries: [
    {
      id: "library-anime",
      name: "Anime Vault",
      preset: "series",
      backend_kind: "local",
      root_scheme: "local",
      has_webdav_password_env: false,
      webdav_timeout_ms: null,
      webdav_max_attempts: null,
    },
    {
      id: "library-films",
      name: "Films",
      preset: "movies",
      backend_kind: "webdav",
      root_scheme: "webdav",
      has_webdav_password_env: true,
      webdav_timeout_ms: 15000,
      webdav_max_attempts: 3,
    },
  ],
  metadata: {
    raw_cache_retention_ms: 604800000,
    raw_cache_cleanup_on_startup: true,
    raw_cache_cleanup_interval_ms: 3600000,
    maintenance_policies: 2,
    providers: [
      {
        provider: "tmdb",
        enabled: true,
        token_env: null,
        api_key_env: "TMDB_API_KEY",
        has_api_base_url: true,
        has_image_base_url: true,
        language: "en-US",
        include_adult: false,
        header_count: 0,
        secret_header_count: 0,
        has_provider_runtime_override: false,
      },
    ],
    runtime: {
      timeout_ms: 10000,
      max_attempts: 3,
      min_interval_ms: 250,
      concurrency: 2,
      user_agent: "taru-admin-web-mock",
      has_proxy: false,
      circuit_breaker_failures: 5,
      circuit_breaker_backoff_ms: 30000,
    },
  },
  transcode: {
    hardware_policy: { requested: "nvenc", fallback: "cpu" },
    cpu_concurrency: 2,
    gpu_concurrency: 1,
  },
  staging: {
    max_bytes: 10737418240,
    retention_ms: 86400000,
    cleanup_on_startup: true,
  },
  playback: {
    remote_stream_concurrency: 4,
    remote_stage_concurrency: 2,
  },
  artwork: {
    artifact_root_configured: true,
    fetch_timeout_ms: 15000,
    fetch_max_attempts: 3,
    fetch_max_bytes: 10485760,
    fetch_concurrency: 2,
    ingest_worker_enabled: true,
    ingest_worker_idle_ms: 1000,
    fetch_user_agent: "taru-artwork-fetch",
    has_fetch_proxy: false,
    max_width: 4096,
    max_height: 4096,
  },
};

export const mockSources: AdminSourceMap = {
  overview: "mock",
  catalogGovernance: "mock",
  events: "mock",
  jobs: "mock",
  playbackSessions: "mock",
  playbackRuntime: "mock",
  storageStaging: "mock",
  systemConfig: "mock",
};

export const mockAdminConsoleData: AdminConsoleData = {
  sources: mockSources,
  errors: {},
  overview: mockOverview,
  libraries: [
    {
      id: "library-anime",
      name: "Anime Vault",
      backendKind: "local",
      status: "ready",
      itemCount: 1248,
      lastScan: "14 min ago",
    },
    {
      id: "library-films",
      name: "Films",
      backendKind: "webdav",
      status: "ready",
      itemCount: 382,
      lastScan: "2 hr ago",
    },
    {
      id: "library-archive",
      name: "Archive",
      backendKind: "local",
      status: "degraded",
      itemCount: 91,
      lastScan: "needs review",
    },
  ],
  catalog: {
    items: mockCatalogGovernance.items.map((item) => ({
      id: item.item_id,
      title: item.title,
      kind: item.kind,
      issues: item.issues,
      sourceCount: item.source_count,
      providerMappingCount: item.provider_mapping_count,
    })),
    page: mockCatalogGovernance.page,
  },
  events: {
    events: mockEvents.events.map((event) => ({
      id: event.id,
      kind: event.kind,
      status: event.status,
      attempts: event.attempts,
      hasError: event.has_error,
    })),
    page: mockEvents.page,
  },
  jobs: mockJobs.jobs.map((job) => ({
    id: job.id,
    kind: job.kind,
    status: job.status,
    resourceClass: job.resource_class,
    hasError: job.has_error,
  })),
  playback: {
    hardwarePolicy: "Prefer NVENC, fall back to CPU",
    ffmpegStatus: mockPlaybackRuntime.ffmpeg.probe_status,
    accelerators: mockPlaybackRuntime.hardware.capabilities.map((capability) => ({
      name: capability.accelerator,
      available: capability.available,
    })),
    sessions: mockPlaybackSessions.sessions.map((session) => ({
      id: session.id,
      kind: session.kind,
      sourceTitle: session.source_id,
      state: session.state,
    })),
  },
  storage: {
    stagingUsedBytes: mockStorageStaging.summary.used_manifest_bytes,
    stagingMaxBytes: mockStorageStaging.summary.configured_max_bytes,
    vfsObjectCount: mockStorageStaging.summary.vfs_cache.object_count,
    records: mockStorageStaging.records.map((record) => ({
      id: record.id,
      sourceScheme: record.source_scheme,
      purpose: record.purpose,
      state: record.state,
      sizeBytes: record.size_bytes,
      hasValidationError: record.has_validation_error,
    })),
  },
  settings: [
    {
      label: "Admin auth",
      value: mockSystemConfig.auth.enabled ? "Auth configured" : "Auth disabled",
    },
    { label: "FFmpeg", value: "Configured, diagnostics only" },
    {
      label: "Transcode policy",
      value: `${mockSystemConfig.transcode.gpu_concurrency} GPU slot`,
    },
    { label: "Settings edits", value: "Planned Admin API" },
  ],
};
