import type {
  AddonGrantsResponse,
  AddonTokensResponse,
  AdminAcquisitionIntakeCandidateListResponse,
  AdminAddonHealthCheckResponse,
  AdminAddonRegistrationResponse,
  AdminAddonRegistrationsResponse,
  AdminAddonResourceCallDiagnosticResponse,
  AdminAddonSurfacesResponse,
  AdminCatalogGovernanceItemListResponse,
  AdminJobListResponse,
  AdminOutboxEventListResponse,
  AdminOverviewResponse,
  AdminPlaybackRuntimeDiagnosticsResponse,
  AdminPlaybackSessionListResponse,
  AdminPlaybackSupportEvidenceResponse,
  AdminServerConfigDiagnosticsResponse,
  AdminStorageStagingDiagnosticsResponse,
  AdminWatchFolderDiscoveryResponse,
} from "./generated/contract";
import type {
  AdminConsoleData,
  AdminSourceMap,
} from "./types";

export const mockOverview: AdminOverviewResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  status: "healthy",
  storage: {
    total_backends: 3,
    ready_backends: 2,
    degraded_backends: 1,
    unavailable_backends: 0,
    backends: [
      {
        library_id: "library-anime",
        library_name: "Anime Vault",
        backend_kind: "local",
        status: "ready",
      },
      {
        library_id: "library-films",
        library_name: "Films",
        backend_kind: "webdav",
        status: "ready",
      },
      {
        library_id: "library-archive",
        library_name: "Archive",
        backend_kind: "local",
        status: "degraded",
      },
    ],
  },
  metadata: {
    total_providers: 4,
    available_providers: 3,
    disabled_providers: 1,
    unavailable_providers: 0,
    providers: [
      { provider: "tmdb", status: "available" },
      { provider: "douban", status: "available" },
      { provider: "bangumi", status: "available" },
      { provider: "nfo", status: "disabled" },
    ],
  },
  runtime: {
    active_tasks: 4,
    completed_tasks: 186,
    failed_tasks: 2,
    succeeded_jobs: 72,
    cancelled_jobs: 1,
    failed_jobs: 3,
    shutdown_requested: false,
  },
  startup: {
    configured_libraries: 3,
    recovered_transcode_sessions: 0,
    recovered_jobs: 1,
    staging_deleted_records: 4,
    staging_deleted_files: 4,
    metadata_raw_cache_deleted: 18,
    metadata_lifecycle_tasks_started: 2,
    artwork_ingest_worker_started: true,
  },
};

export const mockCatalogGovernance: AdminCatalogGovernanceItemListResponse = {
  items: [
    {
      item_id: "item-unknown-1",
      library_id: "library-anime",
      kind: "unknown",
      parent_id: null,
      title: "Unmatched OVA Special",
      release_date: null,
      source_count: 2,
      representative_source_id: "source-unknown-1",
      representative_file_name: "Unmatched OVA Special.mkv",
      local_inference: {
        source_id: "source-unknown-1",
        inferred_kind: "movie",
        inferred_title: "Unmatched OVA Special",
        inferred_year: null,
        inferred_season: null,
        inferred_episode: null,
        confidence_milli: 420,
        evidence_source: "path",
        has_evidence: true,
        inference_version: "taru-naming:1",
      },
      provider_mapping_count: 0,
      accepted_provider_mapping_count: 0,
      duplicate_relationship_count: 1,
      issues: ["unknown_kind", "low_local_inference_confidence"],
    },
    {
      item_id: "item-low-confidence",
      library_id: "library-films",
      kind: "movie",
      parent_id: null,
      title: "Film Needs Mapping",
      release_date: "1999-01-01",
      source_count: 1,
      representative_source_id: "source-low-confidence",
      representative_file_name: "Film Needs Mapping.mkv",
      local_inference: null,
      provider_mapping_count: 1,
      accepted_provider_mapping_count: 0,
      duplicate_relationship_count: 0,
      issues: ["missing_accepted_provider_mapping"],
    },
  ],
  page: { limit: 20, offset: 0, returned: 2 },
};

export const mockAcquisitionIntakeCandidates: AdminAcquisitionIntakeCandidateListResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  candidates: [
    {
      id: "candidate-ready",
      target_library_id: "library-anime",
      source_kind: "watch_folder",
      custom_source_kind: false,
      source_scheme: "local",
      source_ref_redacted: "local://<redacted>",
      source_key_fingerprint: "sha256:11111111111111111111111111111111",
      has_display_name: true,
      has_intended_locator: false,
      size_bytes: 1468006400,
      has_fingerprint: true,
      managed_import_artifact_id: null,
      state: "ready",
      has_diagnostics: true,
      first_seen_at_ms: 1779180000000,
      last_seen_at_ms: 1779180200000,
      created_at_ms: 1779180000000,
      updated_at_ms: 1779180200000,
    },
    {
      id: "candidate-blocked",
      target_library_id: "library-films",
      source_kind: "watch_folder",
      custom_source_kind: false,
      source_scheme: "local",
      source_ref_redacted: "local://<redacted>",
      source_key_fingerprint: "sha256:22222222222222222222222222222222",
      has_display_name: true,
      has_intended_locator: false,
      size_bytes: 1024,
      has_fingerprint: true,
      managed_import_artifact_id: null,
      state: "blocked",
      has_diagnostics: true,
      first_seen_at_ms: 1779180100000,
      last_seen_at_ms: 1779180300000,
      created_at_ms: 1779180100000,
      updated_at_ms: 1779180300000,
    },
  ],
  page: { limit: 20, offset: 0, returned: 2 },
};

export const mockWatchFolderDiscovery: AdminWatchFolderDiscoveryResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  target_library_id: "library-anime",
  root_scheme: "local",
  root_ref_redacted: "local://<redacted>",
  ready_candidates: 1,
  blocked_candidates: 1,
  incomplete_candidates: 1,
  unsupported_candidates: 0,
  recorded_candidates: 2,
  failures: [],
  writes_library: false,
  managed_import_artifacts_created: false,
  promotion_apply: false,
};

export const mockAddons: AdminAddonRegistrationsResponse = {
  addons: [
    {
      id: "addon-subtitle-lab",
      manifest_id: "dev.taru.subtitle-lab",
      name: "Subtitle Lab",
      version: "0.3.0",
      protocol_version: "2026-05-15",
      base_url: "http://subtitle-lab:9100",
      granted_scopes: ["subtitle_read", "item_metadata_read"],
      status: "enabled",
      created_at: "2026-05-22T02:10:00.000Z",
      updated_at: "2026-05-22T02:45:00.000Z",
    },
    {
      id: "addon-artwork-curator",
      manifest_id: "dev.taru.artwork-curator",
      name: "Artwork Curator",
      version: "0.2.1",
      protocol_version: "2026-05-15",
      base_url: "http://artwork-curator:9200",
      granted_scopes: ["image_read", "item_metadata_suggest"],
      status: "disabled",
      created_at: "2026-05-21T20:10:00.000Z",
      updated_at: "2026-05-22T01:00:00.000Z",
    },
  ],
};

export const mockAddonDetail: AdminAddonRegistrationResponse = {
  addon: {
    summary: mockAddons.addons[0],
    manifest: {
      id: "dev.taru.subtitle-lab",
      name: "Subtitle Lab",
      version: "0.3.0",
      protocol_version: "2026-05-15",
      base_url: "http://subtitle-lab:9100",
      description: "Suggests subtitle sidecars and metadata improvements.",
      resources: [
        {
          kind: "subtitle",
          path: "/resources/subtitles",
          input_schema: null,
          output_schema: null,
          required_scopes: ["subtitle_read"],
          timeout_ms: 5000,
          max_attempts: 2,
        },
        {
          kind: "metadata",
          path: "/resources/metadata",
          input_schema: null,
          output_schema: null,
          required_scopes: ["item_metadata_read"],
          timeout_ms: null,
          max_attempts: null,
        },
      ],
      auth: "bearer",
      default_timeout_ms: 5000,
      default_max_attempts: 2,
      scopes: ["subtitle_read", "item_metadata_read"],
    },
  },
};

export const mockAddonHealth: AdminAddonHealthCheckResponse = {
  addon_id: "addon-subtitle-lab",
  manifest_id: "dev.taru.subtitle-lab",
  status: "reachable",
  latency_ms: 42,
  protocol_version: "2026-05-15",
  addon_version: "0.3.0",
  resource_count: 2,
  protocol_checked_at: "2026-05-22T02:46:00.000Z",
};

export const mockAddonSurfaces: AdminAddonSurfacesResponse = {
  addon_id: "addon-subtitle-lab",
  manifest_id: "dev.taru.subtitle-lab",
  entry_points: [
    {
      id: "inspect-subtitles",
      kind: "item_action",
      label: "Inspect subtitles",
      path: "/entry/subtitles",
      hosted_page_id: "diagnostics",
      required_scopes: ["subtitle_read"],
    },
  ],
  hosted_pages: [
    {
      id: "diagnostics",
      title: "Subtitle diagnostics",
      path: "/pages/diagnostics",
      url: "http://subtitle-lab:9100/pages/diagnostics",
      required_scopes: ["subtitle_read"],
    },
  ],
  configuration_schema: {
    schema_id: "subtitle-lab-settings",
    schema: {
      type: "object",
      properties: {
        preferredLanguage: { type: "string" },
      },
    },
  },
  secret_reference_fields: [
    {
      id: "subtitle-provider-key",
      label: "Provider API key",
      description: "Secret Reference resolved by Taru at runtime.",
      required: false,
    },
  ],
  tasks: [
    {
      id: "scan-missing-subtitles",
      name: "Scan missing subtitles",
      path: "/tasks/missing-subtitles",
      description: "Find media items without subtitle sidecars.",
      required_scopes: ["subtitle_read"],
      timeout_ms: 30000,
      max_attempts: 1,
    },
  ],
  event_subscriptions: [
    {
      id: "scan-completed",
      event_kind: "scan.completed",
      path: "/events/scan-completed",
      required_scopes: ["item_metadata_read"],
      filters: {},
    },
  ],
};

export const mockAddonTokens: AddonTokensResponse = {
  tokens: [
    {
      id: "addon-token-active",
      addon_id: "addon-subtitle-lab",
      label: "sidecar runtime",
      token_prefix: "taru_at_subtitle",
      status: "active",
      created_at: "2026-05-22T02:10:00.000Z",
      rotated_at: null,
      revoked_at: null,
      last_used_at: "2026-05-22T02:44:00.000Z",
    },
  ],
};

export const mockAddonGrants: AddonGrantsResponse = {
  grants: [
    {
      id: "addon-grant-subtitle",
      addon_id: "addon-subtitle-lab",
      permission: "subtitle_write",
      library_id: "library-anime",
      created_at: "2026-05-22T02:10:00.000Z",
    },
  ],
};

export const mockAddonDiagnostic: AdminAddonResourceCallDiagnosticResponse = {
  addon_id: "addon-subtitle-lab",
  manifest_id: "dev.taru.subtitle-lab",
  resource: "subtitle",
  status: "succeeded",
  latency_ms: 85,
  attempts: 1,
  http_status: 200,
};

export const mockEvents: AdminOutboxEventListResponse = {
  events: [
    {
      id: "event-metadata",
      kind: "item_metadata_refreshed",
      subject: "item:item-unknown-1",
      library_id: "library-anime",
      source_id: null,
      status: "pending",
      attempts: 0,
      has_payload: true,
      has_error: false,
      occurred_at: "2026-05-19T10:00:00Z",
      updated_at: "2026-05-19T10:00:00Z",
      next_attempt_at: null,
    },
    {
      id: "event-webhook",
      kind: "library_scanned",
      subject: "library:library-films",
      library_id: "library-films",
      source_id: null,
      status: "failed",
      attempts: 3,
      has_payload: true,
      has_error: true,
      occurred_at: "2026-05-19T09:30:00Z",
      updated_at: "2026-05-19T09:45:00Z",
      next_attempt_at: "2026-05-19T10:15:00Z",
    },
  ],
  page: { limit: 20, offset: 0, returned: 2 },
};

export const mockJobs: AdminJobListResponse = {
  jobs: [
    {
      id: "job-scan",
      kind: "library_scan",
      status: "running",
      resource_class: "library",
      library_id: "library-anime",
      source_id: null,
      has_input: true,
      has_summary: false,
      has_error: false,
      queued_at: "2026-05-19T09:58:00Z",
      started_at: "2026-05-19T10:00:00Z",
      completed_at: null,
    },
    {
      id: "job-artwork",
      kind: "managed_artwork_ingest",
      status: "queued",
      resource_class: "artwork",
      library_id: null,
      source_id: "source-unknown-1",
      has_input: true,
      has_summary: false,
      has_error: false,
      queued_at: "2026-05-19T10:02:00Z",
      started_at: null,
      completed_at: null,
    },
    {
      id: "job-metadata",
      kind: "metadata_refresh",
      status: "failed",
      resource_class: "metadata",
      library_id: "library-films",
      source_id: null,
      has_input: true,
      has_summary: true,
      has_error: true,
      queued_at: "2026-05-19T08:00:00Z",
      started_at: "2026-05-19T08:01:00Z",
      completed_at: "2026-05-19T08:04:00Z",
    },
  ],
  page: { limit: 20, offset: 0, returned: 3 },
};

export const mockPlaybackSessions: AdminPlaybackSessionListResponse = {
  sessions: [
    {
      id: "session-hls",
      source_id: "source-hls",
      kind: "hls_transcode",
      request_key: "profile:v1;kind=hls",
      state: "running",
      failure_category: null,
      has_failure_message: false,
      active: true,
      terminal: false,
      created_at: "2026-05-19T10:00:00Z",
      updated_at: "2026-05-19T10:03:00Z",
      started_at: "2026-05-19T10:00:01Z",
      completed_at: null,
    },
    {
      id: "session-remux",
      source_id: "source-remux",
      kind: "remux",
      request_key: "profile:v1;kind=remux",
      state: "starting",
      failure_category: null,
      has_failure_message: false,
      active: true,
      terminal: false,
      created_at: "2026-05-19T10:04:00Z",
      updated_at: "2026-05-19T10:04:00Z",
      started_at: null,
      completed_at: null,
    },
  ],
  page: { limit: 20, offset: 0, returned: 2 },
};

export const mockPlaybackRuntime: AdminPlaybackRuntimeDiagnosticsResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  readiness: {
    status: "ready",
    reason: "ffmpeg_probe_ready",
    checks: [
      { name: "ffmpeg_probe", status: "ready", reason: "ffmpeg_probe_ready" },
      {
        name: "hardware_acceleration",
        status: "ready",
        reason: "requested_accelerator_ready",
      },
      {
        name: "selected_fallback",
        status: "ready",
        reason: "selected_acceleration_ready",
      },
      {
        name: "transcode_budget",
        status: "ready",
        reason: "transcode_budget_ready",
      },
      {
        name: "remote_playback_budget",
        status: "ready",
        reason: "remote_playback_budget_ready",
      },
      { name: "staging", status: "ready", reason: "staging_ready" },
    ],
  },
  ffmpeg: {
    probe_status: "ready",
    has_probe_error: false,
    hardware_capability_count: 4,
    available_gpu_capabilities: 1,
  },
  hardware: {
    policy: { requested: "nvenc", fallback: "cpu" },
    selection: {
      acceleration: "nvenc",
      fallback_used: false,
      reason: "nvenc is available",
    },
    capabilities: [
      {
        accelerator: "vaapi",
        available: false,
        reason_code: "encoder_not_listed",
        encoder_discovery: {
          status: "missing",
          encoder: "h264_vaapi",
          has_detail: false,
        },
        device_initialization: {
          status: "not_run",
          operator_check: "Verify the host exposes a VAAPI render device to Taru",
          has_detail: false,
        },
        smoke_probe: {
          status: "not_run",
          operator_check: "Run a VAAPI encode smoke test on the host",
          has_detail: false,
        },
      },
      {
        accelerator: "nvenc",
        available: true,
        reason_code: "available",
        encoder_discovery: {
          status: "listed",
          encoder: "h264_nvenc",
          has_detail: false,
        },
        device_initialization: {
          status: "passed",
          operator_check: "NVIDIA driver and FFmpeg can initialize NVENC",
          has_detail: false,
        },
        smoke_probe: {
          status: "passed",
          operator_check: "NVENC encode smoke test passed",
          has_detail: true,
        },
      },
      {
        accelerator: "quick_sync",
        available: false,
        reason_code: "encoder_not_listed",
        encoder_discovery: {
          status: "missing",
          encoder: "h264_qsv",
          has_detail: false,
        },
        device_initialization: {
          status: "not_run",
          operator_check: "Verify Intel Quick Sync devices are exposed to Taru",
          has_detail: false,
        },
        smoke_probe: {
          status: "not_run",
          operator_check: "Run a QuickSync encode smoke test on the host",
          has_detail: false,
        },
      },
    ],
  },
  transcode: {
    configured_cpu_slots: 2,
    configured_gpu_slots: 1,
    effective_cpu_slots: 2,
    effective_gpu_slots: 1,
    selected_hls_slots: 1,
  },
  remux: {
    max_concurrent_sessions: 2,
    timeout_ms: 30000,
  },
  remote_playback: {
    backend_count: 2,
    stream_permits_available: 4,
    stream_permits_max: 4,
    stage_permits_available: 1,
    stage_permits_max: 2,
    state_scope: "process_local",
  },
  staging: {
    max_bytes: 10737418240,
    retention_ms: 86400000,
    cleanup_on_startup: true,
    startup_deleted_records: 4,
    startup_deleted_files: 4,
  },
};

export const mockPlaybackSupport: AdminPlaybackSupportEvidenceResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  subject: {
    session_id: "session-hls",
    source_id: "source-hls",
  },
  session: {
    id: "session-hls",
    source_id: "source-hls",
    kind: "hls_transcode",
    state: "failed",
    failure_category: "runner",
    has_failure_message: true,
    active: false,
    terminal: true,
    request_key_fingerprint: "sha256:00000000000000000000000000000000",
    output_artifact_kind: "hls_playlist",
    created_at: "2026-05-19T10:00:00Z",
    updated_at: "2026-05-19T10:03:00Z",
    started_at: "2026-05-19T10:00:01Z",
    completed_at: "2026-05-19T10:03:00Z",
  },
  source: {
    source_id: "source-hls",
    library_id: "library-anime",
    item_id: "item-hls",
    source_scheme: "webdav",
    file_name: "Episode 01.mkv",
    size_bytes: 1468006400,
    has_fingerprint: true,
  },
  runtime: {
    readiness: mockPlaybackRuntime.readiness,
    ffmpeg: mockPlaybackRuntime.ffmpeg,
    hardware: {
      policy: mockPlaybackRuntime.hardware.policy,
      selected_acceleration: mockPlaybackRuntime.hardware.selection.acceleration,
      fallback_used: mockPlaybackRuntime.hardware.selection.fallback_used,
      capability_count: mockPlaybackRuntime.hardware.capabilities.length,
      unavailable_capabilities: mockPlaybackRuntime.hardware.capabilities
        .filter((capability) => !capability.available)
        .map((capability) => ({
          accelerator: capability.accelerator,
          reason_code: capability.reason_code,
          encoder_discovery_status: capability.encoder_discovery.status,
          device_initialization_status: capability.device_initialization.status,
          smoke_probe_status: capability.smoke_probe.status,
        })),
    },
    transcode: mockPlaybackRuntime.transcode,
    remux: mockPlaybackRuntime.remux,
    remote_playback: mockPlaybackRuntime.remote_playback,
    staging: mockPlaybackRuntime.staging,
  },
  redaction: {
    paths_redacted: true,
    source_references_redacted: true,
    ffmpeg_commands_redacted: true,
    stderr_redacted: true,
    credentials_redacted: true,
  },
};

export const mockStorageStaging: AdminStorageStagingDiagnosticsResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  summary: {
    configured_max_bytes: 10737418240,
    used_manifest_bytes: 2147483648,
    cleanup_on_startup: true,
    retention_ms: 86400000,
    startup_deleted_records: 4,
    startup_deleted_files: 4,
    process_cached_backends: 2,
    vfs_cache: {
      object_count: 48,
      listing_count: 7,
      failure_count: 1,
      stale_object_count: 3,
      stale_listing_count: 1,
      last_failure_at_ms: 1779180000000,
    },
  },
  records: [
    {
      id: "staging-hls",
      source_scheme: "webdav",
      purpose: "ffmpeg_input",
      state: "ready",
      size_bytes: 1468006400,
      has_etag: true,
      has_fingerprint: true,
      active_leases: 1,
      has_validation_error: false,
      created_at_ms: 1779180000000,
      updated_at_ms: 1779180200000,
      last_accessed_at_ms: 1779180300000,
      expires_at_ms: 1779266400000,
    },
    {
      id: "staging-old",
      source_scheme: "local",
      purpose: "ffmpeg_input",
      state: "failed",
      size_bytes: null,
      has_etag: false,
      has_fingerprint: false,
      active_leases: 0,
      has_validation_error: true,
      created_at_ms: 1779170000000,
      updated_at_ms: 1779170010000,
      last_accessed_at_ms: 1779170010000,
      expires_at_ms: null,
    },
  ],
  page: { limit: 20, offset: 0, returned: 2 },
};

export const mockSystemConfig: AdminServerConfigDiagnosticsResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  auth: {
    enabled: true,
    token_env: "TARU_ADMIN_TOKEN",
  },
  network: {
    exposure_mode: "reverse_proxy",
    readiness: {
      status: "ready",
      reason: "ready",
      checks: [
        { name: "exposure_mode", status: "ready", reason: "ready" },
        { name: "auth", status: "ready", reason: "ready" },
        { name: "external_endpoint", status: "ready", reason: "ready" },
        { name: "trusted_proxy", status: "ready", reason: "ready" },
        { name: "origin_policy", status: "ready", reason: "ready" },
        { name: "tunnel_provider", status: "ready", reason: "ready" },
      ],
    },
    external_endpoint: {
      configured: true,
      scheme: "https",
      host_fingerprint: "sha256:11111111111111111111111111111111",
    },
    trusted_proxy: {
      headers_enabled: true,
      source_count: 2,
    },
    origins: {
      allowed_origin_count: 1,
      configured: true,
    },
    tunnel_providers: [
      {
        id: "cloudflared",
        kind: "cloudflare_tunnel",
        endpoint_configured: true,
        endpoint_scheme: "https",
        endpoint_host_fingerprint: "sha256:22222222222222222222222222222222",
        token_env: "TARU_TUNNEL_TOKEN",
        token_present: true,
      },
    ],
  },
  database: {
    configured_backend_kind: "sqlite",
    active_backend_kind: "sqlite",
    url_scheme: "sqlite",
    runtime_supported: true,
    migrated_on_startup: true,
    capabilities: {
      lifecycle: true,
      libraries: true,
      jobs: true,
      job_leases: true,
      media: true,
      scan_commits: true,
      metadata: true,
      catalog: true,
      playback_state: true,
      transcode_sessions: true,
      event_outbox: true,
      addons: true,
      automation: true,
      managed_artwork: true,
      vfs_cache: true,
      webhooks: true,
      search_index: true,
    },
  },
  runtime: {
    listen_addr: "127.0.0.1:3000",
    scan_concurrency: 2,
    probe_concurrency: 2,
    metadata_concurrency: 2,
    remux_concurrency: 1,
    webhook_concurrency: 2,
    remux_timeout_ms: 30000,
  },
  libraries: [
    {
      id: "library-anime",
      name: "Anime Vault",
      preset: "series",
      backend_kind: "local",
      root_scheme: "local",
      has_webdav_password_env: false,
      webdav_timeout_ms: null,
      webdav_max_attempts: null,
    },
    {
      id: "library-films",
      name: "Films",
      preset: "movies",
      backend_kind: "webdav",
      root_scheme: "webdav",
      has_webdav_password_env: true,
      webdav_timeout_ms: 15000,
      webdav_max_attempts: 3,
    },
  ],
  metadata: {
    raw_cache_retention_ms: 604800000,
    raw_cache_cleanup_on_startup: true,
    raw_cache_cleanup_interval_ms: 3600000,
    maintenance_policies: 2,
    providers: [
      {
        provider: "tmdb",
        enabled: true,
        token_env: null,
        api_key_env: "TMDB_API_KEY",
        has_api_base_url: true,
        has_image_base_url: true,
        language: "en-US",
        include_adult: false,
        header_count: 0,
        secret_header_count: 0,
        has_provider_runtime_override: false,
      },
    ],
    runtime: {
      timeout_ms: 10000,
      max_attempts: 3,
      min_interval_ms: 250,
      concurrency: 2,
      user_agent: "taru-admin-web-mock",
      has_proxy: false,
      circuit_breaker_failures: 5,
      circuit_breaker_backoff_ms: 30000,
    },
  },
  transcode: {
    hardware_policy: { requested: "nvenc", fallback: "cpu" },
    cpu_concurrency: 2,
    gpu_concurrency: 1,
  },
  staging: {
    max_bytes: 10737418240,
    retention_ms: 86400000,
    cleanup_on_startup: true,
  },
  playback: {
    remote_stream_concurrency: 4,
    remote_stage_concurrency: 2,
  },
  artwork: {
    artifact_root_configured: true,
    fetch_timeout_ms: 15000,
    fetch_max_attempts: 3,
    fetch_max_bytes: 10485760,
    fetch_concurrency: 2,
    ingest_worker_enabled: true,
    ingest_worker_idle_ms: 1000,
    fetch_user_agent: "taru-artwork-fetch",
    has_fetch_proxy: false,
    max_width: 4096,
    max_height: 4096,
  },
};

export const mockSources: AdminSourceMap = {
  overview: "mock",
  addons: "mock",
  addonHealth: "mock",
  addonSurfaces: "mock",
  addonTokens: "mock",
  addonGrants: "mock",
  acquisitionIntake: "mock",
  catalogGovernance: "mock",
  events: "mock",
  jobs: "mock",
  playbackSessions: "mock",
  playbackRuntime: "mock",
  storageStaging: "mock",
  systemConfig: "mock",
};

export const mockAdminConsoleData: AdminConsoleData = {
  sources: mockSources,
  errors: {},
  overview: mockOverview,
  addons: {
    selectedAddonId: "addon-subtitle-lab",
    addons: mockAddons.addons.map((addon) => ({
      id: addon.id,
      manifestId: addon.manifest_id,
      name: addon.name,
      version: addon.version,
      protocolVersion: addon.protocol_version,
      baseUrl: addon.base_url,
      status: addon.status,
      grantedScopes: addon.granted_scopes,
      updatedAt: addon.updated_at,
    })),
    selectedAddon: {
      id: mockAddonDetail.addon.summary.id,
      manifestId: mockAddonDetail.addon.summary.manifest_id,
      name: mockAddonDetail.addon.summary.name,
      version: mockAddonDetail.addon.summary.version,
      protocolVersion: mockAddonDetail.addon.summary.protocol_version,
      baseUrl: mockAddonDetail.addon.summary.base_url,
      status: mockAddonDetail.addon.summary.status,
      grantedScopes: mockAddonDetail.addon.summary.granted_scopes,
      updatedAt: mockAddonDetail.addon.summary.updated_at,
      description: mockAddonDetail.addon.manifest.description,
      resourceCount: mockAddonDetail.addon.manifest.resources.length,
      resourceKinds: mockAddonDetail.addon.manifest.resources.map((resource) => resource.kind),
      authMode: mockAddonDetail.addon.manifest.auth,
      defaultTimeoutMs: mockAddonDetail.addon.manifest.default_timeout_ms,
      defaultMaxAttempts: mockAddonDetail.addon.manifest.default_max_attempts,
    },
    health: {
      addonId: mockAddonHealth.addon_id,
      status: mockAddonHealth.status,
      latencyMs: mockAddonHealth.latency_ms,
      protocolVersion: mockAddonHealth.protocol_version ?? null,
      addonVersion: mockAddonHealth.addon_version ?? null,
      resourceCount: mockAddonHealth.resource_count ?? null,
      safeErrorCode: mockAddonHealth.safe_error_code ?? null,
    },
    surfaces: {
      entryPoints: mockAddonSurfaces.entry_points.map((entryPoint) => ({
        id: entryPoint.id,
        label: entryPoint.label,
        kind: entryPoint.kind,
        path: entryPoint.path,
        hostedPageId: entryPoint.hosted_page_id ?? null,
      })),
      hostedPages: mockAddonSurfaces.hosted_pages.map((page) => ({
        id: page.id,
        title: page.title,
        path: page.path,
        url: page.url,
      })),
      configurationSchemaId: mockAddonSurfaces.configuration_schema?.schema_id ?? null,
      secretReferenceFieldCount: mockAddonSurfaces.secret_reference_fields.length,
      tasks: mockAddonSurfaces.tasks.map((task) => ({
        id: task.id,
        name: task.name,
        path: task.path,
      })),
      eventSubscriptions: mockAddonSurfaces.event_subscriptions.map((subscription) => ({
        id: subscription.id,
        eventKind: subscription.event_kind,
        path: subscription.path,
      })),
    },
    tokens: mockAddonTokens.tokens.map((token) => ({
      id: token.id,
      label: token.label,
      tokenPrefix: token.token_prefix,
      status: token.status,
      lastUsedAt: token.last_used_at,
    })),
    grants: mockAddonGrants.grants.map((grant) => ({
      id: grant.id,
      permission: grant.permission,
      libraryId: grant.library_id,
    })),
    diagnostic: {
      addonId: mockAddonDiagnostic.addon_id,
      resource: mockAddonDiagnostic.resource,
      status: mockAddonDiagnostic.status,
      latencyMs: mockAddonDiagnostic.latency_ms,
      attempts: mockAddonDiagnostic.attempts,
      httpStatus: mockAddonDiagnostic.http_status ?? null,
      safeErrorCode: mockAddonDiagnostic.safe_error_code ?? null,
    },
  },
  libraries: [
    {
      id: "library-anime",
      name: "Anime Vault",
      backendKind: "local",
      status: "ready",
      itemCount: 1248,
      lastScan: "14 min ago",
    },
    {
      id: "library-films",
      name: "Films",
      backendKind: "webdav",
      status: "ready",
      itemCount: 382,
      lastScan: "2 hr ago",
    },
    {
      id: "library-archive",
      name: "Archive",
      backendKind: "local",
      status: "degraded",
      itemCount: 91,
      lastScan: "needs review",
    },
  ],
  catalog: {
    items: mockCatalogGovernance.items.map((item) => ({
      id: item.item_id,
      title: item.title,
      kind: item.kind,
      issues: item.issues,
      sourceCount: item.source_count,
      providerMappingCount: item.provider_mapping_count,
    })),
    page: mockCatalogGovernance.page,
  },
  acquisitionIntake: {
    candidates: mockAcquisitionIntakeCandidates.candidates.map((candidate) => ({
      id: candidate.id,
      sourceKind: candidate.source_kind,
      sourceScheme: candidate.source_scheme ?? "unknown",
      state: candidate.state,
      sizeBytes: candidate.size_bytes,
      hasDiagnostics: candidate.has_diagnostics,
      linkedArtifactId: candidate.managed_import_artifact_id,
    })),
    page: mockAcquisitionIntakeCandidates.page,
  },
  events: {
    events: mockEvents.events.map((event) => ({
      id: event.id,
      kind: event.kind,
      status: event.status,
      attempts: event.attempts,
      hasError: event.has_error,
    })),
    page: mockEvents.page,
  },
  jobs: mockJobs.jobs.map((job) => ({
    id: job.id,
    kind: job.kind,
    status: job.status,
    resourceClass: job.resource_class,
    hasError: job.has_error,
  })),
  playback: {
    hardwarePolicy: "Prefer NVENC, fall back to CPU",
    ffmpegStatus: mockPlaybackRuntime.ffmpeg.probe_status,
    accelerators: mockPlaybackRuntime.hardware.capabilities.map((capability) => ({
      name: capability.accelerator,
      available: capability.available,
    })),
    sessions: mockPlaybackSessions.sessions.map((session) => ({
      id: session.id,
      kind: session.kind,
      sourceTitle: session.source_id,
      state: session.state,
    })),
  },
  storage: {
    stagingUsedBytes: mockStorageStaging.summary.used_manifest_bytes,
    stagingMaxBytes: mockStorageStaging.summary.configured_max_bytes,
    vfsObjectCount: mockStorageStaging.summary.vfs_cache.object_count,
    records: mockStorageStaging.records.map((record) => ({
      id: record.id,
      sourceScheme: record.source_scheme,
      purpose: record.purpose,
      state: record.state,
      sizeBytes: record.size_bytes,
      hasValidationError: record.has_validation_error,
    })),
  },
  network: {
    exposureMode: mockSystemConfig.network.exposure_mode,
    readinessStatus: mockSystemConfig.network.readiness.status,
    readinessReason: mockSystemConfig.network.readiness.reason,
    endpointConfigured: mockSystemConfig.network.external_endpoint.configured,
    endpointScheme: mockSystemConfig.network.external_endpoint.scheme,
    trustedProxyHeaders: mockSystemConfig.network.trusted_proxy.headers_enabled,
    trustedProxySourceCount: mockSystemConfig.network.trusted_proxy.source_count,
    allowedOriginCount: mockSystemConfig.network.origins.allowed_origin_count,
    tunnelProviderCount: mockSystemConfig.network.tunnel_providers.length,
  },
  settings: [
    {
      label: "Admin auth",
      value: mockSystemConfig.auth.enabled ? "Auth configured" : "Auth disabled",
    },
    {
      label: "Network readiness",
      value: `${mockSystemConfig.network.exposure_mode} · ${mockSystemConfig.network.readiness.status}`,
    },
    { label: "FFmpeg", value: "Configured, diagnostics only" },
    {
      label: "Transcode policy",
      value: `${mockSystemConfig.transcode.gpu_concurrency} GPU slot`,
    },
    { label: "Settings edits", value: "Planned Admin API" },
  ],
};
