import type {
  AddonGrantsResponse,
  AddonTokensResponse,
  AdminAcquisitionIntakeCandidateListResponse,
  AdminAddonHealthCheckResponse,
  AdminAddonInstallGuideResponse,
  AdminAddonRegistrationResponse,
  AdminAddonRegistrationsResponse,
  AdminAddonResourceCallDiagnosticResponse,
  AdminAddonSurfacesResponse,
  AdminAccessSummaryResponse,
  AdminCatalogGovernanceItemDetailResponse,
  AdminCatalogGovernanceItemListResponse,
  AdminCatalogGovernanceProviderMappingReviewDecision,
  AdminCatalogGovernanceProviderMappingReviewPlanResponse,
  AdminCatalogGovernanceProviderMappingReviewResponse,
  AdminGeneratedArtifactProposalListResponse,
  AdminGeneratedArtifactReviewPlanResponse,
  AdminGeneratedArtifactReviewRequest,
  AdminGeneratedArtifactReviewResponse,
  AdminMetadataRawCacheSettingsResponse,
  AdminManagedArtworkGalleryResponse,
  AdminLibraryMetadataProfileResponse,
  AdminJobListResponse,
  AdminOutboxEventListResponse,
  AdminOverviewResponse,
  AdminPlaybackRuntimeDiagnosticsResponse,
  AdminPlaybackSessionListResponse,
  AdminPlaybackSupportEvidenceResponse,
  AdminServerConfigDiagnosticsResponse,
  AdminStorageStagingDiagnosticsResponse,
  AdminWatchFolderDiscoveryResponse,
} from "./generated/contract";
import type {
  AdminConsoleData,
  AdminSourceMap,
  AddonsRouteSummary,
  CatalogBrowseSummary,
  ItemArtworkGallerySummary,
  ItemDetailSummary,
  PublicCatalogItemsResponse,
  PublicCatalogSearchResponse,
  PublicItemDetailResponse,
  PublicSourceProbeResponse,
} from "./types";

export const mockAccessSummary: AdminAccessSummaryResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  mode: "single_admin",
  principal: {
    principal_id: "local-admin",
    display_name: "Local administrator",
    principal_kind: "local_admin",
  },
  auth: {
    enabled: true,
    token_reference_configured: true,
  },
  readiness: {
    single_admin_mode: "active",
    user_accounts: "planned",
    roles: "planned",
    library_access_policy: "planned",
  },
  library_access: {
    configured_libraries: 2,
    libraries: [
      {
        library_id: "library-anime",
        library_name: "Anime Vault",
        preset: "series",
        backend_kind: "local",
        access: "manage",
        reason: "single_admin_mode",
      },
      {
        library_id: "library-films",
        library_name: "Films",
        preset: "movies",
        backend_kind: "webdav",
        access: "manage",
        reason: "single_admin_mode",
      },
    ],
  },
};

export const mockOverview: AdminOverviewResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  status: "healthy",
  storage: {
    total_backends: 3,
    ready_backends: 2,
    degraded_backends: 1,
    unavailable_backends: 0,
    backends: [
      {
        library_id: "library-anime",
        library_name: "Anime Vault",
        backend_kind: "local",
        status: "ready",
      },
      {
        library_id: "library-films",
        library_name: "Films",
        backend_kind: "webdav",
        status: "ready",
      },
      {
        library_id: "library-archive",
        library_name: "Archive",
        backend_kind: "local",
        status: "degraded",
      },
    ],
  },
  catalog: {
    governed_items: 1240,
    unknown_kind_items: 3,
    low_confidence_items: 11,
    items_with_duplicate_relationships: 2,
    items_missing_accepted_provider_mapping: 7,
  },
  metadata: {
    total_providers: 4,
    available_providers: 3,
    disabled_providers: 1,
    unavailable_providers: 0,
    providers: [
      { provider: "tmdb", status: "available" },
      { provider: "douban", status: "available" },
      { provider: "bangumi", status: "available" },
      { provider: "nfo", status: "disabled" },
    ],
  },
  runtime: {
    active_tasks: 4,
    completed_tasks: 186,
    failed_tasks: 2,
    succeeded_jobs: 72,
    cancelled_jobs: 1,
    failed_jobs: 3,
    shutdown_requested: false,
  },
  startup: {
    configured_libraries: 3,
    recovered_transcode_sessions: 0,
    recovered_jobs: 1,
    staging_deleted_records: 4,
    staging_deleted_files: 4,
    metadata_raw_cache_deleted: 18,
    metadata_lifecycle_tasks_started: 2,
    artwork_ingest_worker_started: true,
  },
};

export const mockCatalogGovernance: AdminCatalogGovernanceItemListResponse = {
  items: [
    {
      item_id: "item-unknown-1",
      library_id: "library-anime",
      kind: "unknown",
      parent_id: null,
      title: "Unmatched OVA Special",
      release_date: null,
      source_count: 2,
      representative_source_id: "source-unknown-1",
      representative_file_name: "Unmatched OVA Special.mkv",
      local_inference: {
        source_id: "source-unknown-1",
        inferred_kind: "movie",
        inferred_title: "Unmatched OVA Special",
        inferred_year: null,
        inferred_season: null,
        inferred_episode: null,
        confidence_milli: 420,
        evidence_source: "path",
        has_evidence: true,
        inference_version: "nako-naming:1",
      },
      provider_mapping_count: 0,
      accepted_provider_mapping_count: 0,
      duplicate_relationship_count: 1,
      issues: ["unknown_kind", "low_local_inference_confidence"],
    },
    {
      item_id: "item-low-confidence",
      library_id: "library-films",
      kind: "movie",
      parent_id: null,
      title: "Film Needs Mapping",
      release_date: "1999-01-01",
      source_count: 1,
      representative_source_id: "source-low-confidence",
      representative_file_name: "Film Needs Mapping.mkv",
      local_inference: null,
      provider_mapping_count: 1,
      accepted_provider_mapping_count: 0,
      duplicate_relationship_count: 0,
      issues: ["missing_accepted_provider_mapping"],
    },
  ],
  page: { limit: 20, offset: 0, returned: 2 },
};

export function mockCatalogGovernanceItemDetail(
  itemId = "item-low-confidence",
): AdminCatalogGovernanceItemDetailResponse {
  const item =
    mockCatalogGovernance.items.find((candidate) => candidate.item_id === itemId) ??
    mockCatalogGovernance.items[1];

  return {
    admin_api_version: "v1",
    public_api_version: "v1",
    item: {
      ...item,
      item_id: itemId,
      provider_mapping_count: 1,
      accepted_provider_mapping_count: 0,
      issues: ["missing_accepted_provider_mapping"],
    },
    provider_mappings: [
      {
        mapping_id: "mapping-tmdb-603",
        item_id: itemId,
        status: "candidate",
        confidence_milli: 820,
        source: { provider: "tmdb" },
        subject: {
          subject_id: "subject-tmdb-603",
          provider: "tmdb",
          subject_kind: "movie",
          subject_key: "603",
          title: "The Candidate",
          release_year: 2026,
          locale: "en-US",
        },
      },
    ],
    repair_actions: ["provider_mapping_review"],
  };
}

export function mockCatalogGovernanceProviderMappingReviewPlan(
  itemId = "item-low-confidence",
  mappingId = "mapping-tmdb-603",
  decision: AdminCatalogGovernanceProviderMappingReviewDecision = "accept",
): AdminCatalogGovernanceProviderMappingReviewPlanResponse {
  const detail = mockCatalogGovernanceItemDetail(itemId);
  const mapping = {
    ...detail.provider_mappings[0],
    mapping_id: mappingId,
  };
  const targetStatus = decision === "accept" ? "accepted" : "rejected";

  return {
    admin_api_version: "v1",
    public_api_version: "v1",
    plan: {
      item: detail.item,
      mapping,
      decision,
      current_status: mapping.status,
      target_status: targetStatus,
      status: "ready",
      readiness: {
        status: "ready",
        actionable: true,
        reasons:
          mapping.status === targetStatus
            ? ["already_in_target_status"]
            : ["provider_mapping_status_change"],
      },
      boundary: {
        updates_provider_mapping_status: true,
        updates_canonical_metadata: false,
        updates_provider_subject: false,
        updates_local_inference: false,
        updates_source_duplicates: false,
        updates_hierarchy: false,
        writes_nfo: false,
        writes_library_files: false,
        updates_artwork: false,
        updates_playback_state: false,
      },
    },
  };
}

export function mockCatalogGovernanceProviderMappingReviewResponse(
  itemId = "item-low-confidence",
  mappingId = "mapping-tmdb-603",
  decision: AdminCatalogGovernanceProviderMappingReviewDecision = "accept",
  idempotentReplay = false,
): AdminCatalogGovernanceProviderMappingReviewResponse {
  const plan = mockCatalogGovernanceProviderMappingReviewPlan(itemId, mappingId, decision).plan;
  const previousStatus = idempotentReplay ? plan.target_status : plan.current_status;

  return {
    admin_api_version: "v1",
    public_api_version: "v1",
    item_id: itemId,
    mapping_id: mappingId,
    decision,
    previous_status: previousStatus,
    current_status: plan.target_status,
    changed: !idempotentReplay,
    idempotent_replay: idempotentReplay,
    plan: {
      ...plan,
      current_status: idempotentReplay ? plan.target_status : plan.current_status,
      mapping: {
        ...plan.mapping,
        status: plan.target_status,
      },
      readiness: {
        ...plan.readiness,
        reasons: idempotentReplay
          ? ["already_in_target_status"]
          : ["provider_mapping_status_change"],
      },
    },
  };
}

export const mockPublicCatalogItems: PublicCatalogItemsResponse = {
  items: [
    {
      id: "item-unknown-1",
      kind: "unknown",
      parent_id: null,
      metadata: {
        title: "Unmatched OVA Special",
        original_title: null,
        sort_title: "Unmatched OVA Special",
        overview: "Locally inferred item awaiting hierarchy confirmation.",
        release_date: null,
        runtime_minutes: 48,
        tagline: null,
        genres: ["anime"],
        tags: ["needs-review", "local-inference"],
        ratings: [],
        credits: [],
        collections: [],
        studios: [],
        external_ids: [],
      },
    },
    {
      id: "item-low-confidence",
      kind: "movie",
      parent_id: null,
      metadata: {
        title: "Film Needs Mapping",
        original_title: null,
        sort_title: "Film Needs Mapping",
        overview: null,
        release_date: "1999-01-01",
        runtime_minutes: 101,
        tagline: null,
        genres: ["drama", "mystery"],
        tags: ["provider-mapping"],
        ratings: [{ source: "local", value: "PG-13" }],
        credits: [
          {
            name: "Demo Director",
            role: "director",
            character: null,
            order: 1,
            external_ids: [],
          },
        ],
        collections: [],
        studios: [{ name: "Demo Studio", external_ids: [] }],
        external_ids: [],
      },
    },
  ],
  page: { limit: 20, offset: 0, returned: 2 },
};

export const mockPublicCatalogSearch: PublicCatalogSearchResponse = {
  hits: [
    {
      item: mockPublicCatalogItems.items[0],
      score: 0.91,
    },
  ],
  page: { limit: 20, offset: 0, returned: 1 },
};

export const mockCatalogBrowse: CatalogBrowseSummary = {
  mode: "browse",
  items: mockPublicCatalogItems.items.map((item) => ({
    id: item.id,
    parentId: item.parent_id,
    title: item.metadata.title,
    kind: item.kind,
    releaseDate: item.metadata.release_date,
    runtimeMinutes: item.metadata.runtime_minutes,
    genreCount: item.metadata.genres.length,
    tagCount: item.metadata.tags.length,
    creditCount: item.metadata.credits.length,
    collectionCount: item.metadata.collections.length,
    studioCount: item.metadata.studios.length,
    imageCount: null,
    sourceCount: null,
    score: null,
  })),
  page: mockPublicCatalogItems.page,
};

export function mockPublicItemDetail(itemId = "item-unknown-1"): PublicItemDetailResponse {
  const item =
    mockPublicCatalogItems.items.find((candidate) => candidate.id === itemId)
    ?? {
      ...mockPublicCatalogItems.items[0],
      id: itemId,
      metadata: {
        ...mockPublicCatalogItems.items[0].metadata,
        title: `Media Item ${itemId}`,
      },
    };

  return {
    item,
    sources: [
      {
        id: "source-unknown-1",
        library_id: "library-anime",
        item_id: item.id,
        file_name: "Unmatched OVA Special.mkv",
        size_bytes: 1468006400,
        fingerprint: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      },
      {
        id: "source-unknown-2",
        library_id: "library-anime",
        item_id: item.id,
        file_name: "Unmatched OVA Special - 1080p.mkv",
        size_bytes: 2147483648,
        fingerprint: null,
      },
    ],
    credits: [
      {
        item_id: item.id,
        person_id: "person-demo-director",
        role: "director",
        character: null,
        sort_order: 1,
      },
    ],
    genres: [{ item_id: item.id, genre_id: "genre-anime" }],
    tags: [
      { item_id: item.id, tag_id: "tag-needs-review" },
      { item_id: item.id, tag_id: "tag-local-inference" },
    ],
    collections: [],
    studios: [{ item_id: item.id, studio_id: "studio-demo" }],
    images: [
      {
        id: "image-unknown-poster",
        owner: { kind: "item", item_id: item.id },
        kind: "poster",
        url: "/images/image-unknown-poster",
        width: 1000,
        height: 1500,
        language: null,
        media_type: "image/jpeg",
        etag: "poster-etag",
      },
    ],
  };
}

export function mockAdminItemArtworkGallery(
  itemId = "item-unknown-1",
): AdminManagedArtworkGalleryResponse {
  return {
    item_id: itemId,
    summary: {
      candidates: 2,
      artifacts: 2,
      selected: 1,
    },
    candidates: [
      {
        id: "candidate-poster-1",
        addon_id: "addon-artwork-curator",
        side_effect_id: "side-effect-poster-1",
        library_id: "library-anime",
        item_id: itemId,
        kind: "poster",
        source_kind: "provider",
        status: "accepted",
        width: 1000,
        height: 1500,
        language: "ja",
        ingest: {
          id: "ingest-poster-1",
          candidate_id: "candidate-poster-1",
          job_id: "job-artwork-1",
          library_id: "library-anime",
          item_id: itemId,
          kind: "poster",
          status: "completed",
          has_artifact: true,
          has_failure: false,
          failure_code: null,
          created_at: "2026-05-25T01:00:00Z",
          updated_at: "2026-05-25T01:10:00Z",
        },
        artifact_id: "artifact-poster-1",
        has_stored_artifact: true,
        selected_artwork_count: 1,
        selected: true,
        created_at: "2026-05-25T00:59:00Z",
        updated_at: "2026-05-25T01:11:00Z",
      },
      {
        id: "candidate-backdrop-1",
        addon_id: "addon-artwork-curator",
        side_effect_id: "side-effect-backdrop-1",
        library_id: "library-anime",
        item_id: itemId,
        kind: "backdrop",
        source_kind: "local",
        status: "accepted",
        width: 1920,
        height: 1080,
        language: null,
        ingest: {
          id: "ingest-backdrop-1",
          candidate_id: "candidate-backdrop-1",
          job_id: "job-artwork-2",
          library_id: "library-anime",
          item_id: itemId,
          kind: "backdrop",
          status: "completed",
          has_artifact: true,
          has_failure: false,
          failure_code: null,
          created_at: "2026-05-25T01:20:00Z",
          updated_at: "2026-05-25T01:21:00Z",
        },
        artifact_id: "artifact-backdrop-1",
        has_stored_artifact: true,
        selected_artwork_count: 0,
        selected: false,
        created_at: "2026-05-25T01:19:00Z",
        updated_at: "2026-05-25T01:22:00Z",
      },
    ],
    artifacts: [
      {
        id: "artifact-poster-1",
        ingest_id: "ingest-poster-1",
        candidate_id: "candidate-poster-1",
        library_id: "library-anime",
        item_id: itemId,
        kind: "poster",
        selected_artwork_count: 1,
        selected: true,
        width: 1000,
        height: 1500,
        byte_len: 542000,
        media_type: "image/jpeg",
        has_content_hash: true,
        created_at: "2026-05-25T01:10:00Z",
        updated_at: "2026-05-25T01:11:00Z",
      },
      {
        id: "artifact-backdrop-1",
        ingest_id: "ingest-backdrop-1",
        candidate_id: "candidate-backdrop-1",
        library_id: "library-anime",
        item_id: itemId,
        kind: "backdrop",
        selected_artwork_count: 0,
        selected: false,
        width: 1920,
        height: 1080,
        byte_len: 804000,
        media_type: "image/webp",
        has_content_hash: true,
        created_at: "2026-05-25T01:21:00Z",
        updated_at: "2026-05-25T01:22:00Z",
      },
    ],
    selected: [
      {
        selected_artwork: {
          id: "selected-poster-1",
          library_id: "library-anime",
          item_id: itemId,
          kind: "poster",
          artifact_id: "artifact-poster-1",
          created_at: "2026-05-25T01:12:00Z",
          updated_at: "2026-05-25T01:12:00Z",
        },
        artifact: {
          id: "artifact-poster-1",
          ingest_id: "ingest-poster-1",
          candidate_id: "candidate-poster-1",
          library_id: "library-anime",
          item_id: itemId,
          kind: "poster",
          selected_artwork_count: 1,
          selected: true,
          width: 1000,
          height: 1500,
          byte_len: 542000,
          media_type: "image/jpeg",
          has_content_hash: true,
          created_at: "2026-05-25T01:10:00Z",
          updated_at: "2026-05-25T01:11:00Z",
        },
        image: {
          id: "image-poster-1",
          owner: {
            kind: "item",
            item_id: itemId,
          },
          kind: "poster",
          url: "/images/image-poster-1",
          width: 1000,
          height: 1500,
          language: "ja",
          media_type: "image/jpeg",
          etag: "poster-etag",
        },
      },
    ],
    page: {
      limit: 20,
      offset: 0,
      returned: 2,
    },
  };
}

export function mockItemArtworkGallerySummary(
  itemId = "item-unknown-1",
): ItemArtworkGallerySummary {
  return {
    itemId,
    totals: {
      candidateCount: 2,
      artifactCount: 2,
      selectedCount: 1,
    },
    candidates: [
      {
        id: "candidate-poster-1",
        addonId: "addon-artwork-curator",
        sideEffectId: "side-effect-poster-1",
        libraryId: "library-anime",
        itemId,
        kind: "poster",
        sourceKind: "provider",
        status: "accepted",
        width: 1000,
        height: 1500,
        language: "ja",
        ingestId: "ingest-poster-1",
        ingestStatus: "completed",
        hasIngestArtifact: true,
        hasIngestFailure: false,
        ingestFailureCode: null,
        artifactId: "artifact-poster-1",
        hasStoredArtifact: true,
        selectedArtworkCount: 1,
        selected: true,
        updatedAt: "2026-05-25T01:11:00Z",
      },
      {
        id: "candidate-backdrop-1",
        addonId: "addon-artwork-curator",
        sideEffectId: "side-effect-backdrop-1",
        libraryId: "library-anime",
        itemId,
        kind: "backdrop",
        sourceKind: "local",
        status: "accepted",
        width: 1920,
        height: 1080,
        language: null,
        ingestId: "ingest-backdrop-1",
        ingestStatus: "completed",
        hasIngestArtifact: true,
        hasIngestFailure: false,
        ingestFailureCode: null,
        artifactId: "artifact-backdrop-1",
        hasStoredArtifact: true,
        selectedArtworkCount: 0,
        selected: false,
        updatedAt: "2026-05-25T01:22:00Z",
      },
    ],
    artifacts: [
      {
        id: "artifact-poster-1",
        ingestId: "ingest-poster-1",
        candidateId: "candidate-poster-1",
        libraryId: "library-anime",
        itemId,
        kind: "poster",
        selectedArtworkCount: 1,
        selected: true,
        width: 1000,
        height: 1500,
        byteLen: 542000,
        mediaType: "image/jpeg",
        hasContentHash: true,
        updatedAt: "2026-05-25T01:11:00Z",
      },
      {
        id: "artifact-backdrop-1",
        ingestId: "ingest-backdrop-1",
        candidateId: "candidate-backdrop-1",
        libraryId: "library-anime",
        itemId,
        kind: "backdrop",
        selectedArtworkCount: 0,
        selected: false,
        width: 1920,
        height: 1080,
        byteLen: 804000,
        mediaType: "image/webp",
        hasContentHash: true,
        updatedAt: "2026-05-25T01:22:00Z",
      },
    ],
    selected: [
      {
        selectedArtworkId: "selected-poster-1",
        libraryId: "library-anime",
        itemId,
        kind: "poster",
        artifactId: "artifact-poster-1",
        imageId: "image-poster-1",
        routePath: "/images/image-poster-1",
        width: 1000,
        height: 1500,
        language: "ja",
        mediaType: "image/jpeg",
        selectedAt: "2026-05-25T01:12:00Z",
        updatedAt: "2026-05-25T01:12:00Z",
      },
    ],
    page: {
      limit: 20,
      offset: 0,
      returned: 2,
    },
  };
}

export function mockPublicSourceProbe(sourceId = "source-unknown-1"): PublicSourceProbeResponse {
  return {
    source_id: sourceId,
    probe: {
      duration_ms: 2880000,
      container: "matroska",
      bit_rate: 4200000,
      streams: [
        {
          index: 0,
          kind: "video",
          codec: "h264",
          language: null,
          duration_ms: 2880000,
          bit_rate: 3600000,
          width: 1920,
          height: 1080,
          channels: null,
          sample_rate: null,
        },
        {
          index: 1,
          kind: "audio",
          codec: "aac",
          language: "ja",
          duration_ms: 2880000,
          bit_rate: 192000,
          width: null,
          height: null,
          channels: 2,
          sample_rate: 48000,
        },
        {
          index: 2,
          kind: "subtitle",
          codec: "ass",
          language: "en",
          duration_ms: null,
          bit_rate: null,
          width: null,
          height: null,
          channels: null,
          sample_rate: null,
        },
      ],
    },
  };
}

export function mockItemDetailSummary(itemId = "item-unknown-1"): ItemDetailSummary {
  const detail = mockPublicItemDetail(itemId);
  const probe = mockPublicSourceProbe(detail.sources[0]?.id ?? "source-unknown-1").probe;

  return {
    item: {
      id: detail.item.id,
      parentId: detail.item.parent_id,
      title: detail.item.metadata.title,
      kind: detail.item.kind,
      releaseDate: detail.item.metadata.release_date,
      runtimeMinutes: detail.item.metadata.runtime_minutes,
      genreCount: detail.item.metadata.genres.length,
      tagCount: detail.item.metadata.tags.length,
      creditCount: detail.credits.length,
      collectionCount: detail.collections.length,
      studioCount: detail.studios.length,
      imageCount: detail.images.length,
      sourceCount: detail.sources.length,
    },
    canonical: {
      genres: detail.item.metadata.genres,
      tags: detail.item.metadata.tags,
      credits: detail.item.metadata.credits.map((credit) => ({
        name: credit.name,
        role: credit.role,
        character: credit.character,
      })),
      collections: detail.item.metadata.collections.map((collection) => collection.name),
      studios: detail.item.metadata.studios.map((studio) => studio.name),
      ratingCount: detail.item.metadata.ratings.length,
      externalIdCount: detail.item.metadata.external_ids.length,
    },
    sources: detail.sources.map((source, index) => ({
      id: source.id,
      libraryId: source.library_id,
      fileName: source.file_name,
      sizeBytes: source.size_bytes,
      hasFingerprint: Boolean(source.fingerprint),
      probe:
        index === 0
          ? {
              durationMs: probe.duration_ms,
              container: probe.container,
              bitRate: probe.bit_rate,
              streamCount: probe.streams.length,
              videoStreamCount: 1,
              audioStreamCount: 1,
              subtitleStreamCount: 1,
            }
          : null,
    })),
    images: detail.images.map((image) => ({
      id: image.id,
      kind: image.kind,
      routePath: image.url.startsWith("/images/") ? image.url : null,
      width: image.width,
      height: image.height,
      language: image.language,
      mediaType: image.media_type,
      hasEtag: Boolean(image.etag),
    })),
    readiness: [
      {
        label: "NFO sidecar status",
        status: "split",
        detail: "Admin NFO item status read model is split from MBG-040.",
      },
      {
        label: "Provider Mapping",
        status: "split",
        detail: "Provider Mapping decisions need a follow-on repair workflow.",
      },
      {
        label: "Local Inference",
        status: "split",
        detail: "Local Inference evidence diagnostics need an Admin read model.",
      },
      {
        label: "Generated Artifacts",
        status: "planned",
        detail: "Use route-level automation queue until per-item review is split.",
      },
      {
        label: "Artwork decisions",
        status: "ready",
        detail: "Public image refs are available for presentation readiness.",
      },
      {
        label: "Catalog repair",
        status: "split",
        detail: "Repair/apply mutations stay out of the first item detail slice.",
      },
    ],
  };
}

export const mockAcquisitionIntakeCandidates: AdminAcquisitionIntakeCandidateListResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  candidates: [
    {
      id: "candidate-ready",
      target_library_id: "library-anime",
      source_kind: "watch_folder",
      custom_source_kind: false,
      source_scheme: "local",
      source_ref_redacted: "local://<redacted>",
      source_key_fingerprint: "sha256:11111111111111111111111111111111",
      has_display_name: true,
      has_intended_locator: false,
      size_bytes: 1468006400,
      has_fingerprint: true,
      managed_import_artifact_id: null,
      state: "ready",
      has_diagnostics: true,
      first_seen_at_ms: 1779180000000,
      last_seen_at_ms: 1779180200000,
      created_at_ms: 1779180000000,
      updated_at_ms: 1779180200000,
    },
    {
      id: "candidate-blocked",
      target_library_id: "library-films",
      source_kind: "watch_folder",
      custom_source_kind: false,
      source_scheme: "local",
      source_ref_redacted: "local://<redacted>",
      source_key_fingerprint: "sha256:22222222222222222222222222222222",
      has_display_name: true,
      has_intended_locator: false,
      size_bytes: 1024,
      has_fingerprint: true,
      managed_import_artifact_id: null,
      state: "blocked",
      has_diagnostics: true,
      first_seen_at_ms: 1779180100000,
      last_seen_at_ms: 1779180300000,
      created_at_ms: 1779180100000,
      updated_at_ms: 1779180300000,
    },
  ],
  page: { limit: 20, offset: 0, returned: 2 },
};

export const mockWatchFolderDiscovery: AdminWatchFolderDiscoveryResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  target_library_id: "library-anime",
  root_scheme: "local",
  root_ref_redacted: "local://<redacted>",
  ready_candidates: 1,
  blocked_candidates: 1,
  incomplete_candidates: 1,
  unsupported_candidates: 0,
  recorded_candidates: 2,
  failures: [],
  writes_library: false,
  managed_import_artifacts_created: false,
  promotion_apply: false,
};

export const mockGeneratedArtifactProposals: AdminGeneratedArtifactProposalListResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  proposals: [
    {
      id: "artifact-metadata-cleanup",
      kind: "metadata_suggestion",
      capability: "metadata_cleanup",
      status: "proposed",
      target: {
        kind: "media_source",
        library_id: "library-anime",
        item_id: "item-unknown-1",
        source_id: "source-unknown-1",
      },
      provenance: {
        provider_id: "provider-automation",
        provider_name: "Automation gateway",
        job_id: "job-automation",
        capability: "metadata_cleanup",
        idempotency_key_fingerprint: "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        prompt_fingerprint: "sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        attempt_count: 1,
        artifact_created_at: "2026-05-19T10:06:00Z",
      },
      payload: {
        valid_json: true,
        shape: "object",
        payload_fingerprint: "sha256:cccccccccccccccccccccccccccccccc",
        payload_bytes: 512,
        object_field_count: 3,
        array_item_count: null,
        has_textual_values: true,
        has_explanation: true,
        confidence_milli: 810,
      },
      readiness: {
        status: "ready",
        actionable: true,
        reasons: ["ready"],
      },
      created_at: "2026-05-19T10:06:00Z",
      updated_at: "2026-05-19T10:06:00Z",
      accepted_at: null,
    },
    {
      id: "artifact-stale-title-match",
      kind: "title_match",
      capability: "title_match",
      status: "proposed",
      target: {
        kind: "media_item",
        library_id: "library-films",
        item_id: "item-low-confidence",
        source_id: null,
      },
      provenance: {
        provider_id: "provider-automation",
        provider_name: "Automation gateway",
        job_id: "job-automation-stale",
        capability: "title_match",
        idempotency_key_fingerprint: "sha256:dddddddddddddddddddddddddddddddd",
        prompt_fingerprint: "sha256:eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
        attempt_count: 2,
        artifact_created_at: "2026-05-19T10:07:00Z",
      },
      payload: {
        valid_json: true,
        shape: "object",
        payload_fingerprint: "sha256:ffffffffffffffffffffffffffffffff",
        payload_bytes: 256,
        object_field_count: 2,
        array_item_count: null,
        has_textual_values: true,
        has_explanation: false,
        confidence_milli: 640,
      },
      readiness: {
        status: "stale",
        actionable: false,
        reasons: ["target_mismatch"],
      },
      created_at: "2026-05-19T10:07:00Z",
      updated_at: "2026-05-19T10:08:00Z",
      accepted_at: null,
    },
  ],
  page: { limit: 20, offset: 0, returned: 2 },
};

export function mockGeneratedArtifactReviewPlan(
  artifactId = "artifact-metadata-cleanup",
  decision: AdminGeneratedArtifactReviewRequest["decision"] = "accept",
): AdminGeneratedArtifactReviewPlanResponse {
  const proposal =
    mockGeneratedArtifactProposals.proposals.find((candidate) => candidate.id === artifactId) ??
    mockGeneratedArtifactProposals.proposals[0];

  return {
    admin_api_version: "v1",
    public_api_version: "v1",
    plan: {
      artifact_id: artifactId,
      decision,
      status: proposal.readiness.actionable ? "ready" : "blocked",
      action: decision === "accept" ? "stage_metadata_authority_review" : "mark_rejected",
      reasons: proposal.readiness.reasons,
      capability: proposal.capability,
      kind: proposal.kind,
      target: proposal.target,
      payload: proposal.payload,
      readiness: proposal.readiness,
      boundary: {
        accepted_into_canonical_metadata: false,
        writes_sidecar: false,
        writes_library_files: false,
        applies_immediately: false,
        requires_metadata_authority_apply: decision === "accept",
      },
    },
  };
}

export function mockGeneratedArtifactReviewResponse(
  artifactId = "artifact-metadata-cleanup",
  decision: AdminGeneratedArtifactReviewRequest["decision"] = "accept",
): AdminGeneratedArtifactReviewResponse {
  return {
    admin_api_version: "v1",
    public_api_version: "v1",
    artifact_id: artifactId,
    decision,
    artifact_status: decision === "accept" ? "accepted" : "rejected",
    accepted_at: decision === "accept" ? "2026-05-25T11:00:00Z" : null,
    idempotent_replay: false,
    plan: mockGeneratedArtifactReviewPlan(artifactId, decision).plan,
  };
}

export const mockAddons: AdminAddonRegistrationsResponse = {
  addons: [
    {
      id: "addon-subtitle-lab",
      manifest_id: "dev.nako.subtitle-lab",
      name: "Subtitle Lab",
      version: "0.3.0",
      protocol_version: "2026-05-15",
      base_url: "http://subtitle-lab:9100",
      granted_scopes: ["subtitle_read", "item_metadata_read"],
      status: "enabled",
      created_at: "2026-05-22T02:10:00.000Z",
      updated_at: "2026-05-22T02:45:00.000Z",
    },
    {
      id: "addon-artwork-curator",
      manifest_id: "dev.nako.artwork-curator",
      name: "Artwork Curator",
      version: "0.2.1",
      protocol_version: "2026-05-15",
      base_url: "http://artwork-curator:9200",
      granted_scopes: ["image_read", "item_metadata_suggest"],
      status: "disabled",
      created_at: "2026-05-21T20:10:00.000Z",
      updated_at: "2026-05-22T01:00:00.000Z",
    },
  ],
};

export const mockAddonDetail: AdminAddonRegistrationResponse = {
  addon: {
    summary: mockAddons.addons[0],
    manifest: {
      id: "dev.nako.subtitle-lab",
      name: "Subtitle Lab",
      version: "0.3.0",
      protocol_version: "2026-05-15",
      base_url: "http://subtitle-lab:9100",
      description: "Suggests subtitle sidecars and metadata improvements.",
      resources: [
        {
          kind: "subtitle",
          path: "/resources/subtitles",
          input_schema: null,
          output_schema: null,
          required_scopes: ["subtitle_read"],
          timeout_ms: 5000,
          max_attempts: 2,
        },
        {
          kind: "metadata",
          path: "/resources/metadata",
          input_schema: null,
          output_schema: null,
          required_scopes: ["item_metadata_read"],
          timeout_ms: null,
          max_attempts: null,
        },
      ],
      auth: "bearer",
      default_timeout_ms: 5000,
      default_max_attempts: 2,
      scopes: ["subtitle_read", "item_metadata_read"],
    },
  },
};

export const mockAddonHealth: AdminAddonHealthCheckResponse = {
  addon_id: "addon-subtitle-lab",
  manifest_id: "dev.nako.subtitle-lab",
  status: "reachable",
  latency_ms: 42,
  protocol_version: "2026-05-15",
  addon_version: "0.3.0",
  resource_count: 2,
  protocol_checked_at: "2026-05-22T02:46:00.000Z",
};

export const mockAddonSurfaces: AdminAddonSurfacesResponse = {
  addon_id: "addon-subtitle-lab",
  manifest_id: "dev.nako.subtitle-lab",
  entry_points: [
    {
      id: "inspect-subtitles",
      kind: "item_action",
      label: "Inspect subtitles",
      path: "/entry/subtitles",
      hosted_page_id: "diagnostics",
      required_scopes: ["subtitle_read"],
    },
  ],
  hosted_pages: [
    {
      id: "diagnostics",
      title: "Subtitle diagnostics",
      path: "/pages/diagnostics",
      url: "http://subtitle-lab:9100/pages/diagnostics",
      required_scopes: ["subtitle_read"],
    },
  ],
  configuration_schema: {
    schema_id: "subtitle-lab-settings",
    schema: {
      type: "object",
      properties: {
        preferredLanguage: { type: "string" },
      },
    },
  },
  secret_reference_fields: [
    {
      id: "subtitle-provider-key",
      label: "Provider API key",
      description: "Secret Reference resolved by Nako at runtime.",
      required: false,
    },
  ],
  tasks: [
    {
      id: "scan-missing-subtitles",
      name: "Scan missing subtitles",
      path: "/tasks/missing-subtitles",
      description: "Find media items without subtitle sidecars.",
      required_scopes: ["subtitle_read"],
      timeout_ms: 30000,
      max_attempts: 1,
    },
  ],
  event_subscriptions: [
    {
      id: "scan-completed",
      event_kind: "scan.completed",
      path: "/events/scan-completed",
      required_scopes: ["item_metadata_read"],
      filters: {},
    },
  ],
};

export const mockAddonTokens: AddonTokensResponse = {
  tokens: [
    {
      id: "addon-token-active",
      addon_id: "addon-subtitle-lab",
      label: "sidecar runtime",
      token_prefix: "nako_at_subtitle",
      status: "active",
      created_at: "2026-05-22T02:10:00.000Z",
      rotated_at: null,
      revoked_at: null,
      last_used_at: "2026-05-22T02:44:00.000Z",
    },
  ],
};

export const mockAddonGrants: AddonGrantsResponse = {
  grants: [
    {
      id: "addon-grant-subtitle",
      addon_id: "addon-subtitle-lab",
      permission: "subtitle_write",
      library_id: "library-anime",
      created_at: "2026-05-22T02:10:00.000Z",
    },
  ],
};

export const mockAddonDiagnostic: AdminAddonResourceCallDiagnosticResponse = {
  addon_id: "addon-subtitle-lab",
  manifest_id: "dev.nako.subtitle-lab",
  resource: "subtitle",
  status: "succeeded",
  latency_ms: 85,
  attempts: 1,
  http_status: 200,
};

export const mockAddonInstallGuide: AdminAddonInstallGuideResponse = {
  addon_id: "addon-subtitle-lab",
  manifest_id: "dev.nako.subtitle-lab",
  addon_name: "Subtitle Lab",
  addon_version: "0.3.0",
  protocol_version: "2026-05-15",
  base_url: "http://subtitle-lab:9100",
  status: "enabled",
  docker_compose: {
    title: "Docker Compose sidecar snippet",
    filename: "compose.dev-nako-subtitle-lab.yml",
    content: [
      "services:",
      "  dev-nako-subtitle-lab:",
      "    image: \"<replace-with-dev-nako-subtitle-lab-image>:0.3.0\"",
      "    restart: unless-stopped",
      "    environment:",
      "      NAKO_ADDON_BASE_URL: \"http://subtitle-lab:9100\"",
      "      NAKO_ADDON_PROTOCOL_VERSION: \"2026-05-15\"",
      "      NAKO_ADDON_MANIFEST_ID: \"dev.nako.subtitle-lab\"",
      "      ADDON_SECRET_SUBTITLE_PROVIDER_KEY: \"secret-reference:subtitle-provider-key\"",
      "    healthcheck:",
      "      test: [\"CMD-SHELL\", \"curl -fsS http://subtitle-lab:9100/health >/dev/null\"]",
    ].join("\n"),
    notes: [
      "Run this Addon Sidecar as a separate service on a network Nako can reach.",
      "Nako does not mount the Docker socket or manage this container lifecycle.",
    ],
  },
  systemd: {
    title: "systemd sidecar unit snippet",
    filename: "dev-nako-subtitle-lab.service",
    content: [
      "[Unit]",
      "Description=Subtitle Lab Addon Sidecar",
      "After=network-online.target",
      "",
      "[Service]",
      "Type=simple",
      "Environment=\"NAKO_ADDON_BASE_URL=http://subtitle-lab:9100\"",
      "Environment=\"NAKO_ADDON_PROTOCOL_VERSION=2026-05-15\"",
      "Environment=\"NAKO_ADDON_MANIFEST_ID=dev.nako.subtitle-lab\"",
      "Environment=\"ADDON_SECRET_SUBTITLE_PROVIDER_KEY=secret-reference:subtitle-provider-key\"",
      "ExecStart=<addon-sidecar-command> --listen 0.0.0.0:9100",
      "Restart=on-failure",
    ].join("\n"),
    notes: [
      "Replace <addon-sidecar-command> with the Addon author's binary and arguments.",
      "Nako does not call systemd or supervise this process.",
    ],
  },
  secret_references: [
    {
      id: "subtitle-provider-key",
      label: "Provider API key",
      description: "Secret Reference resolved by Nako at runtime.",
      required: false,
      env_var: "ADDON_SECRET_SUBTITLE_PROVIDER_KEY",
      placeholder: "secret-reference:subtitle-provider-key",
    },
  ],
  health_check_steps: [
    {
      title: "Check the Addon Sidecar health contract directly",
      command: "curl -fsS -X POST 'http://subtitle-lab:9100/health' -H 'Content-Type: application/json'",
      expected_result: "The sidecar returns matching protocol, manifest, addon version, and resource-count facts.",
    },
    {
      title: "Check the Addon through Nako Admin API",
      command: "curl -fsS -X POST \"$NAKO_BASE_URL/admin/v1/addons/addon-subtitle-lab/health-check\" -H 'Authorization: <admin-auth-header>'",
      expected_result: "Nako returns a redaction-safe Addon Health Check status.",
    },
  ],
  registration_verification_steps: [
    {
      title: "Verify the registered Addon manifest snapshot",
      command: "curl -fsS \"$NAKO_BASE_URL/admin/v1/addons/addon-subtitle-lab\" -H 'Authorization: <admin-auth-header>'",
      expected_result: "The response summary contains manifest_id `dev.nako.subtitle-lab` and status `enabled`.",
    },
    {
      title: "Verify declared Addon surfaces",
      command: "curl -fsS \"$NAKO_BASE_URL/admin/v1/addons/addon-subtitle-lab/surfaces\" -H 'Authorization: <admin-auth-header>'",
      expected_result: "The response lists Addon surface declarations only.",
    },
  ],
  lifecycle_boundary: {
    nako_manages_containers: false,
    nako_manages_processes: false,
    nako_manages_packages: false,
    message: "Nako generates this guide only. The operator owns Addon Sidecar installation, start/stop, upgrades, logs, and removal outside Nako.",
  },
};

export const mockAddonsRouteSummary: AddonsRouteSummary = {
  addons: mockAddons.addons.map((addon) => ({
    id: addon.id,
    manifestId: addon.manifest_id,
    name: addon.name,
    version: addon.version,
    protocolVersion: addon.protocol_version,
    status: addon.status,
    grantedScopeCount: addon.granted_scopes.length,
    updatedAt: addon.updated_at,
  })),
  selectedAddon: {
    id: mockAddonDetail.addon.summary.id,
    manifestId: mockAddonDetail.addon.summary.manifest_id,
    name: mockAddonDetail.addon.summary.name,
    version: mockAddonDetail.addon.summary.version,
    protocolVersion: mockAddonDetail.addon.summary.protocol_version,
    status: mockAddonDetail.addon.summary.status,
    grantedScopeCount: mockAddonDetail.addon.summary.granted_scopes.length,
    updatedAt: mockAddonDetail.addon.summary.updated_at,
    resourceCount: mockAddonDetail.addon.manifest.resources.length,
    resourceKinds: mockAddonDetail.addon.manifest.resources.map((resource) => resource.kind),
    authMode: mockAddonDetail.addon.manifest.auth,
    grantedScopes: mockAddonDetail.addon.summary.granted_scopes,
    defaultTimeoutMs: mockAddonDetail.addon.manifest.default_timeout_ms,
    defaultMaxAttempts: mockAddonDetail.addon.manifest.default_max_attempts,
  },
  statusCounts: {
    enabled: 1,
    disabled: 1,
    unregistered: 0,
  },
  health: {
    addonId: mockAddonHealth.addon_id,
    status: mockAddonHealth.status,
    latencyMs: mockAddonHealth.latency_ms,
    protocolVersion: mockAddonHealth.protocol_version ?? null,
    addonVersion: mockAddonHealth.addon_version ?? null,
    resourceCount: mockAddonHealth.resource_count ?? null,
    safeErrorCode: mockAddonHealth.safe_error_code ?? null,
  },
  surfaceSummary: {
    entryPointCount: mockAddonSurfaces.entry_points.length,
    hostedPageCount: mockAddonSurfaces.hosted_pages.length,
    configurationSchemaDeclared: Boolean(mockAddonSurfaces.configuration_schema),
    secretReferenceFieldCount: mockAddonSurfaces.secret_reference_fields.length,
    taskCount: mockAddonSurfaces.tasks.length,
    eventSubscriptionCount: mockAddonSurfaces.event_subscriptions.length,
  },
  installBoundary: {
    nakoManagesContainers: mockAddonInstallGuide.lifecycle_boundary.nako_manages_containers,
    nakoManagesProcesses: mockAddonInstallGuide.lifecycle_boundary.nako_manages_processes,
    nakoManagesPackages: mockAddonInstallGuide.lifecycle_boundary.nako_manages_packages,
    secretReferenceCount: mockAddonInstallGuide.secret_references.length,
    healthCheckStepCount: mockAddonInstallGuide.health_check_steps.length,
    registrationVerificationStepCount:
      mockAddonInstallGuide.registration_verification_steps.length,
  },
  tokens: mockAddonTokens.tokens.map((token) => ({
    id: token.id,
    label: token.label,
    tokenPrefix: token.token_prefix,
    status: token.status,
    lastUsedAt: token.last_used_at,
  })),
  grants: mockAddonGrants.grants.map((grant) => ({
    id: grant.id,
    permission: grant.permission,
    libraryId: grant.library_id,
  })),
};

export const mockEvents: AdminOutboxEventListResponse = {
  events: [
    {
      id: "event-metadata",
      kind: "item_metadata_refreshed",
      subject: "item:item-unknown-1",
      library_id: "library-anime",
      source_id: null,
      status: "pending",
      attempts: 0,
      has_payload: true,
      has_error: false,
      occurred_at: "2026-05-19T10:00:00Z",
      updated_at: "2026-05-19T10:00:00Z",
      next_attempt_at: null,
    },
    {
      id: "event-webhook",
      kind: "library_scanned",
      subject: "library:library-films",
      library_id: "library-films",
      source_id: null,
      status: "failed",
      attempts: 3,
      has_payload: true,
      has_error: true,
      occurred_at: "2026-05-19T09:30:00Z",
      updated_at: "2026-05-19T09:45:00Z",
      next_attempt_at: "2026-05-19T10:15:00Z",
    },
  ],
  page: { limit: 20, offset: 0, returned: 2 },
};

export const mockJobs: AdminJobListResponse = {
  jobs: [
    {
      id: "job-scan",
      kind: "library_scan",
      status: "running",
      resource_class: "library",
      library_id: "library-anime",
      source_id: null,
      has_input: true,
      has_summary: false,
      has_error: false,
      queued_at: "2026-05-19T09:58:00Z",
      started_at: "2026-05-19T10:00:00Z",
      completed_at: null,
    },
    {
      id: "job-artwork",
      kind: "managed_artwork_ingest",
      status: "queued",
      resource_class: "artwork",
      library_id: null,
      source_id: "source-unknown-1",
      has_input: true,
      has_summary: false,
      has_error: false,
      queued_at: "2026-05-19T10:02:00Z",
      started_at: null,
      completed_at: null,
    },
    {
      id: "job-metadata",
      kind: "metadata_refresh",
      status: "failed",
      resource_class: "metadata",
      library_id: "library-films",
      source_id: null,
      has_input: true,
      has_summary: true,
      has_error: true,
      queued_at: "2026-05-19T08:00:00Z",
      started_at: "2026-05-19T08:01:00Z",
      completed_at: "2026-05-19T08:04:00Z",
    },
  ],
  page: { limit: 20, offset: 0, returned: 3 },
};

export const mockPlaybackSessions: AdminPlaybackSessionListResponse = {
  sessions: [
    {
      id: "session-hls",
      principal_id: "principal-admin",
      source_id: "source-hls",
      item_id: "item-hls",
      mode: "transcode",
      state: "running",
      transcode_session_id: "transcode-session-hls",
      has_client_capabilities: true,
      active: true,
      terminal: false,
      created_at: "2026-05-19T10:00:00Z",
      updated_at: "2026-05-19T10:03:00Z",
      started_at_ms: 1_769_158_801_000,
      ended_at_ms: null,
      last_heartbeat_at_ms: 1_769_158_980_000,
    },
    {
      id: "session-remux",
      principal_id: "principal-admin",
      source_id: "source-remux",
      item_id: "item-remux",
      mode: "remux",
      state: "starting",
      transcode_session_id: null,
      has_client_capabilities: true,
      active: true,
      terminal: false,
      created_at: "2026-05-19T10:04:00Z",
      updated_at: "2026-05-19T10:04:00Z",
      started_at_ms: 1_769_159_040_000,
      ended_at_ms: null,
      last_heartbeat_at_ms: null,
    },
  ],
  page: { limit: 20, offset: 0, returned: 2 },
};

export const mockPlaybackRuntime: AdminPlaybackRuntimeDiagnosticsResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  readiness: {
    status: "ready",
    reason: "ffmpeg_probe_ready",
    checks: [
      { name: "ffmpeg_probe", status: "ready", reason: "ffmpeg_probe_ready" },
      {
        name: "hardware_acceleration",
        status: "ready",
        reason: "requested_accelerator_ready",
      },
      {
        name: "selected_fallback",
        status: "ready",
        reason: "selected_acceleration_ready",
      },
      {
        name: "transcode_budget",
        status: "ready",
        reason: "transcode_budget_ready",
      },
      {
        name: "remote_playback_budget",
        status: "ready",
        reason: "remote_playback_budget_ready",
      },
      { name: "staging", status: "ready", reason: "staging_ready" },
    ],
  },
  policy: {
    effective_resolution_supported: true,
    library_access_required: true,
    permissions: [
      "media_playback",
      "direct_play",
      "remux",
      "audio_transcode",
      "video_transcode",
      "remote_playback",
      "remote_control",
      "cast",
    ],
    role_policy_merge: "restrictive",
    role_policy_rows_supported: true,
    user_policy_overrides_role_policy: true,
    user_policy_rows_supported: true,
  },
  ffmpeg: {
    probe_status: "ready",
    has_probe_error: false,
    hardware_capability_count: 4,
    available_gpu_capabilities: 1,
  },
  hardware: {
    policy: { requested: "nvenc", fallback: "cpu" },
    selection: {
      acceleration: "nvenc",
      fallback_used: false,
      reason: "nvenc is available",
    },
    capabilities: [
      {
        accelerator: "vaapi",
        available: false,
        reason_code: "encoder_not_listed",
        encoder_discovery: {
          status: "missing",
          encoder: "h264_vaapi",
          has_detail: false,
        },
        device_initialization: {
          status: "not_run",
          operator_check: "Verify the host exposes a VAAPI render device to Nako",
          has_detail: false,
        },
        smoke_probe: {
          status: "not_run",
          operator_check: "Run a VAAPI encode smoke test on the host",
          has_detail: false,
        },
      },
      {
        accelerator: "nvenc",
        available: true,
        reason_code: "available",
        encoder_discovery: {
          status: "listed",
          encoder: "h264_nvenc",
          has_detail: false,
        },
        device_initialization: {
          status: "passed",
          operator_check: "NVIDIA driver and FFmpeg can initialize NVENC",
          has_detail: false,
        },
        smoke_probe: {
          status: "passed",
          operator_check: "NVENC encode smoke test passed",
          has_detail: true,
        },
      },
      {
        accelerator: "quick_sync",
        available: false,
        reason_code: "encoder_not_listed",
        encoder_discovery: {
          status: "missing",
          encoder: "h264_qsv",
          has_detail: false,
        },
        device_initialization: {
          status: "not_run",
          operator_check: "Verify Intel Quick Sync devices are exposed to Nako",
          has_detail: false,
        },
        smoke_probe: {
          status: "not_run",
          operator_check: "Run a QuickSync encode smoke test on the host",
          has_detail: false,
        },
      },
    ],
  },
  transcode: {
    configured_cpu_slots: 2,
    configured_gpu_slots: 1,
    effective_cpu_slots: 2,
    effective_gpu_slots: 1,
    selected_hls_slots: 1,
  },
  remux: {
    max_concurrent_sessions: 2,
    timeout_ms: 30000,
  },
  resource_pressure: {
    classes: [
      {
        class: "cpu_transcode",
        enforcement: "admission_permit",
        configured_capacity: 2,
        available_permits: 1,
        in_use_permits: 1,
      },
      {
        class: "gpu_transcode",
        enforcement: "admission_permit",
        configured_capacity: 1,
        available_permits: 1,
        in_use_permits: 0,
      },
      {
        class: "hls_artifact_io",
        enforcement: "not_yet_enforced",
        configured_capacity: null,
        available_permits: null,
        in_use_permits: null,
      },
    ],
  },
  remote_playback: {
    backend_count: 2,
    stream_permits_available: 4,
    stream_permits_max: 4,
    stage_permits_available: 1,
    stage_permits_max: 2,
    state_scope: "process_local",
  },
  staging: {
    max_bytes: 10737418240,
    retention_ms: 86400000,
    cleanup_on_startup: true,
    startup_deleted_records: 4,
    startup_deleted_files: 4,
  },
  artifact_lifecycle: {
    hls_segment_cleanup_enabled: true,
    hls_segment_keep_ms: 60000,
    startup_deleted_artifacts: 0,
    startup_deleted_bytes: 0,
    startup_deleted_directories: 0,
    startup_deleted_files: 0,
    startup_examined_artifacts: 0,
    startup_skipped_security: 0,
    transcode_artifact_cleanup_on_startup: false,
    transcode_artifact_retention_ms: 86400000,
  },
  throttle: {
    delay_ms: 3000,
    enabled: false,
  },
};

export const mockPlaybackSupport: AdminPlaybackSupportEvidenceResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  subject: {
    session_id: "session-hls",
    source_id: "source-hls",
  },
  session: {
    id: "session-hls",
    source_id: "source-hls",
    kind: "hls_transcode",
    state: "failed",
    failure_category: "runner",
    has_failure_message: true,
    active: false,
    terminal: true,
    request_key_fingerprint: "sha256:00000000000000000000000000000000",
    output_artifact_kind: "hls_playlist",
    runtime_metrics: {
      frame_count: 1200,
      fps_millis: 24000,
      bitrate_kbps: 4800,
      total_size_bytes: 12345678,
      output_time_ms: 60000,
      dup_frames: 0,
      drop_frames: 0,
      speed_millis: 1000,
      progress: "end",
    },
    created_at: "2026-05-19T10:00:00Z",
    updated_at: "2026-05-19T10:03:00Z",
    started_at: "2026-05-19T10:00:01Z",
    completed_at: "2026-05-19T10:03:00Z",
  },
  source: {
    source_id: "source-hls",
    library_id: "library-anime",
    item_id: "item-hls",
    source_scheme: "webdav",
    file_name: "Episode 01.mkv",
    size_bytes: 1468006400,
    has_fingerprint: true,
  },
  runtime: {
    readiness: mockPlaybackRuntime.readiness,
    policy: mockPlaybackRuntime.policy,
    ffmpeg: mockPlaybackRuntime.ffmpeg,
    hardware: {
      policy: mockPlaybackRuntime.hardware.policy,
      selected_acceleration: mockPlaybackRuntime.hardware.selection.acceleration,
      fallback_used: mockPlaybackRuntime.hardware.selection.fallback_used,
      capability_count: mockPlaybackRuntime.hardware.capabilities.length,
      unavailable_capabilities: mockPlaybackRuntime.hardware.capabilities
        .filter((capability) => !capability.available)
        .map((capability) => ({
          accelerator: capability.accelerator,
          reason_code: capability.reason_code,
          encoder_discovery_status: capability.encoder_discovery.status,
          device_initialization_status: capability.device_initialization.status,
          smoke_probe_status: capability.smoke_probe.status,
        })),
    },
    transcode: mockPlaybackRuntime.transcode,
    remux: mockPlaybackRuntime.remux,
    remote_playback: mockPlaybackRuntime.remote_playback,
    staging: mockPlaybackRuntime.staging,
    artifact_lifecycle: mockPlaybackRuntime.artifact_lifecycle,
    throttle: mockPlaybackRuntime.throttle,
  },
  redaction: {
    paths_redacted: true,
    source_references_redacted: true,
    ffmpeg_commands_redacted: true,
    stderr_redacted: true,
    credentials_redacted: true,
  },
};

export const mockStorageStaging: AdminStorageStagingDiagnosticsResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  summary: {
    configured_max_bytes: 10737418240,
    used_manifest_bytes: 2147483648,
    pressure: {
      status: "healthy",
      used_ratio_milli: 200,
      total_records: 2,
      in_flight_records: 0,
      failed_records: 1,
      unknown_size_records: 1,
      active_leases: 1,
      ffmpeg_input_records: 2,
      probe_input_records: 0,
    },
    cleanup_on_startup: true,
    retention_ms: 86400000,
    startup_deleted_records: 4,
    startup_deleted_files: 4,
    cleanup_candidate_records: 12,
    cleanup_candidate_bytes: 3221225472,
    process_cached_backends: 2,
    vfs_cache: {
      object_count: 48,
      listing_count: 7,
      failure_count: 1,
      stale_object_count: 3,
      stale_listing_count: 1,
      last_failure_at_ms: 1779180000000,
    },
  },
  records: [
    {
      id: "staging-hls",
      source_scheme: "webdav",
      purpose: "ffmpeg_input",
      state: "ready",
      size_bytes: 1468006400,
      has_etag: true,
      has_fingerprint: true,
      active_leases: 1,
      has_validation_error: false,
      created_at_ms: 1779180000000,
      updated_at_ms: 1779180200000,
      last_accessed_at_ms: 1779180300000,
      expires_at_ms: 1779266400000,
    },
    {
      id: "staging-old",
      source_scheme: "local",
      purpose: "ffmpeg_input",
      state: "failed",
      size_bytes: null,
      has_etag: false,
      has_fingerprint: false,
      active_leases: 0,
      has_validation_error: true,
      created_at_ms: 1779170000000,
      updated_at_ms: 1779170010000,
      last_accessed_at_ms: 1779170010000,
      expires_at_ms: null,
    },
  ],
  page: { limit: 20, offset: 0, returned: 2 },
};

export const mockSystemConfig: AdminServerConfigDiagnosticsResponse = {
  admin_api_version: "v1",
  public_api_version: "v1",
  auth: {
    enabled: true,
    token_env: "NAKO_ADMIN_TOKEN",
  },
  network: {
    exposure_mode: "reverse_proxy",
    readiness: {
      status: "ready",
      reason: "ready",
      checks: [
        { name: "exposure_mode", status: "ready", reason: "ready" },
        { name: "auth", status: "ready", reason: "ready" },
        { name: "external_endpoint", status: "ready", reason: "ready" },
        { name: "trusted_proxy", status: "ready", reason: "ready" },
        { name: "origin_policy", status: "ready", reason: "ready" },
        { name: "tunnel_provider", status: "ready", reason: "ready" },
      ],
    },
    external_endpoint: {
      configured: true,
      scheme: "https",
      host_fingerprint: "sha256:11111111111111111111111111111111",
    },
    trusted_proxy: {
      headers_enabled: true,
      source_count: 2,
    },
    origins: {
      allowed_origin_count: 1,
      configured: true,
    },
    tunnel_providers: [
      {
        id: "cloudflared",
        kind: "cloudflare_tunnel",
        endpoint_configured: true,
        endpoint_scheme: "https",
        endpoint_host_fingerprint: "sha256:22222222222222222222222222222222",
        token_env: "NAKO_TUNNEL_TOKEN",
        token_present: true,
      },
    ],
  },
  database: {
    configured_backend_kind: "sqlite",
    active_backend_kind: "sqlite",
    url_scheme: "sqlite",
    runtime_supported: true,
    migrated_on_startup: true,
    capabilities: {
      lifecycle: true,
      libraries: true,
      jobs: true,
      job_leases: true,
      media: true,
      scan_commits: true,
      metadata: true,
      catalog: true,
      playback_sessions: true,
      playback_state: true,
      transcode_sessions: true,
      event_outbox: true,
      addons: true,
      automation: true,
      managed_artwork: true,
      vfs_cache: true,
      webhooks: true,
      search_index: true,
    },
  },
  runtime: {
    listen_addr: "127.0.0.1:3000",
    scan_concurrency: 2,
    probe_concurrency: 2,
    metadata_concurrency: 2,
    remux_concurrency: 1,
    webhook_concurrency: 2,
    remux_timeout_ms: 30000,
  },
  libraries: [
    {
      id: "library-anime",
      name: "Anime Vault",
      preset: "series",
      backend_kind: "local",
      root_scheme: "local",
      has_webdav_password_env: false,
      webdav_timeout_ms: null,
      webdav_max_attempts: null,
    },
    {
      id: "library-films",
      name: "Films",
      preset: "movies",
      backend_kind: "webdav",
      root_scheme: "webdav",
      has_webdav_password_env: true,
      webdav_timeout_ms: 15000,
      webdav_max_attempts: 3,
    },
  ],
  metadata: {
    raw_cache_retention_ms: 604800000,
    raw_cache_cleanup_on_startup: true,
    raw_cache_cleanup_interval_ms: 3600000,
    maintenance_policies: 2,
    providers: [
      {
        provider: "tmdb",
        enabled: true,
        token_env: null,
        api_key_env: "TMDB_API_KEY",
        has_api_base_url: true,
        has_image_base_url: true,
        language: "en-US",
        include_adult: false,
        header_count: 0,
        secret_header_count: 0,
        has_provider_runtime_override: false,
      },
    ],
    runtime: {
      timeout_ms: 10000,
      max_attempts: 3,
      min_interval_ms: 250,
      concurrency: 2,
      user_agent: "nako-admin-web-mock",
      has_proxy: false,
      circuit_breaker_failures: 5,
      circuit_breaker_backoff_ms: 30000,
    },
  },
  transcode: {
    hardware_policy: { requested: "nvenc", fallback: "cpu" },
    cpu_concurrency: 2,
    gpu_concurrency: 1,
  },
  staging: {
    max_bytes: 10737418240,
    retention_ms: 86400000,
    cleanup_on_startup: true,
  },
  playback: {
    remote_stream_concurrency: 4,
    remote_stage_concurrency: 2,
    hls_segment_cleanup_enabled: true,
    hls_segment_keep_ms: 60000,
    transcode_artifact_cleanup_on_startup: false,
    transcode_artifact_retention_ms: 86400000,
    transcode_throttle_delay_ms: 3000,
    transcode_throttle_enabled: false,
  },
  artwork: {
    artifact_root_configured: true,
    fetch_timeout_ms: 15000,
    fetch_max_attempts: 3,
    fetch_max_bytes: 10485760,
    fetch_concurrency: 2,
    ingest_worker_enabled: true,
    ingest_worker_idle_ms: 1000,
    fetch_user_agent: "nako-artwork-fetch",
    has_fetch_proxy: false,
    max_width: 4096,
    max_height: 4096,
  },
};

export const mockMetadataRawCacheSettings: AdminMetadataRawCacheSettingsResponse = {
  admin_api_version: "v1",
  retention_ms: mockSystemConfig.metadata.raw_cache_retention_ms,
  cleanup_on_startup: mockSystemConfig.metadata.raw_cache_cleanup_on_startup,
  source: "configured",
  effect: "active",
  updated_at_ms: null,
};

export function mockLibraryMetadataProfile(
  libraryId = "library-anime",
): AdminLibraryMetadataProfileResponse {
  return {
    admin_api_version: "v1",
    public_api_version: "v1",
    library_id: libraryId,
    profile: {
      item_kinds: ["series", "episode", "movie"],
      local_readers: ["nfo", "embedded"],
      metadata_providers: ["nfo", "tmdb", "bangumi"],
      image_providers: ["local", "tmdb"],
      language: "en-US",
      country: "US",
      refresh_mode: "missing_only",
      local_metadata_policy: "local_first",
      scan: {
        enabled: true,
        addon_scrape: true,
        addon_writeback: false,
      },
    },
    scan_acquisition_plan: {
      local_nfo_import: true,
      provider_refresh: true,
      addon_scrape: true,
      addon_writeback: false,
      embedded_read: true,
      sidecar_read: true,
      image_discovery: true,
    },
  };
}

export const mockSources: AdminSourceMap = {
  overview: "mock",
  addons: "mock",
  addonHealth: "mock",
  addonSurfaces: "mock",
  addonInstallGuide: "mock",
  addonTokens: "mock",
  addonGrants: "mock",
  acquisitionIntake: "mock",
  catalogGovernance: "mock",
  generatedArtifactProposals: "mock",
  events: "mock",
  jobs: "mock",
  playbackSessions: "mock",
  playbackRuntime: "mock",
  storageStaging: "mock",
  systemConfig: "mock",
};

export const mockAdminConsoleData: AdminConsoleData = {
  sources: mockSources,
  errors: {},
  overview: mockOverview,
  addons: {
    selectedAddonId: "addon-subtitle-lab",
    addons: mockAddons.addons.map((addon) => ({
      id: addon.id,
      manifestId: addon.manifest_id,
      name: addon.name,
      version: addon.version,
      protocolVersion: addon.protocol_version,
      baseUrl: addon.base_url,
      status: addon.status,
      grantedScopes: addon.granted_scopes,
      updatedAt: addon.updated_at,
    })),
    selectedAddon: {
      id: mockAddonDetail.addon.summary.id,
      manifestId: mockAddonDetail.addon.summary.manifest_id,
      name: mockAddonDetail.addon.summary.name,
      version: mockAddonDetail.addon.summary.version,
      protocolVersion: mockAddonDetail.addon.summary.protocol_version,
      baseUrl: mockAddonDetail.addon.summary.base_url,
      status: mockAddonDetail.addon.summary.status,
      grantedScopes: mockAddonDetail.addon.summary.granted_scopes,
      updatedAt: mockAddonDetail.addon.summary.updated_at,
      description: mockAddonDetail.addon.manifest.description,
      resourceCount: mockAddonDetail.addon.manifest.resources.length,
      resourceKinds: mockAddonDetail.addon.manifest.resources.map((resource) => resource.kind),
      authMode: mockAddonDetail.addon.manifest.auth,
      defaultTimeoutMs: mockAddonDetail.addon.manifest.default_timeout_ms,
      defaultMaxAttempts: mockAddonDetail.addon.manifest.default_max_attempts,
    },
    health: {
      addonId: mockAddonHealth.addon_id,
      status: mockAddonHealth.status,
      latencyMs: mockAddonHealth.latency_ms,
      protocolVersion: mockAddonHealth.protocol_version ?? null,
      addonVersion: mockAddonHealth.addon_version ?? null,
      resourceCount: mockAddonHealth.resource_count ?? null,
      safeErrorCode: mockAddonHealth.safe_error_code ?? null,
    },
    surfaces: {
      entryPoints: mockAddonSurfaces.entry_points.map((entryPoint) => ({
        id: entryPoint.id,
        label: entryPoint.label,
        kind: entryPoint.kind,
        path: entryPoint.path,
        hostedPageId: entryPoint.hosted_page_id ?? null,
      })),
      hostedPages: mockAddonSurfaces.hosted_pages.map((page) => ({
        id: page.id,
        title: page.title,
        path: page.path,
        url: page.url,
      })),
      configurationSchemaId: mockAddonSurfaces.configuration_schema?.schema_id ?? null,
      secretReferenceFieldCount: mockAddonSurfaces.secret_reference_fields.length,
      tasks: mockAddonSurfaces.tasks.map((task) => ({
        id: task.id,
        name: task.name,
        path: task.path,
      })),
      eventSubscriptions: mockAddonSurfaces.event_subscriptions.map((subscription) => ({
        id: subscription.id,
        eventKind: subscription.event_kind,
        path: subscription.path,
      })),
    },
    installGuide: {
      addonId: mockAddonInstallGuide.addon_id,
      manifestId: mockAddonInstallGuide.manifest_id,
      addonName: mockAddonInstallGuide.addon_name,
      addonVersion: mockAddonInstallGuide.addon_version,
      protocolVersion: mockAddonInstallGuide.protocol_version,
      baseUrl: mockAddonInstallGuide.base_url,
      status: mockAddonInstallGuide.status,
      dockerCompose: {
        title: mockAddonInstallGuide.docker_compose.title,
        filename: mockAddonInstallGuide.docker_compose.filename,
        content: mockAddonInstallGuide.docker_compose.content,
        notes: mockAddonInstallGuide.docker_compose.notes,
      },
      systemd: {
        title: mockAddonInstallGuide.systemd.title,
        filename: mockAddonInstallGuide.systemd.filename,
        content: mockAddonInstallGuide.systemd.content,
        notes: mockAddonInstallGuide.systemd.notes,
      },
      secretReferences: mockAddonInstallGuide.secret_references.map((secret) => ({
        id: secret.id,
        label: secret.label,
        description: secret.description ?? null,
        required: secret.required,
        envVar: secret.env_var,
        placeholder: secret.placeholder,
      })),
      healthCheckSteps: mockAddonInstallGuide.health_check_steps.map((step) => ({
        title: step.title,
        command: step.command,
        expectedResult: step.expected_result,
      })),
      registrationVerificationSteps: mockAddonInstallGuide.registration_verification_steps.map((step) => ({
        title: step.title,
        command: step.command,
        expectedResult: step.expected_result,
      })),
      lifecycleBoundary: {
        nakoManagesContainers: mockAddonInstallGuide.lifecycle_boundary.nako_manages_containers,
        nakoManagesProcesses: mockAddonInstallGuide.lifecycle_boundary.nako_manages_processes,
        nakoManagesPackages: mockAddonInstallGuide.lifecycle_boundary.nako_manages_packages,
        message: mockAddonInstallGuide.lifecycle_boundary.message,
      },
    },
    tokens: mockAddonTokens.tokens.map((token) => ({
      id: token.id,
      label: token.label,
      tokenPrefix: token.token_prefix,
      status: token.status,
      lastUsedAt: token.last_used_at,
    })),
    grants: mockAddonGrants.grants.map((grant) => ({
      id: grant.id,
      permission: grant.permission,
      libraryId: grant.library_id,
    })),
    diagnostic: {
      addonId: mockAddonDiagnostic.addon_id,
      resource: mockAddonDiagnostic.resource,
      status: mockAddonDiagnostic.status,
      latencyMs: mockAddonDiagnostic.latency_ms,
      attempts: mockAddonDiagnostic.attempts,
      httpStatus: mockAddonDiagnostic.http_status ?? null,
      safeErrorCode: mockAddonDiagnostic.safe_error_code ?? null,
    },
  },
  libraries: [
    {
      id: "library-anime",
      name: "Anime Vault",
      backendKind: "local",
      status: "ready",
      itemCount: 1248,
      lastScan: "14 min ago",
    },
    {
      id: "library-films",
      name: "Films",
      backendKind: "webdav",
      status: "ready",
      itemCount: 382,
      lastScan: "2 hr ago",
    },
    {
      id: "library-archive",
      name: "Archive",
      backendKind: "local",
      status: "degraded",
      itemCount: 91,
      lastScan: "needs review",
    },
  ],
  catalog: {
    items: mockCatalogGovernance.items.map((item) => ({
      id: item.item_id,
      libraryId: item.library_id,
      kind: item.kind,
      parentId: item.parent_id,
      title: item.title,
      releaseDate: item.release_date,
      issues: item.issues,
      sourceCount: item.source_count,
      representativeSourceId: item.representative_source_id,
      representativeFileName: item.representative_file_name,
      providerMappingCount: item.provider_mapping_count,
      acceptedProviderMappingCount: item.accepted_provider_mapping_count,
      duplicateRelationshipCount: item.duplicate_relationship_count,
      localInference: item.local_inference
        ? {
            sourceId: item.local_inference.source_id,
            inferredKind: item.local_inference.inferred_kind,
            inferredTitle: item.local_inference.inferred_title,
            inferredYear: item.local_inference.inferred_year,
            inferredSeason: item.local_inference.inferred_season,
            inferredEpisode: item.local_inference.inferred_episode,
            confidenceMilli: item.local_inference.confidence_milli,
            evidenceSource: item.local_inference.evidence_source,
            hasEvidence: item.local_inference.has_evidence,
            inferenceVersion: item.local_inference.inference_version,
          }
        : null,
    })),
    page: mockCatalogGovernance.page,
  },
  acquisitionIntake: {
    candidates: mockAcquisitionIntakeCandidates.candidates.map((candidate) => ({
      id: candidate.id,
      sourceKind: candidate.source_kind,
      sourceScheme: candidate.source_scheme ?? "unknown",
      state: candidate.state,
      sizeBytes: candidate.size_bytes,
      hasDiagnostics: candidate.has_diagnostics,
      linkedArtifactId: candidate.managed_import_artifact_id,
    })),
    page: mockAcquisitionIntakeCandidates.page,
  },
  generatedArtifactProposals: {
    proposals: mockGeneratedArtifactProposals.proposals.map((proposal) => ({
      id: proposal.id,
      capability: proposal.capability,
      kind: proposal.kind,
      status: proposal.status,
      targetKind: proposal.target.kind,
      readinessStatus: proposal.readiness.status,
      actionable: proposal.readiness.actionable,
      confidenceMilli: proposal.payload.confidence_milli,
      payloadShape: proposal.payload.shape,
      providerName: proposal.provenance.provider_name,
      promptFingerprint: proposal.provenance.prompt_fingerprint,
      payloadFingerprint: proposal.payload.payload_fingerprint,
    })),
    page: mockGeneratedArtifactProposals.page,
  },
  events: {
    events: mockEvents.events.map((event) => ({
      id: event.id,
      kind: event.kind,
      status: event.status,
      attempts: event.attempts,
      hasError: event.has_error,
    })),
    page: mockEvents.page,
  },
  jobs: mockJobs.jobs.map((job) => ({
    id: job.id,
    kind: job.kind,
    status: job.status,
    resourceClass: job.resource_class,
    hasError: job.has_error,
  })),
  playback: {
    hardwarePolicy: "Prefer NVENC, fall back to CPU",
    ffmpegStatus: mockPlaybackRuntime.ffmpeg.probe_status,
    accelerators: mockPlaybackRuntime.hardware.capabilities.map((capability) => ({
      name: capability.accelerator,
      available: capability.available,
    })),
    sessions: mockPlaybackSessions.sessions.map((session) => ({
      id: session.id,
      kind: session.mode,
      sourceTitle: session.source_id,
      state: session.state,
    })),
  },
  storage: {
    stagingUsedBytes: mockStorageStaging.summary.used_manifest_bytes,
    stagingMaxBytes: mockStorageStaging.summary.configured_max_bytes,
    vfsObjectCount: mockStorageStaging.summary.vfs_cache.object_count,
    records: mockStorageStaging.records.map((record) => ({
      id: record.id,
      sourceScheme: record.source_scheme,
      purpose: record.purpose,
      state: record.state,
      sizeBytes: record.size_bytes,
      hasValidationError: record.has_validation_error,
    })),
  },
  network: {
    exposureMode: mockSystemConfig.network.exposure_mode,
    readinessStatus: mockSystemConfig.network.readiness.status,
    readinessReason: mockSystemConfig.network.readiness.reason,
    endpointConfigured: mockSystemConfig.network.external_endpoint.configured,
    endpointScheme: mockSystemConfig.network.external_endpoint.scheme,
    trustedProxyHeaders: mockSystemConfig.network.trusted_proxy.headers_enabled,
    trustedProxySourceCount: mockSystemConfig.network.trusted_proxy.source_count,
    allowedOriginCount: mockSystemConfig.network.origins.allowed_origin_count,
    tunnelProviderCount: mockSystemConfig.network.tunnel_providers.length,
  },
  settings: [
    {
      label: "Admin auth",
      value: mockSystemConfig.auth.enabled ? "Auth configured" : "Auth disabled",
    },
    {
      label: "Network readiness",
      value: `${mockSystemConfig.network.exposure_mode} · ${mockSystemConfig.network.readiness.status}`,
    },
    { label: "FFmpeg", value: "Configured, diagnostics only" },
    {
      label: "Transcode policy",
      value: `${mockSystemConfig.transcode.gpu_concurrency} GPU slot`,
    },
    { label: "Settings edits", value: "Planned Admin API" },
  ],
};
