[package]
name = "nako-events"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
hmac.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
nako-core = { path = "../nako-core" }
time.workspace = true

[dev-dependencies]
axum.workspace = true
nako-db = { path = "../nako-db" }
tokio.workspace = true
