[package]
name = "nako-catalog"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
nako-core = { path = "../nako-core" }
nako-search = { path = "../nako-search" }

[dev-dependencies]
pollster = { workspace = true }
nako-db = { path = "../nako-db" }
tokio = { workspace = true }
