// Generated by `cargo run -p nako-api --example emit-typescript-sdk`.
// Do not edit generated output by hand.

export const NAKO_API_VERSION = "v1" as const;
export const NAKO_API_VERSION_HEADER = "x-nako-api-version" as const;

export const NAKO_PLAYBACK_SESSION_ID_HEADER = "x-nako-playback-session-id" as const;

export const NAKO_PUBLIC_PATHS = [
  "/health",
  "/auth/login",
  "/auth/invitations/redeem",
  "/auth/logout",
  "/users/me",
  "/users/me/playlists",
  "/users/me/playlists/{playlist_id}",
  "/users/me/playlists/{playlist_id}/items",
  "/users/me/playlists/{playlist_id}/items/{item_id}",
  "/users/me/playlists/{playlist_id}/items/reorder",
  "/libraries",
  "/libraries/{library_id}",
  "/libraries/{library_id}/sources",
  "/libraries/{library_id}/items",
  "/items",
  "/items/{item_id}",
  "/items/{item_id}/credits",
  "/items/{item_id}/images",
  "/images/{image_id}",
  "/people",
  "/people/{person_id}",
  "/people/{person_id}/items",
  "/tags",
  "/tags/{tag_id}/items",
  "/genres",
  "/genres/{genre_id}/items",
  "/search",
  "/management/context-links",
  "/playback/profile-presets",
  "/sources/{source_id}/probe",
  "/sources/{source_id}/playback/decision",
  "/sources/{source_id}/playback/browser-ticket",
  "/sources/{source_id}/stream",
  "/sources/{source_id}/stream/remux",
  "/sources/{source_id}/stream/hls/playlist.m3u8",
  "/sources/{source_id}/subtitles/{stream_index}",
  "/playback/sessions/{session_id}",
  "/playback/sessions/{session_id}/cancel",
  "/playback/sessions/{session_id}/heartbeat",
  "/playback/sessions/{session_id}/hls/segments/{segment_name}",
  "/renderers",
  "/renderers/{renderer_session_id}/heartbeat",
  "/renderers/{renderer_session_id}/commands/next",
  "/renderers/{renderer_session_id}/commands/play",
  "/renderers/{renderer_session_id}/commands/{command_id}/complete",
  "/users/me/playback-profile",
  "/users/me/playback-state/items/{item_id}",
  "/users/me/playback-state/continue-watching",
  "/users/me/playback-state/items/{item_id}/progress",
  "/users/me/playback-state/items/{item_id}/watched",
] as const;

export interface AddUserPlaylistItemRequest {
  expected_version?: number;
  position?: number;
}

export interface BrowserPlaybackCapabilitiesDto {
  audio_codec?: Array<string>;
  container?: Array<string>;
  device_family?: string;
  direct_play?: boolean;
  hls_segment_container?: ClientHlsSegmentContainer;
  hls_variant_policy?: ClientHlsVariantPolicy;
  max_audio_channels?: number;
  max_height?: number;
  max_video_bitrate?: number;
  max_width?: number;
  output_container?: "mp4" | "mkv";
  profile_version?: number;
  supports_hdr?: boolean;
  supports_subtitles?: boolean;
  video_codec?: Array<string>;
}

export interface BrowserPlaybackTicketRequest {
  capabilities?: BrowserPlaybackCapabilitiesDto;
  mode: "direct" | "remux" | "hls" | "subtitle";
  subtitle_stream_index?: number;
}

export interface BrowserPlaybackTicketResponse {
  expires_at: string;
  item_id?: string | null;
  mode: "direct" | "remux" | "hls" | "subtitle";
  playback_session_id: string | null;
  source_id: string;
  urls: Array<BrowserPlaybackUrlDto>;
}

export interface BrowserPlaybackUrlDto {
  content_type: string;
  kind: "stream" | "playlist" | "subtitle";
  supports_range_requests: boolean;
  url: string;
}

export interface CanonicalMetadataDto {
  collections: Array<CollectionRefDto>;
  credits: Array<CreditDto>;
  external_ids: Array<ExternalIdDto>;
  genres: Array<string>;
  original_title: string | null;
  overview: string | null;
  ratings: Array<ContentRatingDto>;
  release_date: string | null;
  runtime_minutes: number | null;
  sort_title: string | null;
  studios: Array<StudioRefDto>;
  tagline: string | null;
  tags: Array<string>;
  title: string;
}

export type ClientBrowseSortKey = "title" | "release_date" | "date_added" | "last_played";

export interface ClientDirectPlayPlan {
  content_type: string;
  source_id: string;
  supports_range_requests: boolean;
}

export type ClientHlsSegmentContainer = "mpeg_ts" | "fmp4";

export type ClientHlsVariantPolicy = "single_variant" | "adaptive";

export type ClientMediaKind = "movie" | "series" | "season" | "episode" | "collection" | "extra" | "unknown";

export interface ClientPlaybackCapabilitiesDto {
  audio_codecs: Array<string>;
  containers: Array<string>;
  device_family?: string;
  direct_play: boolean;
  hls_segment_container?: ClientHlsSegmentContainer;
  hls_variant_policy?: ClientHlsVariantPolicy;
  max_audio_channels?: number;
  max_height?: number;
  max_video_bitrate?: number;
  max_width?: number;
  profile_version?: number;
  supports_hdr?: boolean;
  supports_subtitles?: boolean;
  video_codecs: Array<string>;
}

export interface ClientPlaybackCapabilityEvaluation {
  reason_details?: Array<ClientPlaybackCompatibilityConditionDetail>;
  reasons: Array<ClientPlaybackCompatibilityCondition>;
  supported: boolean;
}

export type ClientPlaybackCompatibilityCondition = "compatible" | "direct_play_disabled" | "media_technical_facts_missing" | "container_unknown" | "container_unsupported" | "remux_container_unsupported" | "video_codec_unsupported" | "audio_codec_unsupported" | "video_bitrate_unsupported" | "video_resolution_unsupported" | "video_hdr_unsupported" | "audio_channels_unsupported" | "subtitle_delivery_unsupported" | "requested_transcode_output" | "transcode_profile_unsupported" | "policy_denied";

export interface ClientPlaybackCompatibilityConditionDetail {
  condition: ClientPlaybackCompatibilityCondition;
  detail: string;
  summary: string;
}

export interface ClientPlaybackDecision {
  denial: ClientPlaybackDenialDto | null;
  direct_play: ClientDirectPlayPlan | null;
  mode: "direct_play" | "remux" | "transcode" | "denied";
  reason: ClientPlaybackDecisionReason;
  report: ClientPlaybackDecisionReport;
  transcode_plan: ClientTranscodePlan | null;
}

export type ClientPlaybackDecisionReason = "compatible" | "requested_transcode_output" | "client_disabled_direct_play" | "source_container_unknown" | "client_container_unsupported" | "source_codecs_unsupported" | "policy_denied";

export interface ClientPlaybackDecisionReport {
  denial?: ClientPlaybackDenialDto | null;
  direct_play: ClientPlaybackCapabilityEvaluation;
  remux: ClientPlaybackCapabilityEvaluation;
  selected_mode: "direct_play" | "remux" | "transcode" | "denied";
  selection_reason_details?: Array<ClientPlaybackCompatibilityConditionDetail>;
  selection_reasons?: Array<ClientPlaybackCompatibilityCondition>;
  transcode: ClientPlaybackCapabilityEvaluation;
}

export interface ClientPlaybackDenialDto {
  permission: ClientPlaybackPermission;
  reason: ClientPlaybackPermissionDecisionReason;
}

export type ClientPlaybackPermission = "media_playback" | "direct_play" | "remux" | "audio_transcode" | "video_transcode" | "remote_playback" | "remote_control" | "cast";

export type ClientPlaybackPermissionDecisionReason = "allowed" | "library_access_does_not_allow_play" | "media_playback_disabled" | "direct_play_disabled" | "remux_disabled" | "audio_transcode_disabled" | "video_transcode_disabled" | "remote_playback_disabled" | "remote_control_disabled" | "cast_disabled";

export type ClientPlaybackProfileFamily = "browser_chromium" | "browser_firefox" | "browser_safari" | "android_media3" | "desktop_native" | "tv_webos" | "tv_tizen" | "chromecast" | "dlna_renderer";

export interface ClientPlaybackTargetDto {
  control_capabilities: ClientRendererControlCapabilitiesDto;
  kind: ClientPlaybackTargetKind;
  media_capabilities: ClientPlaybackCapabilitiesDto;
  network_scope: ClientPlaybackTargetNetworkScope;
  transport_auth: ClientPlaybackTargetTransportAuth;
}

export type ClientPlaybackTargetKind = "browser" | "native_desktop" | "native_mobile" | "nako_remote_client" | "chromecast" | "dlna_renderer" | "airplay";

export type ClientPlaybackTargetNetworkScope = "local" | "remote" | "unknown";

export type ClientPlaybackTargetTransportAuth = "bearer" | "browser_ticket" | "cast_ticket" | "none";

export type ClientRendererCommandState = "queued" | "delivered" | "acknowledged" | "failed" | "cancelled";

export interface ClientRendererControlCapabilitiesDto {
  commands: Array<ClientRendererControlCommand>;
}

export type ClientRendererControlCommand = "show_item" | "play" | "pause" | "resume" | "seek" | "stop" | "set_volume";

export type ClientRendererSessionState = "online" | "offline" | "revoked";

export type ClientSortOrder = "asc" | "desc";

export interface ClientTranscodePlan {
  audio_codec: string | null;
  output_container: "hls" | "mp4" | "mkv";
  video_codec: string | null;
}

export type ClientWatchStateFilter = "any" | "watched" | "unwatched" | "in_progress";

export interface CollectionItemDto {
  collection_id: string;
  item_id: string;
  sort_order: number | null;
}

export interface CollectionRefDto {
  external_ids: Array<ExternalIdDto>;
  name: string;
  overview: string | null;
  sort_order: number | null;
}

export interface ContentRatingDto {
  source: string;
  value: string;
}

export interface ContinueWatchingItemDto {
  images: Array<PublicImageRefDto>;
  item: MediaItemDto;
  state: UserPlaybackStateDto;
}

export interface ContinueWatchingResponse {
  items: Array<ContinueWatchingItemDto>;
  page: PageInfo;
}

export interface CreateUserPlaylistRequest {
  name: string;
}

export interface CreditDto {
  character: string | null;
  external_ids: Array<ExternalIdDto>;
  name: string;
  order: number | null;
  role: string;
}

export interface CurrentUserDto {
  bootstrap: boolean;
  display_name: string;
  id: string;
  roles: Array<"administrator" | "library_manager" | "viewer">;
  username: string;
}

export interface CurrentUserResponse {
  user: CurrentUserDto;
}

export interface DeleteUserPlaybackProfilePreferenceResponse {
  deleted: boolean;
}

export interface ErrorResponse {
  code: "invalid_input" | "not_found" | "conflict" | "unsupported" | "unauthorized" | "forbidden" | "provider_error" | "storage_error" | "ffmpeg_error" | "staging_budget_exhausted" | "staging_validation_mismatch" | "storage_timeout" | "storage_unauthorized" | "storage_rate_limited" | "database_error";
  message: string;
}

export interface ExternalIdDto {
  provider: string;
  value: string;
}

export interface GenreDto {
  id: string;
  name: string;
  source: string;
}

export interface GenreItemsResponse {
  genre: GenreDto;
  items: Array<MediaItemDto>;
  page: PageInfo;
}

export interface GenreListResponse {
  genres: Array<GenreDto>;
  page: PageInfo;
}

export interface HealthResponse {
  status: string;
  version: "v1";
}

export interface ImagesResponse {
  images: Array<PublicImageRefDto>;
  item_id: string;
}

export interface ItemCreditDto {
  character: string | null;
  item_id: string;
  person_id: string;
  role: string;
  sort_order: number | null;
}

export interface ItemCreditsResponse {
  credits: Array<ItemCreditDto>;
  item_id: string;
  people: Array<PersonDto>;
}

export interface ItemDetailResponse {
  collections: Array<CollectionItemDto>;
  credits: Array<ItemCreditDto>;
  genres: Array<ItemGenreDto>;
  images: Array<PublicImageRefDto>;
  item: MediaItemDto;
  sources: Array<MediaSourceDto>;
  studios: Array<ItemStudioDto>;
  tags: Array<ItemTagDto>;
}

export interface ItemGenreDto {
  genre_id: string;
  item_id: string;
}

export interface ItemStudioDto {
  item_id: string;
  studio_id: string;
}

export interface ItemTagDto {
  item_id: string;
  tag_id: string;
}

export interface ItemsResponse {
  items: Array<MediaItemDto>;
  page: PageInfo;
}

export interface LibraryDto {
  id: string;
  name: string;
  options: LibraryOptionsDto;
  roots: Array<string>;
}

export interface LibraryItemsResponse {
  items: Array<MediaItemDto>;
  library: LibraryDto;
  page: PageInfo;
}

export interface LibraryListResponse {
  libraries: Array<LibraryDto>;
  page: PageInfo;
}

export interface LibraryOptionsDto {
  domain: "video" | "audio" | "image" | "document" | "mixed" | "online";
  metadata_profile: MetadataProfileDto;
  naming_strategy: "movie" | "series" | "anime" | "music" | "podcast" | "photo" | "home_video" | "mixed" | "online_catalog";
  preset: "movies" | "tv" | "anime" | "music" | "podcast" | "photos" | "home_video" | "mixed_video" | "online_catalog" | "custom";
  scan: LibraryScanOptionsDto;
}

export interface LibraryResponse {
  library: LibraryDto;
}

export interface LibraryScanOptionsDto {
  max_depth: number | null;
  realtime_monitor: boolean;
}

export interface LibrarySourceResponse {
  item: MediaItemDto | null;
  probe: MediaProbeDto | null;
  source: MediaSourceDto;
}

export interface LibrarySourcesResponse {
  library: LibraryDto;
  page: PageInfo;
  sources: Array<LibrarySourceResponse>;
}

export interface LoginRequest {
  password: string;
  username: string;
}

export interface LoginResponse {
  account: CurrentUserResponse;
  session: UserSessionDto;
}

export interface LogoutResponse {
  revoked: boolean;
}

export interface ManagementContextDto {
  item_id: string | null;
  library_id: string | null;
  playback_session_id: string | null;
  source_id: string | null;
}

export interface ManagementContextLinkDto {
  action: "scan_library" | "update_library_metadata_profile" | "refresh_item_metadata" | "view_jobs" | "view_playback_diagnostics" | "view_playback_runtime" | "manage_library_access";
  disabled_reason: "missing_context" | "insufficient_permission" | null;
  enabled: boolean;
  method: "GET" | "POST" | "PUT" | "DELETE";
  required_access: "library_manage" | "administrator";
  route_name: string;
  surface: "management" | "media";
  target: ManagementContextDto;
}

export interface ManagementContextLinksResponse {
  context: ManagementContextDto;
  links: Array<ManagementContextLinkDto>;
}

export interface MediaItemDto {
  id: string;
  kind: ClientMediaKind;
  metadata: CanonicalMetadataDto;
  parent_id: string | null;
}

export interface MediaProbeDto {
  bit_rate: number | null;
  container: string | null;
  duration_ms: number | null;
  streams: Array<MediaStreamDto>;
}

export interface MediaSourceDto {
  file_name: string;
  fingerprint: string | null;
  id: string;
  item_id: string;
  library_id: string;
  size_bytes: number | null;
}

export interface MediaStreamDispositionDto {
  attached_pic: boolean;
  captions: boolean;
  commentary: boolean;
  default: boolean;
  descriptions: boolean;
  forced: boolean;
  hearing_impaired: boolean;
  visual_impaired: boolean;
}

export interface MediaStreamDto {
  bit_rate: number | null;
  channels: number | null;
  codec: string | null;
  disposition: MediaStreamDispositionDto;
  duration_ms: number | null;
  height: number | null;
  index: number;
  kind: string;
  language: string | null;
  origin: string | null;
  sample_rate: number | null;
  width: number | null;
}

export interface MetadataProfileDto {
  country: string | null;
  image_providers: Array<string>;
  item_kinds: Array<ClientMediaKind>;
  language: string | null;
  local_metadata_policy: "disabled" | "read_only" | "local_first" | "remote_first" | "write_sidecar";
  local_readers: Array<string>;
  metadata_providers: Array<string>;
  refresh_mode: "none" | "validation_only" | "default" | "missing_only" | "full_refresh";
  scan: MetadataScanPolicyDto;
}

export interface MetadataScanPolicyDto {
  addon_scrape: boolean;
  addon_writeback: boolean;
  enabled: boolean;
}

export interface PageInfo {
  limit: number;
  offset: number;
  returned: number;
}

export interface PeopleResponse {
  page: PageInfo;
  people: Array<PersonDto>;
}

export interface PersonDto {
  external_ids: Array<ExternalIdDto>;
  id: string;
  name: string;
  overview: string | null;
  sort_name: string | null;
}

export interface PersonItemsResponse {
  items: Array<MediaItemDto>;
  page: PageInfo;
  person: PersonDto;
}

export interface PersonResponse {
  person: PersonDto;
}

export interface PlaybackDecisionResponse {
  decision: ClientPlaybackDecision;
  probe: MediaProbeDto | null;
  source: MediaSourceDto;
  target: ClientPlaybackTargetDto;
}

export interface PlaybackProfilePresetDto {
  audio_codecs: Array<string>;
  containers: Array<string>;
  device_family: string;
  direct_play: boolean;
  family: ClientPlaybackProfileFamily;
  hls_segment_container: ClientHlsSegmentContainer;
  hls_variant_policy: ClientHlsVariantPolicy;
  max_audio_channels?: number;
  max_height?: number;
  max_video_bitrate?: number;
  max_width?: number;
  profile_version: number;
  supports_hdr: boolean;
  supports_subtitles: boolean;
  video_codecs: Array<string>;
}

export interface PlaybackProfilePresetsResponse {
  presets: Array<PlaybackProfilePresetDto>;
}

export interface PlaybackSessionDto {
  client_capabilities?: ClientPlaybackCapabilitiesDto | null;
  duration_ms?: number | null;
  ended_at?: string | null;
  id: string;
  item_id: string;
  last_heartbeat_at?: string | null;
  mode: "direct" | "remux" | "hls";
  position_ms?: number | null;
  source_id: string;
  started_at?: string | null;
  state: "active" | "paused" | "cancel_requested" | "cancelled" | "ended" | "failed";
  transcode_session_id?: string | null;
  updated_at: string;
}

export interface PlaybackSessionHeartbeatRequest {
  duration_ms?: number | null;
  position_ms?: number | null;
  state: "active" | "paused" | "cancel_requested" | "cancelled" | "ended" | "failed";
}

export interface PlaybackSessionResponse {
  session: PlaybackSessionDto;
}

export interface PublicImageRefDto {
  etag: string | null;
  height: number | null;
  id: string;
  kind: string;
  language: string | null;
  media_type: string | null;
  owner: Record<string, unknown>;
  url: string;
  width: number | null;
}

export interface RedeemInvitationRequest {
  display_name: string;
  password: string;
  token: string;
  username: string;
}

export interface RendererCommandCompletionRequest {
  failure_message?: string | null;
  state: ClientRendererCommandState;
}

export interface RendererCommandDto {
  command: ClientRendererControlCommand;
  created_at: string;
  id: string;
  item_id?: string | null;
  playback_session_id?: string | null;
  position_ms?: number | null;
  renderer_session_id: string;
  source_id?: string | null;
  state: ClientRendererCommandState;
  transport?: RendererCommandTransportDto | null;
  updated_at: string;
  volume_percent?: number | null;
}

export interface RendererCommandPollResponse {
  command: RendererCommandDto | null;
}

export interface RendererCommandResponse {
  command: RendererCommandDto;
}

export interface RendererCommandTransportDto {
  expires_at: string;
  mode: RendererTransportMode;
  urls: Array<RendererCommandTransportUrlDto>;
}

export interface RendererCommandTransportUrlDto {
  content_type: string;
  kind: RendererTransportUrlKind;
  supports_range_requests: boolean;
  url: string;
}

export interface RendererHeartbeatRequest {
  control_capabilities?: ClientRendererControlCapabilitiesDto | null;
  media_capabilities?: ClientPlaybackCapabilitiesDto | null;
  state: ClientRendererSessionState;
  ttl_ms?: number | null;
}

export interface RendererPlayCommandRequest {
  position_ms?: number | null;
  source_id: string;
}

export interface RendererPlayCommandResponse {
  command: RendererCommandDto;
  session: PlaybackSessionDto;
}

export interface RendererRegistrationRequest {
  control_capabilities: ClientRendererControlCapabilitiesDto;
  display_name: string;
  media_capabilities?: ClientPlaybackCapabilitiesDto | null;
  network_scope: ClientPlaybackTargetNetworkScope;
  target_kind: ClientPlaybackTargetKind;
  transport_auth: ClientPlaybackTargetTransportAuth;
  ttl_ms?: number | null;
}

export interface RendererSessionDto {
  active_playback_session_id?: string | null;
  control_capabilities: ClientRendererControlCapabilitiesDto;
  display_name: string;
  expires_at?: string | null;
  id: string;
  last_seen_at?: string | null;
  media_capabilities?: ClientPlaybackCapabilitiesDto | null;
  network_scope: ClientPlaybackTargetNetworkScope;
  state: ClientRendererSessionState;
  target_kind: ClientPlaybackTargetKind;
  transport_auth: ClientPlaybackTargetTransportAuth;
  updated_at: string;
}

export interface RendererSessionResponse {
  renderer: RendererSessionDto;
}

export interface RendererSessionsResponse {
  page: PageInfo;
  renderers: Array<RendererSessionDto>;
}

export type RendererTransportMode = "direct" | "remux" | "hls";

export type RendererTransportUrlKind = "stream" | "playlist" | "segment_base";

export interface ReorderUserPlaylistItemsRequest {
  expected_version?: number;
  item_ids: Array<string>;
}

export interface SearchItemHit {
  item: MediaItemDto;
  score: number;
}

export interface SearchResponse {
  hits: Array<SearchItemHit>;
  page: PageInfo;
}

export interface SetUserPlaybackProfilePreferenceRequest {
  audio_codecs?: Array<string> | null;
  containers?: Array<string> | null;
  device_family?: string | null;
  direct_play?: boolean;
  hls_segment_container?: ClientHlsSegmentContainer;
  hls_variant_policy?: ClientHlsVariantPolicy;
  max_audio_channels?: number | null;
  max_height?: number | null;
  max_video_bitrate?: number | null;
  max_width?: number | null;
  profile_version?: number | null;
  supports_hdr?: boolean;
  supports_subtitles?: boolean;
  video_codecs?: Array<string> | null;
}

export interface SetWatchedStateRequest {
  duration_ms?: number | null;
  marked_at?: string | null;
  position_ms?: number | null;
  source_id?: string | null;
  watched: boolean;
}

export interface SourceProbeResponse {
  probe: MediaProbeDto;
  source_id: string;
}

export interface StudioRefDto {
  external_ids: Array<ExternalIdDto>;
  name: string;
}

export interface TagDto {
  id: string;
  name: string;
  source: string;
}

export interface TagItemsResponse {
  items: Array<MediaItemDto>;
  page: PageInfo;
  tag: TagDto;
}

export interface TagsResponse {
  page: PageInfo;
  tags: Array<TagDto>;
}

export interface TranscodeSessionDto {
  completed_at: string | null;
  created_at: string;
  failure_category: "invalid_request" | "runner" | "timeout" | "storage" | "stale" | "cancelled" | "unknown" | null;
  failure_message: string | null;
  id: string;
  kind: "remux" | "hls_transcode";
  request_key: string;
  source_id: string;
  started_at: string | null;
  state: "planned" | "starting" | "running" | "cancel_requested" | "cancelled" | "failed" | "finished";
  updated_at: string;
}

export interface TranscodeSessionResponse {
  session: TranscodeSessionDto;
}

export interface UpdatePlaybackProgressRequest {
  duration_ms?: number | null;
  position_ms: number;
  reported_at?: string | null;
  source_id?: string | null;
}

export interface UpdateUserPlaylistRequest {
  expected_version?: number;
  name: string;
}

export interface UserPlaybackProfilePreferenceDto {
  capabilities: ClientPlaybackCapabilitiesDto;
  updated_at: string;
  version: number;
}

export interface UserPlaybackProfilePreferenceResponse {
  preference: UserPlaybackProfilePreferenceDto | null;
}

export interface UserPlaybackStateDto {
  duration_ms: number | null;
  item_id: string;
  last_played_at: string | null;
  progress_percent: number | null;
  resume_position_ms: number | null;
  source_id: string | null;
  updated_at: string | null;
  version: number;
  watched: boolean;
  watched_at: string | null;
}

export interface UserPlaybackStateResponse {
  state: UserPlaybackStateDto;
}

export interface UserPlaylistDeleteResponse {
  deleted: boolean;
  playlist_id: string;
}

export interface UserPlaylistDto {
  created_at: string;
  id: string;
  item_count: number;
  name: string;
  updated_at: string;
  version: number;
  visibility: "private";
}

export interface UserPlaylistItemDto {
  added_at: string;
  images: Array<PublicImageRefDto>;
  item: MediaItemDto;
  item_id: string;
  playlist_id: string;
  position: number;
}

export interface UserPlaylistItemsResponse {
  items: Array<UserPlaylistItemDto>;
  page: PageInfo;
  playlist: UserPlaylistDto;
}

export interface UserPlaylistResponse {
  playlist: UserPlaylistDto;
}

export interface UserPlaylistsResponse {
  page: PageInfo;
  playlists: Array<UserPlaylistDto>;
}

export interface UserSessionDto {
  expires_at_ms: number;
  token: string;
}

export interface PageQuery {
  limit?: number;
  offset?: number;
}

export interface PlaybackCapabilitiesQuery {
  direct_play?: boolean;
  device_family?: string;
  profile_version?: number;
  container?: string | string[];
  video_codec?: string | string[];
  audio_codec?: string | string[];
  max_video_bitrate?: number;
  max_width?: number;
  max_height?: number;
  max_audio_channels?: number;
  supports_hdr?: boolean;
  supports_subtitles?: boolean;
  hls_variant_policy?: "single_variant" | "adaptive";
  hls_segment_container?: "mpeg_ts" | "fmp4";
}

export interface RemuxPlaybackQuery extends PlaybackCapabilitiesQuery {
  output_container?: "mp4" | "mkv";
}

export interface HlsPlaybackQuery extends PlaybackCapabilitiesQuery {
  preferred_audio_language?: string | string[];
  preferred_subtitle_language?: string | string[];
  start_position_ms?: number;
}

export interface ImageVariantQuery {
  width?: number;
  height?: number;
}

export interface LibraryItemsQuery extends PageQuery {
  sort?: ClientBrowseSortKey;
  order?: ClientSortOrder;
  facet?: string | string[];
  watch_state?: ClientWatchStateFilter;
}

export interface ManagementContextQuery {
  library_id?: string;
  item_id?: string;
  source_id?: string;
  playback_session_id?: string;
}

export interface NakoClientOptions {
  baseUrl: string;
  bearerToken?: string;
  fetch?: FetchLike;
}

export type FetchLike = (input: string, init?: RequestInit) => Promise<Response>;

export class NakoApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly body: ErrorResponse;

  constructor(status: number, body: ErrorResponse) {
    super(body.message);
    this.name = "NakoApiError";
    this.status = status;
    this.code = body.code;
    this.body = body;
  }
}

export class NakoClient {
  private readonly baseUrl: string;
  private readonly bearerToken: string | undefined;
  private readonly fetchImpl: FetchLike;

  constructor(options: NakoClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/+$/, "");
    this.bearerToken = options.bearerToken;
    this.fetchImpl = options.fetch ?? globalThis.fetch.bind(globalThis);
  }

  health(): Promise<HealthResponse> {
    return this.requestJson("GET", "/health", { auth: false });
  }

  login(body: LoginRequest): Promise<LoginResponse> {
    return this.requestJson("POST", "/auth/login", { auth: false, body });
  }

  redeemInvitation(body: RedeemInvitationRequest): Promise<LoginResponse> {
    return this.requestJson("POST", "/auth/invitations/redeem", { auth: false, body });
  }

  logout(): Promise<LogoutResponse> {
    return this.requestJson("POST", "/auth/logout");
  }

  currentUser(): Promise<CurrentUserResponse> {
    return this.requestJson("GET", "/users/me");
  }

  listUserPlaylists(page?: PageQuery): Promise<UserPlaylistsResponse> {
    return this.requestJson("GET", "/users/me/playlists", { query: page });
  }

  createUserPlaylist(body: CreateUserPlaylistRequest): Promise<UserPlaylistResponse> {
    return this.requestJson("POST", "/users/me/playlists", { body });
  }

  getUserPlaylist(playlistId: string): Promise<UserPlaylistResponse> {
    return this.requestJson("GET", `/users/me/playlists/${encodeURIComponent(playlistId)}`);
  }

  updateUserPlaylist(playlistId: string, body: UpdateUserPlaylistRequest): Promise<UserPlaylistResponse> {
    return this.requestJson("PATCH", `/users/me/playlists/${encodeURIComponent(playlistId)}`, { body });
  }

  deleteUserPlaylist(playlistId: string): Promise<UserPlaylistDeleteResponse> {
    return this.requestJson("DELETE", `/users/me/playlists/${encodeURIComponent(playlistId)}`);
  }

  listUserPlaylistItems(playlistId: string, page?: PageQuery): Promise<UserPlaylistItemsResponse> {
    return this.requestJson("GET", `/users/me/playlists/${encodeURIComponent(playlistId)}/items`, { query: page });
  }

  addUserPlaylistItem(playlistId: string, itemId: string, body: AddUserPlaylistItemRequest = {}): Promise<UserPlaylistResponse> {
    return this.requestJson("PUT", `/users/me/playlists/${encodeURIComponent(playlistId)}/items/${encodeURIComponent(itemId)}`, { body });
  }

  removeUserPlaylistItem(playlistId: string, itemId: string): Promise<UserPlaylistResponse> {
    return this.requestJson("DELETE", `/users/me/playlists/${encodeURIComponent(playlistId)}/items/${encodeURIComponent(itemId)}`);
  }

  reorderUserPlaylistItems(playlistId: string, body: ReorderUserPlaylistItemsRequest): Promise<UserPlaylistResponse> {
    return this.requestJson("PUT", `/users/me/playlists/${encodeURIComponent(playlistId)}/items/reorder`, { body });
  }

  listLibraries(page?: PageQuery): Promise<LibraryListResponse> {
    return this.requestJson("GET", "/libraries", { query: page });
  }

  getLibrary(libraryId: string): Promise<LibraryResponse> {
    return this.requestJson("GET", `/libraries/${encodeURIComponent(libraryId)}`);
  }

  listLibrarySources(libraryId: string, page?: PageQuery): Promise<LibrarySourcesResponse> {
    return this.requestJson("GET", `/libraries/${encodeURIComponent(libraryId)}/sources`, { query: page });
  }

  listLibraryItems(libraryId: string, query?: LibraryItemsQuery): Promise<LibraryItemsResponse> {
    return this.requestJson("GET", `/libraries/${encodeURIComponent(libraryId)}/items`, { query });
  }

  listItems(page?: PageQuery): Promise<ItemsResponse> {
    return this.requestJson("GET", "/items", { query: page });
  }

  getItem(itemId: string): Promise<ItemDetailResponse> {
    return this.requestJson("GET", `/items/${encodeURIComponent(itemId)}`);
  }

  listItemCredits(itemId: string): Promise<ItemCreditsResponse> {
    return this.requestJson("GET", `/items/${encodeURIComponent(itemId)}/credits`);
  }

  listItemImages(itemId: string): Promise<ImagesResponse> {
    return this.requestJson("GET", `/items/${encodeURIComponent(itemId)}/images`);
  }

  image(imageId: string, variant?: ImageVariantQuery): Promise<Response> {
    return this.requestRaw("GET", `/images/${encodeURIComponent(imageId)}`, { query: variant });
  }

  headImage(imageId: string, variant?: ImageVariantQuery): Promise<Response> {
    return this.requestRaw("HEAD", `/images/${encodeURIComponent(imageId)}`, { query: variant });
  }

  listPeople(page?: PageQuery): Promise<PeopleResponse> {
    return this.requestJson("GET", "/people", { query: page });
  }

  getPerson(personId: string): Promise<PersonResponse> {
    return this.requestJson("GET", `/people/${encodeURIComponent(personId)}`);
  }

  listPersonItems(personId: string, page?: PageQuery): Promise<PersonItemsResponse> {
    return this.requestJson("GET", `/people/${encodeURIComponent(personId)}/items`, { query: page });
  }

  listTags(page?: PageQuery): Promise<TagsResponse> {
    return this.requestJson("GET", "/tags", { query: page });
  }

  listTagItems(tagId: string, page?: PageQuery): Promise<TagItemsResponse> {
    return this.requestJson("GET", `/tags/${encodeURIComponent(tagId)}/items`, { query: page });
  }

  listGenres(page?: PageQuery): Promise<GenreListResponse> {
    return this.requestJson("GET", "/genres", { query: page });
  }

  listGenreItems(genreId: string, page?: PageQuery): Promise<GenreItemsResponse> {
    return this.requestJson("GET", `/genres/${encodeURIComponent(genreId)}/items`, { query: page });
  }

  searchItems(params: { q?: string; facet?: string | string[] } & PageQuery): Promise<SearchResponse> {
    return this.requestJson("GET", "/search", { query: params });
  }

  managementContextLinks(query?: ManagementContextQuery): Promise<ManagementContextLinksResponse> {
    return this.requestJson("GET", "/management/context-links", { query });
  }

  playbackProfilePresets(): Promise<PlaybackProfilePresetsResponse> {
    return this.requestJson("GET", "/playback/profile-presets");
  }

  getSourceProbe(sourceId: string): Promise<SourceProbeResponse> {
    return this.requestJson("GET", `/sources/${encodeURIComponent(sourceId)}/probe`);
  }

  getPlaybackDecision(sourceId: string, capabilities?: PlaybackCapabilitiesQuery): Promise<PlaybackDecisionResponse> {
    return this.requestJson("GET", `/sources/${encodeURIComponent(sourceId)}/playback/decision`, { query: capabilities });
  }

  createBrowserPlaybackTicket(sourceId: string, body: BrowserPlaybackTicketRequest): Promise<BrowserPlaybackTicketResponse> {
    return this.requestJson("POST", `/sources/${encodeURIComponent(sourceId)}/playback/browser-ticket`, { body });
  }

  streamSource(sourceId: string, range?: string): Promise<Response> {
    return this.requestRaw("GET", `/sources/${encodeURIComponent(sourceId)}/stream`, { range });
  }

  headStreamSource(sourceId: string, range?: string): Promise<Response> {
    return this.requestRaw("HEAD", `/sources/${encodeURIComponent(sourceId)}/stream`, { range });
  }

  remuxStreamSource(sourceId: string, query?: RemuxPlaybackQuery, range?: string): Promise<Response> {
    return this.requestRaw("GET", `/sources/${encodeURIComponent(sourceId)}/stream/remux`, { query, range });
  }

  headRemuxStreamSource(sourceId: string, query?: RemuxPlaybackQuery): Promise<Response> {
    return this.requestRaw("HEAD", `/sources/${encodeURIComponent(sourceId)}/stream/remux`, { query });
  }

  hlsPlaylist(sourceId: string, query?: HlsPlaybackQuery): Promise<string> {
    return this.requestText("GET", `/sources/${encodeURIComponent(sourceId)}/stream/hls/playlist.m3u8`, { query });
  }

  getSourceSubtitle(sourceId: string, streamIndex: number): Promise<string> {
    return this.requestText("GET", `/sources/${encodeURIComponent(sourceId)}/subtitles/${encodeURIComponent(String(streamIndex))}`);
  }

  getPlaybackSession(sessionId: string): Promise<PlaybackSessionResponse> {
    return this.requestJson("GET", `/playback/sessions/${encodeURIComponent(sessionId)}`);
  }

  cancelPlaybackSession(sessionId: string): Promise<PlaybackSessionResponse> {
    return this.requestJson("POST", `/playback/sessions/${encodeURIComponent(sessionId)}/cancel`);
  }

  heartbeatPlaybackSession(sessionId: string, body: PlaybackSessionHeartbeatRequest): Promise<PlaybackSessionResponse> {
    return this.requestJson("POST", `/playback/sessions/${encodeURIComponent(sessionId)}/heartbeat`, { body });
  }

  hlsSegment(sessionId: string, segmentName: string): Promise<Response> {
    return this.requestRaw("GET", `/playback/sessions/${encodeURIComponent(sessionId)}/hls/segments/${encodeURIComponent(segmentName)}`);
  }

  listRenderers(page?: PageQuery): Promise<RendererSessionsResponse> {
    return this.requestJson("GET", "/renderers", { query: page });
  }

  registerRenderer(body: RendererRegistrationRequest): Promise<RendererSessionResponse> {
    return this.requestJson("POST", "/renderers", { body });
  }

  heartbeatRenderer(rendererSessionId: string, body: RendererHeartbeatRequest): Promise<RendererSessionResponse> {
    return this.requestJson("POST", `/renderers/${encodeURIComponent(rendererSessionId)}/heartbeat`, { body });
  }

  pollNextRendererCommand(rendererSessionId: string): Promise<RendererCommandPollResponse> {
    return this.requestJson("POST", `/renderers/${encodeURIComponent(rendererSessionId)}/commands/next`);
  }

  playOnRenderer(rendererSessionId: string, body: RendererPlayCommandRequest): Promise<RendererPlayCommandResponse> {
    return this.requestJson("POST", `/renderers/${encodeURIComponent(rendererSessionId)}/commands/play`, { body });
  }

  completeRendererCommand(rendererSessionId: string, commandId: string, body: RendererCommandCompletionRequest): Promise<RendererCommandResponse> {
    return this.requestJson("POST", `/renderers/${encodeURIComponent(rendererSessionId)}/commands/${encodeURIComponent(commandId)}/complete`, { body });
  }

  getUserPlaybackState(itemId: string): Promise<UserPlaybackStateResponse> {
    return this.requestJson("GET", `/users/me/playback-state/items/${encodeURIComponent(itemId)}`);
  }

  getUserPlaybackProfilePreference(): Promise<UserPlaybackProfilePreferenceResponse> {
    return this.requestJson("GET", "/users/me/playback-profile");
  }

  setUserPlaybackProfilePreference(body: SetUserPlaybackProfilePreferenceRequest): Promise<UserPlaybackProfilePreferenceResponse> {
    return this.requestJson("PUT", "/users/me/playback-profile", { body });
  }

  deleteUserPlaybackProfilePreference(): Promise<DeleteUserPlaybackProfilePreferenceResponse> {
    return this.requestJson("DELETE", "/users/me/playback-profile");
  }

  listContinueWatching(page?: PageQuery): Promise<ContinueWatchingResponse> {
    return this.requestJson("GET", "/users/me/playback-state/continue-watching", { query: page });
  }

  updateUserPlaybackProgress(itemId: string, body: UpdatePlaybackProgressRequest): Promise<UserPlaybackStateResponse> {
    return this.requestJson("PUT", `/users/me/playback-state/items/${encodeURIComponent(itemId)}/progress`, { body });
  }

  setUserWatchedState(itemId: string, body: SetWatchedStateRequest): Promise<UserPlaybackStateResponse> {
    return this.requestJson("PUT", `/users/me/playback-state/items/${encodeURIComponent(itemId)}/watched`, { body });
  }

  private async requestJson<T>(method: string, path: string, options: RequestOptions = {}): Promise<T> {
    const response = await this.request(method, path, options);
    await this.ensureOk(response);
    this.checkApiVersion(response);
    return await response.json() as T;
  }

  private async requestText(method: string, path: string, options: RequestOptions = {}): Promise<string> {
    const response = await this.request(method, path, options);
    await this.ensureOk(response);
    this.checkApiVersion(response);
    return await response.text();
  }

  private async requestRaw(method: string, path: string, options: RequestOptions = {}): Promise<Response> {
    const response = await this.request(method, path, options);
    await this.ensureOk(response);
    this.checkApiVersion(response);
    return response;
  }

  private request(method: string, path: string, options: RequestOptions): Promise<Response> {
    const headers = new Headers(options.headers);
    if (options.auth !== false && this.bearerToken) {
      headers.set("Authorization", `Bearer ${this.bearerToken}`);
    }
    if (options.range) {
      headers.set("Range", options.range);
    }
    const init: RequestInit = {
      method,
      headers,
    };
    if (options.body !== undefined) {
      headers.set("Content-Type", "application/json");
      init.body = JSON.stringify(options.body);
    }
    return this.fetchImpl(this.url(path, options.query), init);
  }

  private url(path: string, query?: QueryInput): string {
    const url = new URL(`${this.baseUrl}${path}`);
    for (const [key, value] of Object.entries(query ?? {})) {
      if (value === undefined || value === null) {
        continue;
      }
      const rendered = Array.isArray(value) ? value.join(",") : String(value);
      url.searchParams.set(key, rendered);
    }
    return url.toString();
  }

  private async ensureOk(response: Response): Promise<void> {
    if (response.ok) {
      return;
    }

    let body: ErrorResponse | undefined;
    const text = await response.text();
    if (text.length > 0) {
      try {
        body = JSON.parse(text) as ErrorResponse;
      } catch {
        body = undefined;
      }
    }

    throw new NakoApiError(response.status, body ?? {
      code: "invalid_input",
      message: response.statusText || `HTTP ${response.status}`,
    });
  }

  private checkApiVersion(response: Response): void {
    const version = response.headers.get(NAKO_API_VERSION_HEADER);
    if (version !== null && version !== NAKO_API_VERSION) {
      throw new NakoApiError(response.status, {
        code: "unsupported",
        message: `unsupported Nako API version: ${version}`,
      });
    }
  }
}

interface RequestOptions {
  auth?: boolean | undefined;
  body?: unknown | undefined;
  headers?: HeadersInit | undefined;
  query?: QueryInput | undefined;
  range?: string | undefined;
}

type QueryInput = object;
