// Generated by `cargo run -p nako-api --example emit-typescript-sdk`.
// Do not edit generated output by hand.

export const NAKO_API_VERSION = "v1" as const;
export const NAKO_API_VERSION_HEADER = "x-nako-api-version" as const;

export const NAKO_PLAYBACK_SESSION_ID_HEADER = "x-nako-playback-session-id" as const;

export const NAKO_PUBLIC_PATHS = [
  "/health",
  "/libraries",
  "/libraries/{library_id}",
  "/libraries/{library_id}/sources",
  "/items",
  "/items/{item_id}",
  "/items/{item_id}/credits",
  "/items/{item_id}/images",
  "/images/{image_id}",
  "/people",
  "/people/{person_id}",
  "/people/{person_id}/items",
  "/tags",
  "/tags/{tag_id}/items",
  "/genres",
  "/genres/{genre_id}/items",
  "/search",
  "/sources/{source_id}/probe",
  "/sources/{source_id}/playback/decision",
  "/sources/{source_id}/stream",
  "/sources/{source_id}/stream/remux",
  "/sources/{source_id}/stream/hls/playlist.m3u8",
  "/playback/sessions/{session_id}",
  "/playback/sessions/{session_id}/cancel",
  "/playback/sessions/{session_id}/hls/segments/{segment_name}",
  "/users/me/playback-state/items/{item_id}",
  "/users/me/playback-state/continue-watching",
  "/users/me/playback-state/items/{item_id}/progress",
  "/users/me/playback-state/items/{item_id}/watched",
] as const;

export interface CanonicalMetadataDto {
  collections: Array<CollectionRefDto>;
  credits: Array<CreditDto>;
  external_ids: Array<ExternalIdDto>;
  genres: Array<string>;
  original_title: string | null;
  overview: string | null;
  ratings: Array<ContentRatingDto>;
  release_date: string | null;
  runtime_minutes: number | null;
  sort_title: string | null;
  studios: Array<StudioRefDto>;
  tagline: string | null;
  tags: Array<string>;
  title: string;
}

export interface ClientDirectPlayPlan {
  content_type: string;
  source_id: string;
  supports_range_requests: boolean;
}

export type ClientMediaKind = "movie" | "series" | "season" | "episode" | "collection" | "extra" | "unknown";

export interface ClientPlaybackDecision {
  direct_play: ClientDirectPlayPlan | null;
  mode: "direct_play" | "remux" | "transcode";
  reason: string;
  transcode_plan: ClientTranscodePlan | null;
}

export interface ClientTranscodePlan {
  audio_codec: string | null;
  hardware_acceleration: "none" | "vaapi" | "nvenc" | "quick_sync";
  output_container: "hls" | "mp4" | "mkv";
  video_codec: string | null;
}

export interface CollectionItemDto {
  collection_id: string;
  item_id: string;
  sort_order: number | null;
}

export interface CollectionRefDto {
  external_ids: Array<ExternalIdDto>;
  name: string;
  overview: string | null;
  sort_order: number | null;
}

export interface ContentRatingDto {
  source: string;
  value: string;
}

export interface ContinueWatchingItemDto {
  images: Array<PublicImageRefDto>;
  item: MediaItemDto;
  state: UserPlaybackStateDto;
}

export interface ContinueWatchingResponse {
  items: Array<ContinueWatchingItemDto>;
  page: PageInfo;
}

export interface CreditDto {
  character: string | null;
  external_ids: Array<ExternalIdDto>;
  name: string;
  order: number | null;
  role: string;
}

export interface ErrorResponse {
  code: "invalid_input" | "not_found" | "conflict" | "unsupported" | "unauthorized" | "forbidden" | "provider_error" | "storage_error" | "ffmpeg_error" | "staging_budget_exhausted" | "staging_validation_mismatch" | "storage_timeout" | "storage_unauthorized" | "storage_rate_limited" | "database_error";
  message: string;
}

export interface ExternalIdDto {
  provider: string;
  value: string;
}

export interface GenreDto {
  id: string;
  name: string;
  source: string;
}

export interface GenreItemsResponse {
  genre: GenreDto;
  items: Array<MediaItemDto>;
  page: PageInfo;
}

export interface GenreListResponse {
  genres: Array<GenreDto>;
  page: PageInfo;
}

export interface HealthResponse {
  status: string;
  version: "v1";
}

export interface ImagesResponse {
  images: Array<PublicImageRefDto>;
  item_id: string;
}

export interface ItemCreditDto {
  character: string | null;
  item_id: string;
  person_id: string;
  role: string;
  sort_order: number | null;
}

export interface ItemCreditsResponse {
  credits: Array<ItemCreditDto>;
  item_id: string;
  people: Array<PersonDto>;
}

export interface ItemDetailResponse {
  collections: Array<CollectionItemDto>;
  credits: Array<ItemCreditDto>;
  genres: Array<ItemGenreDto>;
  images: Array<PublicImageRefDto>;
  item: MediaItemDto;
  sources: Array<MediaSourceDto>;
  studios: Array<ItemStudioDto>;
  tags: Array<ItemTagDto>;
}

export interface ItemGenreDto {
  genre_id: string;
  item_id: string;
}

export interface ItemStudioDto {
  item_id: string;
  studio_id: string;
}

export interface ItemTagDto {
  item_id: string;
  tag_id: string;
}

export interface ItemsResponse {
  items: Array<MediaItemDto>;
  page: PageInfo;
}

export interface LibraryDto {
  id: string;
  name: string;
  options: LibraryOptionsDto;
  roots: Array<string>;
}

export interface LibraryListResponse {
  libraries: Array<LibraryDto>;
  page: PageInfo;
}

export interface LibraryOptionsDto {
  domain: "video" | "audio" | "image" | "document" | "mixed" | "online";
  metadata_profile: MetadataProfileDto;
  naming_strategy: "movie" | "series" | "anime" | "music" | "podcast" | "photo" | "home_video" | "mixed" | "online_catalog";
  preset: "movies" | "tv" | "anime" | "music" | "podcast" | "photos" | "home_video" | "mixed_video" | "online_catalog" | "custom";
  scan: LibraryScanOptionsDto;
}

export interface LibraryResponse {
  library: LibraryDto;
}

export interface LibraryScanOptionsDto {
  max_depth: number | null;
  realtime_monitor: boolean;
}

export interface LibrarySourceResponse {
  item: MediaItemDto | null;
  probe: MediaProbeDto | null;
  source: MediaSourceDto;
}

export interface LibrarySourcesResponse {
  library: LibraryDto;
  page: PageInfo;
  sources: Array<LibrarySourceResponse>;
}

export interface MediaItemDto {
  id: string;
  kind: ClientMediaKind;
  metadata: CanonicalMetadataDto;
  parent_id: string | null;
}

export interface MediaProbeDto {
  bit_rate: number | null;
  container: string | null;
  duration_ms: number | null;
  streams: Array<MediaStreamDto>;
}

export interface MediaSourceDto {
  file_name: string;
  fingerprint: string | null;
  id: string;
  item_id: string;
  library_id: string;
  size_bytes: number | null;
}

export interface MediaStreamDto {
  bit_rate: number | null;
  channels: number | null;
  codec: string | null;
  duration_ms: number | null;
  height: number | null;
  index: number;
  kind: string;
  language: string | null;
  sample_rate: number | null;
  width: number | null;
}

export interface MetadataProfileDto {
  country: string | null;
  image_providers: Array<string>;
  item_kinds: Array<ClientMediaKind>;
  language: string | null;
  local_metadata_policy: "disabled" | "read_only" | "local_first" | "remote_first" | "write_sidecar";
  local_readers: Array<string>;
  metadata_providers: Array<string>;
  refresh_mode: "none" | "validation_only" | "default" | "missing_only" | "full_refresh";
  scan: MetadataScanPolicyDto;
}

export interface MetadataScanPolicyDto {
  addon_scrape: boolean;
  enabled: boolean;
}

export interface PageInfo {
  limit: number;
  offset: number;
  returned: number;
}

export interface PeopleResponse {
  page: PageInfo;
  people: Array<PersonDto>;
}

export interface PersonDto {
  external_ids: Array<ExternalIdDto>;
  id: string;
  name: string;
  overview: string | null;
  sort_name: string | null;
}

export interface PersonItemsResponse {
  items: Array<MediaItemDto>;
  page: PageInfo;
  person: PersonDto;
}

export interface PersonResponse {
  person: PersonDto;
}

export interface PlaybackDecisionResponse {
  decision: ClientPlaybackDecision;
  probe: MediaProbeDto | null;
  source: MediaSourceDto;
}

export interface PublicImageRefDto {
  etag: string | null;
  height: number | null;
  id: string;
  kind: string;
  language: string | null;
  media_type: string | null;
  owner: Record<string, unknown>;
  url: string;
  width: number | null;
}

export interface SearchItemHit {
  item: MediaItemDto;
  score: number;
}

export interface SearchResponse {
  hits: Array<SearchItemHit>;
  page: PageInfo;
}

export interface SetWatchedStateRequest {
  duration_ms?: number | null;
  marked_at?: string | null;
  position_ms?: number | null;
  source_id?: string | null;
  watched: boolean;
}

export interface SourceProbeResponse {
  probe: MediaProbeDto;
  source_id: string;
}

export interface StudioRefDto {
  external_ids: Array<ExternalIdDto>;
  name: string;
}

export interface TagDto {
  id: string;
  name: string;
  source: string;
}

export interface TagItemsResponse {
  items: Array<MediaItemDto>;
  page: PageInfo;
  tag: TagDto;
}

export interface TagsResponse {
  page: PageInfo;
  tags: Array<TagDto>;
}

export interface TranscodeSessionDto {
  completed_at: string | null;
  created_at: string;
  failure_category: "invalid_request" | "runner" | "timeout" | "storage" | "stale" | "cancelled" | "unknown" | null;
  failure_message: string | null;
  id: string;
  kind: "remux" | "hls_transcode";
  request_key: string;
  source_id: string;
  started_at: string | null;
  state: "planned" | "starting" | "running" | "cancel_requested" | "cancelled" | "failed" | "finished";
  updated_at: string;
}

export interface TranscodeSessionResponse {
  session: TranscodeSessionDto;
}

export interface UpdatePlaybackProgressRequest {
  duration_ms?: number | null;
  position_ms: number;
  reported_at?: string | null;
  source_id?: string | null;
}

export interface UserPlaybackStateDto {
  duration_ms: number | null;
  item_id: string;
  last_played_at: string | null;
  progress_percent: number | null;
  resume_position_ms: number | null;
  source_id: string | null;
  updated_at: string | null;
  version: number;
  watched: boolean;
  watched_at: string | null;
}

export interface UserPlaybackStateResponse {
  state: UserPlaybackStateDto;
}

export interface PageQuery {
  limit?: number;
  offset?: number;
}

export interface PlaybackCapabilitiesQuery {
  direct_play?: boolean;
  container?: string | string[];
  video_codec?: string | string[];
  audio_codec?: string | string[];
}

export interface RemuxPlaybackQuery extends PlaybackCapabilitiesQuery {
  output_container?: "mp4" | "mkv";
}

export interface ImageVariantQuery {
  width?: number;
  height?: number;
}

export interface NakoClientOptions {
  baseUrl: string;
  bearerToken?: string;
  fetch?: FetchLike;
}

export type FetchLike = (input: string, init?: RequestInit) => Promise<Response>;

export class NakoApiError extends Error {
  readonly status: number;
  readonly code: string;
  readonly body: ErrorResponse;

  constructor(status: number, body: ErrorResponse) {
    super(body.message);
    this.name = "NakoApiError";
    this.status = status;
    this.code = body.code;
    this.body = body;
  }
}

export class NakoClient {
  private readonly baseUrl: string;
  private readonly bearerToken: string | undefined;
  private readonly fetchImpl: FetchLike;

  constructor(options: NakoClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/+$/, "");
    this.bearerToken = options.bearerToken;
    this.fetchImpl = options.fetch ?? globalThis.fetch.bind(globalThis);
  }

  health(): Promise<HealthResponse> {
    return this.requestJson("GET", "/health", { auth: false });
  }

  listLibraries(page?: PageQuery): Promise<LibraryListResponse> {
    return this.requestJson("GET", "/libraries", { query: page });
  }

  getLibrary(libraryId: string): Promise<LibraryResponse> {
    return this.requestJson("GET", `/libraries/${encodeURIComponent(libraryId)}`);
  }

  listLibrarySources(libraryId: string, page?: PageQuery): Promise<LibrarySourcesResponse> {
    return this.requestJson("GET", `/libraries/${encodeURIComponent(libraryId)}/sources`, { query: page });
  }

  listItems(page?: PageQuery): Promise<ItemsResponse> {
    return this.requestJson("GET", "/items", { query: page });
  }

  getItem(itemId: string): Promise<ItemDetailResponse> {
    return this.requestJson("GET", `/items/${encodeURIComponent(itemId)}`);
  }

  listItemCredits(itemId: string): Promise<ItemCreditsResponse> {
    return this.requestJson("GET", `/items/${encodeURIComponent(itemId)}/credits`);
  }

  listItemImages(itemId: string): Promise<ImagesResponse> {
    return this.requestJson("GET", `/items/${encodeURIComponent(itemId)}/images`);
  }

  image(imageId: string, variant?: ImageVariantQuery): Promise<Response> {
    return this.requestRaw("GET", `/images/${encodeURIComponent(imageId)}`, { query: variant });
  }

  headImage(imageId: string, variant?: ImageVariantQuery): Promise<Response> {
    return this.requestRaw("HEAD", `/images/${encodeURIComponent(imageId)}`, { query: variant });
  }

  listPeople(page?: PageQuery): Promise<PeopleResponse> {
    return this.requestJson("GET", "/people", { query: page });
  }

  getPerson(personId: string): Promise<PersonResponse> {
    return this.requestJson("GET", `/people/${encodeURIComponent(personId)}`);
  }

  listPersonItems(personId: string, page?: PageQuery): Promise<PersonItemsResponse> {
    return this.requestJson("GET", `/people/${encodeURIComponent(personId)}/items`, { query: page });
  }

  listTags(page?: PageQuery): Promise<TagsResponse> {
    return this.requestJson("GET", "/tags", { query: page });
  }

  listTagItems(tagId: string, page?: PageQuery): Promise<TagItemsResponse> {
    return this.requestJson("GET", `/tags/${encodeURIComponent(tagId)}/items`, { query: page });
  }

  listGenres(page?: PageQuery): Promise<GenreListResponse> {
    return this.requestJson("GET", "/genres", { query: page });
  }

  listGenreItems(genreId: string, page?: PageQuery): Promise<GenreItemsResponse> {
    return this.requestJson("GET", `/genres/${encodeURIComponent(genreId)}/items`, { query: page });
  }

  searchItems(params: { q?: string; facet?: string | string[] } & PageQuery): Promise<SearchResponse> {
    return this.requestJson("GET", "/search", { query: params });
  }

  getSourceProbe(sourceId: string): Promise<SourceProbeResponse> {
    return this.requestJson("GET", `/sources/${encodeURIComponent(sourceId)}/probe`);
  }

  getPlaybackDecision(sourceId: string, capabilities?: PlaybackCapabilitiesQuery): Promise<PlaybackDecisionResponse> {
    return this.requestJson("GET", `/sources/${encodeURIComponent(sourceId)}/playback/decision`, { query: capabilities });
  }

  streamSource(sourceId: string, range?: string): Promise<Response> {
    return this.requestRaw("GET", `/sources/${encodeURIComponent(sourceId)}/stream`, { range });
  }

  headStreamSource(sourceId: string, range?: string): Promise<Response> {
    return this.requestRaw("HEAD", `/sources/${encodeURIComponent(sourceId)}/stream`, { range });
  }

  remuxStreamSource(sourceId: string, query?: RemuxPlaybackQuery, range?: string): Promise<Response> {
    return this.requestRaw("GET", `/sources/${encodeURIComponent(sourceId)}/stream/remux`, { query, range });
  }

  headRemuxStreamSource(sourceId: string, query?: RemuxPlaybackQuery): Promise<Response> {
    return this.requestRaw("HEAD", `/sources/${encodeURIComponent(sourceId)}/stream/remux`, { query });
  }

  hlsPlaylist(sourceId: string, capabilities?: PlaybackCapabilitiesQuery): Promise<string> {
    return this.requestText("GET", `/sources/${encodeURIComponent(sourceId)}/stream/hls/playlist.m3u8`, { query: capabilities });
  }

  getPlaybackSession(sessionId: string): Promise<TranscodeSessionResponse> {
    return this.requestJson("GET", `/playback/sessions/${encodeURIComponent(sessionId)}`);
  }

  cancelPlaybackSession(sessionId: string): Promise<TranscodeSessionResponse> {
    return this.requestJson("POST", `/playback/sessions/${encodeURIComponent(sessionId)}/cancel`);
  }

  hlsSegment(sessionId: string, segmentName: string): Promise<Response> {
    return this.requestRaw("GET", `/playback/sessions/${encodeURIComponent(sessionId)}/hls/segments/${encodeURIComponent(segmentName)}`);
  }

  getUserPlaybackState(itemId: string): Promise<UserPlaybackStateResponse> {
    return this.requestJson("GET", `/users/me/playback-state/items/${encodeURIComponent(itemId)}`);
  }

  listContinueWatching(page?: PageQuery): Promise<ContinueWatchingResponse> {
    return this.requestJson("GET", "/users/me/playback-state/continue-watching", { query: page });
  }

  updateUserPlaybackProgress(itemId: string, body: UpdatePlaybackProgressRequest): Promise<UserPlaybackStateResponse> {
    return this.requestJson("PUT", `/users/me/playback-state/items/${encodeURIComponent(itemId)}/progress`, { body });
  }

  setUserWatchedState(itemId: string, body: SetWatchedStateRequest): Promise<UserPlaybackStateResponse> {
    return this.requestJson("PUT", `/users/me/playback-state/items/${encodeURIComponent(itemId)}/watched`, { body });
  }

  private async requestJson<T>(method: string, path: string, options: RequestOptions = {}): Promise<T> {
    const response = await this.request(method, path, options);
    await this.ensureOk(response);
    this.checkApiVersion(response);
    return await response.json() as T;
  }

  private async requestText(method: string, path: string, options: RequestOptions = {}): Promise<string> {
    const response = await this.request(method, path, options);
    await this.ensureOk(response);
    this.checkApiVersion(response);
    return await response.text();
  }

  private async requestRaw(method: string, path: string, options: RequestOptions = {}): Promise<Response> {
    const response = await this.request(method, path, options);
    await this.ensureOk(response);
    this.checkApiVersion(response);
    return response;
  }

  private request(method: string, path: string, options: RequestOptions): Promise<Response> {
    const headers = new Headers(options.headers);
    if (options.auth !== false && this.bearerToken) {
      headers.set("Authorization", `Bearer ${this.bearerToken}`);
    }
    if (options.range) {
      headers.set("Range", options.range);
    }
    const init: RequestInit = {
      method,
      headers,
    };
    if (options.body !== undefined) {
      headers.set("Content-Type", "application/json");
      init.body = JSON.stringify(options.body);
    }
    return this.fetchImpl(this.url(path, options.query), init);
  }

  private url(path: string, query?: QueryInput): string {
    const url = new URL(`${this.baseUrl}${path}`);
    for (const [key, value] of Object.entries(query ?? {})) {
      if (value === undefined || value === null) {
        continue;
      }
      const rendered = Array.isArray(value) ? value.join(",") : String(value);
      url.searchParams.set(key, rendered);
    }
    return url.toString();
  }

  private async ensureOk(response: Response): Promise<void> {
    if (response.ok) {
      return;
    }

    let body: ErrorResponse | undefined;
    const text = await response.text();
    if (text.length > 0) {
      try {
        body = JSON.parse(text) as ErrorResponse;
      } catch {
        body = undefined;
      }
    }

    throw new NakoApiError(response.status, body ?? {
      code: "invalid_input",
      message: response.statusText || `HTTP ${response.status}`,
    });
  }

  private checkApiVersion(response: Response): void {
    const version = response.headers.get(NAKO_API_VERSION_HEADER);
    if (version !== null && version !== NAKO_API_VERSION) {
      throw new NakoApiError(response.status, {
        code: "unsupported",
        message: `unsupported Nako API version: ${version}`,
      });
    }
  }
}

interface RequestOptions {
  auth?: boolean | undefined;
  body?: unknown | undefined;
  headers?: HeadersInit | undefined;
  query?: QueryInput | undefined;
  range?: string | undefined;
}

type QueryInput = object;
