[package]
name = "taru-nfo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
roxmltree.workspace = true
serde.workspace = true
taru-catalog = { path = "../taru-catalog" }
taru-core = { path = "../taru-core" }
taru-search = { path = "../taru-search" }
taru-vfs = { path = "../taru-vfs" }

[dev-dependencies]
taru-db = { path = "../taru-db" }
tempfile.workspace = true
tokio.workspace = true
