// Generated by `cargo run -p taru-api --example emit-kotlin-sdk`.
// Do not edit generated output by hand.

@file:Suppress("unused")

package dev.taru.sdk

import java.net.URLEncoder
import java.nio.charset.StandardCharsets
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

public const val TARU_API_VERSION: String = "v1"
public const val TARU_API_VERSION_HEADER: String = "x-taru-api-version"
public const val TARU_PLAYBACK_SESSION_ID_HEADER: String = "x-taru-playback-session-id"

public val TARU_PUBLIC_PATHS: List<String> = listOf(
    "/health",
    "/libraries",
    "/libraries/{library_id}",
    "/libraries/{library_id}/sources",
    "/items",
    "/items/{item_id}",
    "/items/{item_id}/credits",
    "/items/{item_id}/images",
    "/images/{image_id}",
    "/people",
    "/people/{person_id}",
    "/people/{person_id}/items",
    "/tags",
    "/tags/{tag_id}/items",
    "/genres",
    "/genres/{genre_id}/items",
    "/search",
    "/sources/{source_id}/probe",
    "/sources/{source_id}/playback/decision",
    "/sources/{source_id}/stream",
    "/sources/{source_id}/stream/remux",
    "/sources/{source_id}/stream/hls/playlist.m3u8",
    "/playback/sessions/{session_id}",
    "/playback/sessions/{session_id}/cancel",
    "/playback/sessions/{session_id}/hls/segments/{segment_name}",
    "/users/me/playback-state/items/{item_id}",
    "/users/me/playback-state/continue-watching",
    "/users/me/playback-state/items/{item_id}/progress",
    "/users/me/playback-state/items/{item_id}/watched",
)

public data class TaruRequestDescriptor(
    public val method: String,
    public val pathAndQuery: String,
    public val authRequired: Boolean = true,
)

public data class PageQuery(
    public val limit: Int? = null,
    public val offset: Long? = null,
)

public data class ImageVariantQuery(
    public val width: Int? = null,
    public val height: Int? = null,
)

public data class PlaybackCapabilitiesQuery(
    public val directPlay: Boolean? = null,
    public val containers: List<String> = emptyList(),
    public val videoCodecs: List<String> = emptyList(),
    public val audioCodecs: List<String> = emptyList(),
)

public enum class RemuxOutputContainer(
    public val wireValue: String,
) {
    Mp4("mp4"),
    Mkv("mkv"),
}

public data class RemuxPlaybackQuery(
    public val directPlay: Boolean? = null,
    public val containers: List<String> = emptyList(),
    public val videoCodecs: List<String> = emptyList(),
    public val audioCodecs: List<String> = emptyList(),
    public val outputContainer: RemuxOutputContainer? = null,
)

public object TaruPublicClientRequests {
    public fun health(): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = "/health",
            authRequired = false,
        )

    public fun listLibraries(page: PageQuery = PageQuery()): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery("/libraries", pageQuery(page)),
        )

    public fun getLibrary(libraryId: String): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = "/libraries/${encodePathSegment(libraryId)}",
        )

    public fun listLibrarySources(
        libraryId: String,
        page: PageQuery = PageQuery(),
    ): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/libraries/${encodePathSegment(libraryId)}/sources",
                pageQuery(page),
            ),
        )

    public fun listItems(page: PageQuery = PageQuery()): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery("/items", pageQuery(page)),
        )

    public fun getItem(itemId: String): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = "/items/${encodePathSegment(itemId)}",
        )

    public fun listItemImages(itemId: String): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = "/items/${encodePathSegment(itemId)}/images",
        )

    public fun image(
        imageId: String,
        variant: ImageVariantQuery = ImageVariantQuery(),
    ): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/images/${encodePathSegment(imageId)}",
                imageVariantQuery(variant),
            ),
        )

    public fun headImage(
        imageId: String,
        variant: ImageVariantQuery = ImageVariantQuery(),
    ): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "HEAD",
            pathAndQuery = pathWithQuery(
                "/images/${encodePathSegment(imageId)}",
                imageVariantQuery(variant),
            ),
        )

    public fun getPerson(personId: String): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = "/people/${encodePathSegment(personId)}",
        )

    public fun listPersonItems(
        personId: String,
        page: PageQuery = PageQuery(),
    ): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/people/${encodePathSegment(personId)}/items",
                pageQuery(page),
            ),
        )

    public fun listGenres(page: PageQuery = PageQuery()): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery("/genres", pageQuery(page)),
        )

    public fun listGenreItems(
        genreId: String,
        page: PageQuery = PageQuery(),
    ): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/genres/${encodePathSegment(genreId)}/items",
                pageQuery(page),
            ),
        )

    public fun listTags(page: PageQuery = PageQuery()): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery("/tags", pageQuery(page)),
        )

    public fun listTagItems(
        tagId: String,
        page: PageQuery = PageQuery(),
    ): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/tags/${encodePathSegment(tagId)}/items",
                pageQuery(page),
            ),
        )

    public fun searchItems(
        query: String? = null,
        facets: List<String> = emptyList(),
        page: PageQuery = PageQuery(),
    ): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/search",
                buildList {
                    if (!query.isNullOrBlank()) {
                        add("q" to query)
                    }
                    if (facets.isNotEmpty()) {
                        add("facet" to facets.joinToString(","))
                    }
                    addAll(pageQuery(page))
                },
            ),
        )

    public fun getSourceProbe(sourceId: String): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = "/sources/${encodePathSegment(sourceId)}/probe",
        )

    public fun getSourcePlaybackDecision(
        sourceId: String,
        capabilities: PlaybackCapabilitiesQuery = PlaybackCapabilitiesQuery(),
    ): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/sources/${encodePathSegment(sourceId)}/playback/decision",
                playbackCapabilitiesQuery(capabilities),
            ),
        )

    public fun streamSource(sourceId: String): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = "/sources/${encodePathSegment(sourceId)}/stream",
        )

    public fun headStreamSource(sourceId: String): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "HEAD",
            pathAndQuery = "/sources/${encodePathSegment(sourceId)}/stream",
        )

    public fun remuxStreamSource(
        sourceId: String,
        query: RemuxPlaybackQuery = RemuxPlaybackQuery(),
    ): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/sources/${encodePathSegment(sourceId)}/stream/remux",
                remuxPlaybackQuery(query),
            ),
        )

    public fun headRemuxStreamSource(
        sourceId: String,
        query: RemuxPlaybackQuery = RemuxPlaybackQuery(),
    ): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "HEAD",
            pathAndQuery = pathWithQuery(
                "/sources/${encodePathSegment(sourceId)}/stream/remux",
                remuxPlaybackQuery(query),
            ),
        )

    public fun hlsPlaylistSource(
        sourceId: String,
        capabilities: PlaybackCapabilitiesQuery = PlaybackCapabilitiesQuery(),
    ): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery(
                "/sources/${encodePathSegment(sourceId)}/stream/hls/playlist.m3u8",
                playbackCapabilitiesQuery(capabilities),
            ),
        )

    public fun getPlaybackSession(sessionId: String): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = "/playback/sessions/${encodePathSegment(sessionId)}",
        )

    public fun cancelPlaybackSession(sessionId: String): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "POST",
            pathAndQuery = "/playback/sessions/${encodePathSegment(sessionId)}/cancel",
        )

    public fun hlsSegment(
        sessionId: String,
        segmentName: String,
    ): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = "/playback/sessions/${encodePathSegment(sessionId)}/hls/segments/${
                encodePathSegment(segmentName)
            }",
        )

    public fun getUserPlaybackState(itemId: String): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = "/users/me/playback-state/items/${encodePathSegment(itemId)}",
        )

    public fun listContinueWatching(page: PageQuery = PageQuery()): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "GET",
            pathAndQuery = pathWithQuery("/users/me/playback-state/continue-watching", pageQuery(page)),
        )

    public fun updateUserPlaybackProgress(itemId: String): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "PUT",
            pathAndQuery = "/users/me/playback-state/items/${encodePathSegment(itemId)}/progress",
        )

    public fun setUserWatchedState(itemId: String): TaruRequestDescriptor =
        TaruRequestDescriptor(
            method = "PUT",
            pathAndQuery = "/users/me/playback-state/items/${encodePathSegment(itemId)}/watched",
        )

    public fun pathWithQuery(
        path: String,
        query: Iterable<Pair<String, String>>,
    ): String {
        val rendered = queryString(query)
        return if (rendered.isEmpty()) path else "$path?$rendered"
    }

    public fun queryString(query: Iterable<Pair<String, String>>): String =
        query.joinToString("&") { (name, value) ->
            "${encodeQueryValue(name)}=${encodeQueryValue(value)}"
        }

    public fun encodePathSegment(value: String): String =
        URLEncoder
            .encode(value, StandardCharsets.UTF_8)
            .replace("+", "%20")

    private fun pageQuery(page: PageQuery): List<Pair<String, String>> =
        buildList {
            page.limit?.let { add("limit" to it.toString()) }
            page.offset?.let { add("offset" to it.toString()) }
        }

    private fun imageVariantQuery(variant: ImageVariantQuery): List<Pair<String, String>> =
        buildList {
            variant.width?.let { add("width" to it.toString()) }
            variant.height?.let { add("height" to it.toString()) }
        }

    private fun playbackCapabilitiesQuery(
        capabilities: PlaybackCapabilitiesQuery,
    ): List<Pair<String, String>> =
        buildList {
            capabilities.directPlay?.let {
                add("direct_play" to it.toString())
            }
            addCsv("container", capabilities.containers)
            addCsv("video_codec", capabilities.videoCodecs)
            addCsv("audio_codec", capabilities.audioCodecs)
        }

    private fun remuxPlaybackQuery(
        query: RemuxPlaybackQuery,
    ): List<Pair<String, String>> =
        buildList {
            query.directPlay?.let {
                add("direct_play" to it.toString())
            }
            addCsv("container", query.containers)
            addCsv("video_codec", query.videoCodecs)
            addCsv("audio_codec", query.audioCodecs)
            query.outputContainer?.let {
                add("output_container" to it.wireValue)
            }
        }

    private fun MutableList<Pair<String, String>>.addCsv(
        name: String,
        values: List<String>,
    ) {
        val cleaned = values.map(String::trim).filter(String::isNotEmpty)
        if (cleaned.isNotEmpty()) {
            add(name to cleaned.joinToString(","))
        }
    }

    private fun encodeQueryValue(value: String): String =
        URLEncoder.encode(value, StandardCharsets.UTF_8)
}


@Serializable
public enum class ClientPlaybackDecisionMode(
    public val wireValue: String,
) {
    @SerialName("direct_play")
    DirectPlay("direct_play"),

    @SerialName("remux")
    Remux("remux"),

    @SerialName("transcode")
    Transcode("transcode")

}

@Serializable
public enum class ClientTranscodePlanHardwareAcceleration(
    public val wireValue: String,
) {
    @SerialName("none")
    None("none"),

    @SerialName("vaapi")
    Vaapi("vaapi"),

    @SerialName("nvenc")
    Nvenc("nvenc"),

    @SerialName("quick_sync")
    QuickSync("quick_sync")

}

@Serializable
public enum class ClientTranscodePlanOutputContainer(
    public val wireValue: String,
) {
    @SerialName("hls")
    Hls("hls"),

    @SerialName("mp4")
    Mp4("mp4"),

    @SerialName("mkv")
    Mkv("mkv")

}

@Serializable
public enum class ErrorResponseCode(
    public val wireValue: String,
) {
    @SerialName("invalid_input")
    InvalidInput("invalid_input"),

    @SerialName("not_found")
    NotFound("not_found"),

    @SerialName("conflict")
    Conflict("conflict"),

    @SerialName("unsupported")
    Unsupported("unsupported"),

    @SerialName("unauthorized")
    Unauthorized("unauthorized"),

    @SerialName("forbidden")
    Forbidden("forbidden"),

    @SerialName("provider_error")
    ProviderError("provider_error"),

    @SerialName("storage_error")
    StorageError("storage_error"),

    @SerialName("ffmpeg_error")
    FfmpegError("ffmpeg_error"),

    @SerialName("staging_budget_exhausted")
    StagingBudgetExhausted("staging_budget_exhausted"),

    @SerialName("staging_validation_mismatch")
    StagingValidationMismatch("staging_validation_mismatch"),

    @SerialName("storage_timeout")
    StorageTimeout("storage_timeout"),

    @SerialName("storage_unauthorized")
    StorageUnauthorized("storage_unauthorized"),

    @SerialName("storage_rate_limited")
    StorageRateLimited("storage_rate_limited"),

    @SerialName("database_error")
    DatabaseError("database_error")

}

@Serializable
public enum class HealthResponseVersion(
    public val wireValue: String,
) {
    @SerialName("v1")
    V1("v1")

}

@Serializable
public enum class LibraryOptionsDtoDomain(
    public val wireValue: String,
) {
    @SerialName("video")
    Video("video"),

    @SerialName("audio")
    Audio("audio"),

    @SerialName("image")
    Image("image"),

    @SerialName("document")
    Document("document"),

    @SerialName("mixed")
    Mixed("mixed"),

    @SerialName("online")
    Online("online")

}

@Serializable
public enum class LibraryOptionsDtoNamingStrategy(
    public val wireValue: String,
) {
    @SerialName("movie")
    Movie("movie"),

    @SerialName("series")
    Series("series"),

    @SerialName("anime")
    Anime("anime"),

    @SerialName("music")
    Music("music"),

    @SerialName("podcast")
    Podcast("podcast"),

    @SerialName("photo")
    Photo("photo"),

    @SerialName("home_video")
    HomeVideo("home_video"),

    @SerialName("mixed")
    Mixed("mixed"),

    @SerialName("online_catalog")
    OnlineCatalog("online_catalog")

}

@Serializable
public enum class LibraryOptionsDtoPreset(
    public val wireValue: String,
) {
    @SerialName("movies")
    Movies("movies"),

    @SerialName("tv")
    Tv("tv"),

    @SerialName("anime")
    Anime("anime"),

    @SerialName("music")
    Music("music"),

    @SerialName("podcast")
    Podcast("podcast"),

    @SerialName("photos")
    Photos("photos"),

    @SerialName("home_video")
    HomeVideo("home_video"),

    @SerialName("mixed_video")
    MixedVideo("mixed_video"),

    @SerialName("online_catalog")
    OnlineCatalog("online_catalog"),

    @SerialName("custom")
    Custom("custom")

}

@Serializable
public enum class MetadataProfileDtoLocalMetadataPolicy(
    public val wireValue: String,
) {
    @SerialName("disabled")
    Disabled("disabled"),

    @SerialName("read_only")
    ReadOnly("read_only"),

    @SerialName("local_first")
    LocalFirst("local_first"),

    @SerialName("remote_first")
    RemoteFirst("remote_first"),

    @SerialName("write_sidecar")
    WriteSidecar("write_sidecar")

}

@Serializable
public enum class MetadataProfileDtoRefreshMode(
    public val wireValue: String,
) {
    @SerialName("none")
    None("none"),

    @SerialName("validation_only")
    ValidationOnly("validation_only"),

    @SerialName("default")
    Default("default"),

    @SerialName("missing_only")
    MissingOnly("missing_only"),

    @SerialName("full_refresh")
    FullRefresh("full_refresh")

}

@Serializable
public enum class TranscodeSessionDtoFailureCategory(
    public val wireValue: String,
) {
    @SerialName("invalid_request")
    InvalidRequest("invalid_request"),

    @SerialName("runner")
    Runner("runner"),

    @SerialName("timeout")
    Timeout("timeout"),

    @SerialName("storage")
    Storage("storage"),

    @SerialName("stale")
    Stale("stale"),

    @SerialName("cancelled")
    Cancelled("cancelled"),

    @SerialName("unknown")
    Unknown("unknown")

}

@Serializable
public enum class TranscodeSessionDtoKind(
    public val wireValue: String,
) {
    @SerialName("remux")
    Remux("remux"),

    @SerialName("hls_transcode")
    HlsTranscode("hls_transcode")

}

@Serializable
public enum class TranscodeSessionDtoState(
    public val wireValue: String,
) {
    @SerialName("planned")
    Planned("planned"),

    @SerialName("starting")
    Starting("starting"),

    @SerialName("running")
    Running("running"),

    @SerialName("cancel_requested")
    CancelRequested("cancel_requested"),

    @SerialName("cancelled")
    Cancelled("cancelled"),

    @SerialName("failed")
    Failed("failed"),

    @SerialName("finished")
    Finished("finished")

}

@Serializable
public data class CanonicalMetadataDto(
    public val collections: List<CollectionRefDto>,
    public val credits: List<CreditDto>,
    @SerialName("external_ids")
    public val externalIds: List<ExternalIdDto>,
    public val genres: List<String>,
    @SerialName("original_title")
    public val originalTitle: String?,
    public val overview: String?,
    public val ratings: List<ContentRatingDto>,
    @SerialName("release_date")
    public val releaseDate: String?,
    @SerialName("runtime_minutes")
    public val runtimeMinutes: Int?,
    @SerialName("sort_title")
    public val sortTitle: String?,
    public val studios: List<StudioRefDto>,
    public val tagline: String?,
    public val tags: List<String>,
    public val title: String,
)

@Serializable
public data class ClientDirectPlayPlan(
    @SerialName("content_type")
    public val contentType: String,
    @SerialName("source_id")
    public val sourceId: String,
    @SerialName("supports_range_requests")
    public val supportsRangeRequests: Boolean,
)

@Serializable
public enum class ClientMediaKind(
    public val wireValue: String,
) {
    @SerialName("movie")
    Movie("movie"),

    @SerialName("series")
    Series("series"),

    @SerialName("season")
    Season("season"),

    @SerialName("episode")
    Episode("episode"),

    @SerialName("collection")
    Collection("collection"),

    @SerialName("extra")
    Extra("extra"),

    @SerialName("unknown")
    Unknown("unknown")

}

@Serializable
public data class ClientPlaybackDecision(
    @SerialName("direct_play")
    public val directPlay: ClientDirectPlayPlan?,
    public val mode: ClientPlaybackDecisionMode,
    public val reason: String,
    @SerialName("transcode_plan")
    public val transcodePlan: ClientTranscodePlan?,
)

@Serializable
public data class ClientTranscodePlan(
    @SerialName("audio_codec")
    public val audioCodec: String?,
    @SerialName("hardware_acceleration")
    public val hardwareAcceleration: ClientTranscodePlanHardwareAcceleration,
    @SerialName("output_container")
    public val outputContainer: ClientTranscodePlanOutputContainer,
    @SerialName("video_codec")
    public val videoCodec: String?,
)

@Serializable
public data class CollectionItemDto(
    @SerialName("collection_id")
    public val collectionId: String,
    @SerialName("item_id")
    public val itemId: String,
    @SerialName("sort_order")
    public val sortOrder: Int?,
)

@Serializable
public data class CollectionRefDto(
    @SerialName("external_ids")
    public val externalIds: List<ExternalIdDto>,
    public val name: String,
    public val overview: String?,
    @SerialName("sort_order")
    public val sortOrder: Int?,
)

@Serializable
public data class ContentRatingDto(
    public val source: String,
    public val value: String,
)

@Serializable
public data class ContinueWatchingItemDto(
    public val images: List<PublicImageRefDto>,
    public val item: MediaItemDto,
    public val state: UserPlaybackStateDto,
)

@Serializable
public data class ContinueWatchingResponse(
    public val items: List<ContinueWatchingItemDto>,
    public val page: PageInfo,
)

@Serializable
public data class CreditDto(
    public val character: String?,
    @SerialName("external_ids")
    public val externalIds: List<ExternalIdDto>,
    public val name: String,
    public val order: Int?,
    public val role: String,
)

@Serializable
public data class ErrorResponse(
    public val code: ErrorResponseCode,
    public val message: String,
)

@Serializable
public data class ExternalIdDto(
    public val provider: String,
    public val value: String,
)

@Serializable
public data class GenreDto(
    public val id: String,
    public val name: String,
    public val source: String,
)

@Serializable
public data class GenreItemsResponse(
    public val genre: GenreDto,
    public val items: List<MediaItemDto>,
    public val page: PageInfo,
)

@Serializable
public data class GenreListResponse(
    public val genres: List<GenreDto>,
    public val page: PageInfo,
)

@Serializable
public data class HealthResponse(
    public val status: String,
    public val version: HealthResponseVersion,
)

@Serializable
public data class ImagesResponse(
    public val images: List<PublicImageRefDto>,
    @SerialName("item_id")
    public val itemId: String,
)

@Serializable
public data class ItemCreditDto(
    public val character: String?,
    @SerialName("item_id")
    public val itemId: String,
    @SerialName("person_id")
    public val personId: String,
    public val role: String,
    @SerialName("sort_order")
    public val sortOrder: Int?,
)

@Serializable
public data class ItemCreditsResponse(
    public val credits: List<ItemCreditDto>,
    @SerialName("item_id")
    public val itemId: String,
    public val people: List<PersonDto>,
)

@Serializable
public data class ItemDetailResponse(
    public val collections: List<CollectionItemDto>,
    public val credits: List<ItemCreditDto>,
    public val genres: List<ItemGenreDto>,
    public val images: List<PublicImageRefDto>,
    public val item: MediaItemDto,
    public val sources: List<MediaSourceDto>,
    public val studios: List<ItemStudioDto>,
    public val tags: List<ItemTagDto>,
)

@Serializable
public data class ItemGenreDto(
    @SerialName("genre_id")
    public val genreId: String,
    @SerialName("item_id")
    public val itemId: String,
)

@Serializable
public data class ItemStudioDto(
    @SerialName("item_id")
    public val itemId: String,
    @SerialName("studio_id")
    public val studioId: String,
)

@Serializable
public data class ItemTagDto(
    @SerialName("item_id")
    public val itemId: String,
    @SerialName("tag_id")
    public val tagId: String,
)

@Serializable
public data class ItemsResponse(
    public val items: List<MediaItemDto>,
    public val page: PageInfo,
)

@Serializable
public data class LibraryDto(
    public val id: String,
    public val name: String,
    public val options: LibraryOptionsDto,
    public val roots: List<String>,
)

@Serializable
public data class LibraryListResponse(
    public val libraries: List<LibraryDto>,
    public val page: PageInfo,
)

@Serializable
public data class LibraryOptionsDto(
    public val domain: LibraryOptionsDtoDomain,
    @SerialName("metadata_profile")
    public val metadataProfile: MetadataProfileDto,
    @SerialName("naming_strategy")
    public val namingStrategy: LibraryOptionsDtoNamingStrategy,
    public val preset: LibraryOptionsDtoPreset,
    public val scan: LibraryScanOptionsDto,
)

@Serializable
public data class LibraryResponse(
    public val library: LibraryDto,
)

@Serializable
public data class LibraryScanOptionsDto(
    @SerialName("max_depth")
    public val maxDepth: Int?,
    @SerialName("realtime_monitor")
    public val realtimeMonitor: Boolean,
)

@Serializable
public data class LibrarySourceResponse(
    public val item: MediaItemDto?,
    public val probe: MediaProbeDto?,
    public val source: MediaSourceDto,
)

@Serializable
public data class LibrarySourcesResponse(
    public val library: LibraryDto,
    public val page: PageInfo,
    public val sources: List<LibrarySourceResponse>,
)

@Serializable
public data class MediaItemDto(
    public val id: String,
    public val kind: ClientMediaKind,
    public val metadata: CanonicalMetadataDto,
    @SerialName("parent_id")
    public val parentId: String?,
)

@Serializable
public data class MediaProbeDto(
    @SerialName("bit_rate")
    public val bitRate: Long?,
    public val container: String?,
    @SerialName("duration_ms")
    public val durationMs: Long?,
    public val streams: List<MediaStreamDto>,
)

@Serializable
public data class MediaSourceDto(
    @SerialName("file_name")
    public val fileName: String,
    public val fingerprint: String?,
    public val id: String,
    @SerialName("item_id")
    public val itemId: String,
    @SerialName("library_id")
    public val libraryId: String,
    @SerialName("size_bytes")
    public val sizeBytes: Long?,
)

@Serializable
public data class MediaStreamDto(
    @SerialName("bit_rate")
    public val bitRate: Long?,
    public val channels: Int?,
    public val codec: String?,
    @SerialName("duration_ms")
    public val durationMs: Long?,
    public val height: Int?,
    public val index: Int,
    public val kind: String,
    public val language: String?,
    @SerialName("sample_rate")
    public val sampleRate: Int?,
    public val width: Int?,
)

@Serializable
public data class MetadataProfileDto(
    public val country: String?,
    @SerialName("image_providers")
    public val imageProviders: List<String>,
    @SerialName("item_kinds")
    public val itemKinds: List<ClientMediaKind>,
    public val language: String?,
    @SerialName("local_metadata_policy")
    public val localMetadataPolicy: MetadataProfileDtoLocalMetadataPolicy,
    @SerialName("local_readers")
    public val localReaders: List<String>,
    @SerialName("metadata_providers")
    public val metadataProviders: List<String>,
    @SerialName("refresh_mode")
    public val refreshMode: MetadataProfileDtoRefreshMode,
)

@Serializable
public data class PageInfo(
    public val limit: Int,
    public val offset: Long,
    public val returned: Int,
)

@Serializable
public data class PeopleResponse(
    public val page: PageInfo,
    public val people: List<PersonDto>,
)

@Serializable
public data class PersonDto(
    @SerialName("external_ids")
    public val externalIds: List<ExternalIdDto>,
    public val id: String,
    public val name: String,
    public val overview: String?,
    @SerialName("sort_name")
    public val sortName: String?,
)

@Serializable
public data class PersonItemsResponse(
    public val items: List<MediaItemDto>,
    public val page: PageInfo,
    public val person: PersonDto,
)

@Serializable
public data class PersonResponse(
    public val person: PersonDto,
)

@Serializable
public data class PlaybackDecisionResponse(
    public val decision: ClientPlaybackDecision,
    public val probe: MediaProbeDto?,
    public val source: MediaSourceDto,
)

@Serializable
public data class PublicImageRefDto(
    public val etag: String?,
    public val height: Int?,
    public val id: String,
    public val kind: String,
    public val language: String?,
    @SerialName("media_type")
    public val mediaType: String?,
    public val owner: Map<String, String>,
    public val url: String,
    public val width: Int?,
)

@Serializable
public data class SearchItemHit(
    public val item: MediaItemDto,
    public val score: Float,
)

@Serializable
public data class SearchResponse(
    public val hits: List<SearchItemHit>,
    public val page: PageInfo,
)

@Serializable
public data class SetWatchedStateRequest(
    @SerialName("duration_ms")
    public val durationMs: Long? = null,
    @SerialName("marked_at")
    public val markedAt: String? = null,
    @SerialName("position_ms")
    public val positionMs: Long? = null,
    @SerialName("source_id")
    public val sourceId: String? = null,
    public val watched: Boolean,
)

@Serializable
public data class SourceProbeResponse(
    public val probe: MediaProbeDto,
    @SerialName("source_id")
    public val sourceId: String,
)

@Serializable
public data class StudioRefDto(
    @SerialName("external_ids")
    public val externalIds: List<ExternalIdDto>,
    public val name: String,
)

@Serializable
public data class TagDto(
    public val id: String,
    public val name: String,
    public val source: String,
)

@Serializable
public data class TagItemsResponse(
    public val items: List<MediaItemDto>,
    public val page: PageInfo,
    public val tag: TagDto,
)

@Serializable
public data class TagsResponse(
    public val page: PageInfo,
    public val tags: List<TagDto>,
)

@Serializable
public data class TranscodeSessionDto(
    @SerialName("completed_at")
    public val completedAt: String?,
    @SerialName("created_at")
    public val createdAt: String,
    @SerialName("failure_category")
    public val failureCategory: TranscodeSessionDtoFailureCategory?,
    @SerialName("failure_message")
    public val failureMessage: String?,
    public val id: String,
    public val kind: TranscodeSessionDtoKind,
    @SerialName("request_key")
    public val requestKey: String,
    @SerialName("source_id")
    public val sourceId: String,
    @SerialName("started_at")
    public val startedAt: String?,
    public val state: TranscodeSessionDtoState,
    @SerialName("updated_at")
    public val updatedAt: String,
)

@Serializable
public data class TranscodeSessionResponse(
    public val session: TranscodeSessionDto,
)

@Serializable
public data class UpdatePlaybackProgressRequest(
    @SerialName("duration_ms")
    public val durationMs: Long? = null,
    @SerialName("position_ms")
    public val positionMs: Long,
    @SerialName("reported_at")
    public val reportedAt: String? = null,
    @SerialName("source_id")
    public val sourceId: String? = null,
)

@Serializable
public data class UserPlaybackStateDto(
    @SerialName("duration_ms")
    public val durationMs: Long?,
    @SerialName("item_id")
    public val itemId: String,
    @SerialName("last_played_at")
    public val lastPlayedAt: String?,
    @SerialName("progress_percent")
    public val progressPercent: Float?,
    @SerialName("resume_position_ms")
    public val resumePositionMs: Long?,
    @SerialName("source_id")
    public val sourceId: String?,
    @SerialName("updated_at")
    public val updatedAt: String?,
    public val version: Long,
    public val watched: Boolean,
    @SerialName("watched_at")
    public val watchedAt: String?,
)

@Serializable
public data class UserPlaybackStateResponse(
    public val state: UserPlaybackStateDto,
)
