[package]
name = "taru-db"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
serde_json.workspace = true
sqlx.workspace = true
taru-core = { path = "../taru-core" }
taru-search = { path = "../taru-search" }

[dev-dependencies]
sqlx = { workspace = true, features = ["postgres", "uuid"] }
tempfile.workspace = true
tokio.workspace = true
