[package]
name = "taru-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
taru-db = { path = "../taru-db" }
taru-core = { path = "../taru-core" }
taru-library = { path = "../taru-library" }
taru-media-probe = { path = "../taru-media-probe" }
taru-vfs = { path = "../taru-vfs" }
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
