[package]
name = "taru-catalog"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
taru-core = { path = "../taru-core" }
taru-search = { path = "../taru-search" }

[dev-dependencies]
pollster = { workspace = true }
taru-db = { path = "../taru-db" }
tokio = { workspace = true }
